/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// AboutApplyConfiguration represents a declarative configuration of the About type for use
// with apply.
//
// About contains descriptive information about a repository.
type AboutApplyConfiguration struct {
	// Description is a short description of the repository displayed on the repository page.
	Description *string `json:"description,omitempty"`
	// Website is the URL of the repository's homepage or documentation.
	// Must be a valid HTTP or HTTPS URL.
	Website *string `json:"website,omitempty"`
	// Topics is a list of topics (tags) that categorize and help discover the repository.
	// Topics appear on the repository page and in GitHub's topic explorer.
	// See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics
	Topics []TopicApplyConfiguration `json:"topics,omitempty"`
}

// AboutApplyConfiguration constructs a declarative configuration of the About type for use with
// apply.
func About() *AboutApplyConfiguration {
	return &AboutApplyConfiguration{}
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *AboutApplyConfiguration) WithDescription(value string) *AboutApplyConfiguration {
	b.Description = &value
	return b
}

// WithWebsite sets the Website field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Website field is set to the value of the last call.
func (b *AboutApplyConfiguration) WithWebsite(value string) *AboutApplyConfiguration {
	b.Website = &value
	return b
}

// WithTopics adds the given value to the Topics field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Topics field.
func (b *AboutApplyConfiguration) WithTopics(values ...*TopicApplyConfiguration) *AboutApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTopics")
		}
		b.Topics = append(b.Topics, *values[i])
	}
	return b
}
