/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// ActionsSettingsApplyConfiguration represents a declarative configuration of the ActionsSettings type for use
// with apply.
//
// ActionsSettings configures GitHub Actions permissions and behavior for an organization.
// See: https://docs.github.com/en/rest/actions/permissions
type ActionsSettingsApplyConfiguration struct {
	// EnabledRepositories determines which repositories can use GitHub Actions.
	// - "all": Actions enabled for all repositories
	// - "none": Actions disabled for all repositories
	// - "selected": Actions enabled for specific repositories (requires additional configuration)
	EnabledRepositories *string `json:"enabledRepositories,omitempty"`
	// AllowedActions configures which actions and workflows are allowed to run.
	// Must be nil if EnabledRepositories is "none".
	// - "all": All actions and reusable workflows are allowed
	// - "local_only": Only actions and workflows defined in the same repository or organization are allowed
	// - "selected": Only specific actions are allowed (requires SelectedAllowedActions)
	AllowedActions *string `json:"allowedActions,omitempty"`
	// SelectedAllowedActions specifies which actions are allowed when AllowedActions is "selected".
	// This field is required when AllowedActions is "selected" and ignored otherwise.
	SelectedAllowedActions *SelectedAllowedActionsApplyConfiguration `json:"selectedAllowedActions,omitempty"`
	// ShaPinningRequired determines whether workflows must reference actions using the commit SHA instead of tags or branches.
	// When true, improves security by preventing tag manipulation attacks.
	ShaPinningRequired *bool `json:"shaPinningRequired,omitempty"`
	// DefaultWorkflowPermissions sets the default GITHUB_TOKEN permissions for workflows.
	// - "read": Token has read-only access to repository contents
	// - "write": Token has read and write access to repository contents
	DefaultWorkflowPermissions *string `json:"defaultWorkflowPermissions,omitempty"`
	// CanApprovePullRequestReviews determines whether the GITHUB_TOKEN can approve pull requests.
	// When false, prevents workflows from approving pull requests automatically.
	CanApprovePullRequestReviews *bool `json:"canApprovePullRequestReviews,omitempty"`
	// ArtifactAndLogRetentionDays specifies how many days workflow artifacts and logs are retained.
	// Must be between 1 and 400 days. Shorter retention periods reduce storage costs.
	ArtifactAndLogRetentionDays *int `json:"artifactAndLogRetentionDays,omitempty"`
	// RunnerGroups configures self-hosted runner groups for the organization.
	// Each group can have different visibility and workflow restrictions.
	RunnerGroups []RunnerGroupApplyConfiguration `json:"runnerGroups,omitempty"`
}

// ActionsSettingsApplyConfiguration constructs a declarative configuration of the ActionsSettings type for use with
// apply.
func ActionsSettings() *ActionsSettingsApplyConfiguration {
	return &ActionsSettingsApplyConfiguration{}
}

// WithEnabledRepositories sets the EnabledRepositories field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EnabledRepositories field is set to the value of the last call.
func (b *ActionsSettingsApplyConfiguration) WithEnabledRepositories(value string) *ActionsSettingsApplyConfiguration {
	b.EnabledRepositories = &value
	return b
}

// WithAllowedActions sets the AllowedActions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllowedActions field is set to the value of the last call.
func (b *ActionsSettingsApplyConfiguration) WithAllowedActions(value string) *ActionsSettingsApplyConfiguration {
	b.AllowedActions = &value
	return b
}

// WithSelectedAllowedActions sets the SelectedAllowedActions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SelectedAllowedActions field is set to the value of the last call.
func (b *ActionsSettingsApplyConfiguration) WithSelectedAllowedActions(value *SelectedAllowedActionsApplyConfiguration) *ActionsSettingsApplyConfiguration {
	b.SelectedAllowedActions = value
	return b
}

// WithShaPinningRequired sets the ShaPinningRequired field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ShaPinningRequired field is set to the value of the last call.
func (b *ActionsSettingsApplyConfiguration) WithShaPinningRequired(value bool) *ActionsSettingsApplyConfiguration {
	b.ShaPinningRequired = &value
	return b
}

// WithDefaultWorkflowPermissions sets the DefaultWorkflowPermissions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefaultWorkflowPermissions field is set to the value of the last call.
func (b *ActionsSettingsApplyConfiguration) WithDefaultWorkflowPermissions(value string) *ActionsSettingsApplyConfiguration {
	b.DefaultWorkflowPermissions = &value
	return b
}

// WithCanApprovePullRequestReviews sets the CanApprovePullRequestReviews field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CanApprovePullRequestReviews field is set to the value of the last call.
func (b *ActionsSettingsApplyConfiguration) WithCanApprovePullRequestReviews(value bool) *ActionsSettingsApplyConfiguration {
	b.CanApprovePullRequestReviews = &value
	return b
}

// WithArtifactAndLogRetentionDays sets the ArtifactAndLogRetentionDays field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ArtifactAndLogRetentionDays field is set to the value of the last call.
func (b *ActionsSettingsApplyConfiguration) WithArtifactAndLogRetentionDays(value int) *ActionsSettingsApplyConfiguration {
	b.ArtifactAndLogRetentionDays = &value
	return b
}

// WithRunnerGroups adds the given value to the RunnerGroups field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the RunnerGroups field.
func (b *ActionsSettingsApplyConfiguration) WithRunnerGroups(values ...*RunnerGroupApplyConfiguration) *ActionsSettingsApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithRunnerGroups")
		}
		b.RunnerGroups = append(b.RunnerGroups, *values[i])
	}
	return b
}
