/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// AutolinkApplyConfiguration represents a declarative configuration of the Autolink type for use
// with apply.
//
// Autolink defines an automatic link reference for external resources.
// When a reference matching KeyPrefix is found in issues, pull requests, or commit messages,
// GitHub automatically converts it to a clickable link using the URLTemplate.
// See: https://docs.github.com/en/rest/repos/autolinks
type AutolinkApplyConfiguration struct {
	// KeyPrefix is the text prefix that triggers autolink creation.
	// When text starts with this prefix followed by a reference, it becomes a link.
	// Examples: "JIRA-", "TICKET-", "BUG-"
	KeyPrefix *string `json:"keyPrefix,omitempty"`
	// URLTemplate is the URL pattern used to generate links.
	// Use <num> as a placeholder for the reference number/ID.
	// Example: "https://jira.example.com/browse/<num>" converts "JIRA-123" to "https://jira.example.com/browse/123"
	URLTemplate *string `json:"urlTemplate,omitempty"`
	// IsAlphanumeric determines whether the reference must be alphanumeric.
	// - true: the <num> parameter of the url_template matches alphanumeric characters `A-Z` (case insensitive), `0-9`, and `-`
	// - false: reference only matches numeric characters.
	IsAlphanumeric *bool `json:"isAlphanumeric,omitempty"`
}

// AutolinkApplyConfiguration constructs a declarative configuration of the Autolink type for use with
// apply.
func Autolink() *AutolinkApplyConfiguration {
	return &AutolinkApplyConfiguration{}
}

// WithKeyPrefix sets the KeyPrefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KeyPrefix field is set to the value of the last call.
func (b *AutolinkApplyConfiguration) WithKeyPrefix(value string) *AutolinkApplyConfiguration {
	b.KeyPrefix = &value
	return b
}

// WithURLTemplate sets the URLTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URLTemplate field is set to the value of the last call.
func (b *AutolinkApplyConfiguration) WithURLTemplate(value string) *AutolinkApplyConfiguration {
	b.URLTemplate = &value
	return b
}

// WithIsAlphanumeric sets the IsAlphanumeric field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IsAlphanumeric field is set to the value of the last call.
func (b *AutolinkApplyConfiguration) WithIsAlphanumeric(value bool) *AutolinkApplyConfiguration {
	b.IsAlphanumeric = &value
	return b
}
