/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// AutolinksPresetSpecApplyConfiguration represents a declarative configuration of the AutolinksPresetSpec type for use
// with apply.
//
// EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
// NOTE: json tags are required.  Any new fields you add must have json tags for the fields to be serialized.
// AutolinksPresetSpec defines the desired state of AutolinksPreset.
// Autolinks automatically convert references to external resources (like issue trackers) into clickable links.
// See: https://docs.github.com/en/rest/repos/autolinks
type AutolinksPresetSpecApplyConfiguration struct {
	// AutolinkList is a list of autolink configurations to create in repositories.
	// Each autolink defines a prefix that triggers link generation and a URL template.
	AutolinkList []AutolinkApplyConfiguration `json:"autolinks,omitempty"`
}

// AutolinksPresetSpecApplyConfiguration constructs a declarative configuration of the AutolinksPresetSpec type for use with
// apply.
func AutolinksPresetSpec() *AutolinksPresetSpecApplyConfiguration {
	return &AutolinksPresetSpecApplyConfiguration{}
}

// WithAutolinkList adds the given value to the AutolinkList field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AutolinkList field.
func (b *AutolinksPresetSpecApplyConfiguration) WithAutolinkList(values ...*AutolinkApplyConfiguration) *AutolinksPresetSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAutolinkList")
		}
		b.AutolinkList = append(b.AutolinkList, *values[i])
	}
	return b
}
