/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// BypassReviewerApplyConfiguration represents a declarative configuration of the BypassReviewer type for use
// with apply.
//
// BypassReviewer represents a team or role that can review secret scanning bypass requests.
// Either ReviewerId (for direct ID specification) or ReviewerName (for name-based resolution) must be set.
// See: https://docs.github.com/en/rest/code-security/configurations
type BypassReviewerApplyConfiguration struct {
	// ReviewerId is the numeric ID of the reviewer (team ID or role ID).
	// This field is mutually exclusive with ReviewerName.
	ReviewerId *int64 `json:"reviewerId,omitempty"`
	// ReviewerName is the name of the reviewer (team slug or role name) which will be resolved to an ID based on the ReviewerType.
	// This field is mutually exclusive with ReviewerId.
	// For TEAM type, this should be the team slug.
	// For ROLE type, this should be the role name.
	ReviewerName *string `json:"reviewerName,omitempty"`
	// ReviewerType specifies the type of reviewer.
	// - "TEAM": A team within the organization (use team slug for ReviewerName)
	// - "ROLE": An organization role (use role name for ReviewerName)
	ReviewerType *string `json:"reviewerType,omitempty"`
}

// BypassReviewerApplyConfiguration constructs a declarative configuration of the BypassReviewer type for use with
// apply.
func BypassReviewer() *BypassReviewerApplyConfiguration {
	return &BypassReviewerApplyConfiguration{}
}

// WithReviewerId sets the ReviewerId field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReviewerId field is set to the value of the last call.
func (b *BypassReviewerApplyConfiguration) WithReviewerId(value int64) *BypassReviewerApplyConfiguration {
	b.ReviewerId = &value
	return b
}

// WithReviewerName sets the ReviewerName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReviewerName field is set to the value of the last call.
func (b *BypassReviewerApplyConfiguration) WithReviewerName(value string) *BypassReviewerApplyConfiguration {
	b.ReviewerName = &value
	return b
}

// WithReviewerType sets the ReviewerType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReviewerType field is set to the value of the last call.
func (b *BypassReviewerApplyConfiguration) WithReviewerType(value string) *BypassReviewerApplyConfiguration {
	b.ReviewerType = &value
	return b
}
