/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/Interhyp/git-hubby/api/v1alpha1"
	internal "github.com/Interhyp/git-hubby/api/v1alpha1/applyconfiguration/internal"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// CodeSecurityConfigurationApplyConfiguration represents a declarative configuration of the CodeSecurityConfiguration type for use
// with apply.
//
// CodeSecurityConfiguration is the Schema for the codesecurityconfigurations API
type CodeSecurityConfigurationApplyConfiguration struct {
	v1.TypeMetaApplyConfiguration `json:",inline"`
	// metadata is a standard object metadata
	*v1.ObjectMetaApplyConfiguration `json:"metadata,omitempty"`
	// spec defines the desired state of CodeSecurityConfiguration
	Spec *CodeSecurityConfigurationSpecApplyConfiguration `json:"spec,omitempty"`
	// status defines the observed state of CodeSecurityConfiguration
	Status *CodeSecurityConfigurationStatusApplyConfiguration `json:"status,omitempty"`
}

// CodeSecurityConfiguration constructs a declarative configuration of the CodeSecurityConfiguration type for use with
// apply.
func CodeSecurityConfiguration(name, namespace string) *CodeSecurityConfigurationApplyConfiguration {
	b := &CodeSecurityConfigurationApplyConfiguration{}
	b.WithName(name)
	b.WithNamespace(namespace)
	b.WithKind("CodeSecurityConfiguration")
	b.WithAPIVersion("github.interhyp.de/v1alpha1")
	return b
}

// ExtractCodeSecurityConfigurationFrom extracts the applied configuration owned by fieldManager from
// codeSecurityConfiguration for the specified subresource. Pass an empty string for subresource to extract
// the main resource. Common subresources include "status", "scale", etc.
// codeSecurityConfiguration must be a unmodified CodeSecurityConfiguration API object that was retrieved from the Kubernetes API.
// ExtractCodeSecurityConfigurationFrom provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractCodeSecurityConfigurationFrom(codeSecurityConfiguration *apiv1alpha1.CodeSecurityConfiguration, fieldManager string, subresource string) (*CodeSecurityConfigurationApplyConfiguration, error) {
	b := &CodeSecurityConfigurationApplyConfiguration{}
	err := managedfields.ExtractInto(codeSecurityConfiguration, internal.Parser().Type("com.github.Interhyp.git-hubby.api.v1alpha1.CodeSecurityConfiguration"), fieldManager, b, subresource)
	if err != nil {
		return nil, err
	}
	b.WithName(codeSecurityConfiguration.Name)
	b.WithNamespace(codeSecurityConfiguration.Namespace)

	b.WithKind("CodeSecurityConfiguration")
	b.WithAPIVersion("github.interhyp.de/v1alpha1")
	return b, nil
}

// ExtractCodeSecurityConfiguration extracts the applied configuration owned by fieldManager from
// codeSecurityConfiguration. If no managedFields are found in codeSecurityConfiguration for fieldManager, a
// CodeSecurityConfigurationApplyConfiguration is returned with only the Name, Namespace (if applicable),
// APIVersion and Kind populated. It is possible that no managed fields were found for because other
// field managers have taken ownership of all the fields previously owned by fieldManager, or because
// the fieldManager never owned fields any fields.
// codeSecurityConfiguration must be a unmodified CodeSecurityConfiguration API object that was retrieved from the Kubernetes API.
// ExtractCodeSecurityConfiguration provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractCodeSecurityConfiguration(codeSecurityConfiguration *apiv1alpha1.CodeSecurityConfiguration, fieldManager string) (*CodeSecurityConfigurationApplyConfiguration, error) {
	return ExtractCodeSecurityConfigurationFrom(codeSecurityConfiguration, fieldManager, "")
}

// ExtractCodeSecurityConfigurationStatus extracts the applied configuration owned by fieldManager from
// codeSecurityConfiguration for the status subresource.
func ExtractCodeSecurityConfigurationStatus(codeSecurityConfiguration *apiv1alpha1.CodeSecurityConfiguration, fieldManager string) (*CodeSecurityConfigurationApplyConfiguration, error) {
	return ExtractCodeSecurityConfigurationFrom(codeSecurityConfiguration, fieldManager, "status")
}

func (b CodeSecurityConfigurationApplyConfiguration) IsApplyConfiguration() {}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *CodeSecurityConfigurationApplyConfiguration) WithKind(value string) *CodeSecurityConfigurationApplyConfiguration {
	b.TypeMetaApplyConfiguration.Kind = &value
	return b
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *CodeSecurityConfigurationApplyConfiguration) WithAPIVersion(value string) *CodeSecurityConfigurationApplyConfiguration {
	b.TypeMetaApplyConfiguration.APIVersion = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *CodeSecurityConfigurationApplyConfiguration) WithName(value string) *CodeSecurityConfigurationApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Name = &value
	return b
}

// WithGenerateName sets the GenerateName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GenerateName field is set to the value of the last call.
func (b *CodeSecurityConfigurationApplyConfiguration) WithGenerateName(value string) *CodeSecurityConfigurationApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.GenerateName = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *CodeSecurityConfigurationApplyConfiguration) WithNamespace(value string) *CodeSecurityConfigurationApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Namespace = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *CodeSecurityConfigurationApplyConfiguration) WithUID(value types.UID) *CodeSecurityConfigurationApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.UID = &value
	return b
}

// WithResourceVersion sets the ResourceVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceVersion field is set to the value of the last call.
func (b *CodeSecurityConfigurationApplyConfiguration) WithResourceVersion(value string) *CodeSecurityConfigurationApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.ResourceVersion = &value
	return b
}

// WithGeneration sets the Generation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generation field is set to the value of the last call.
func (b *CodeSecurityConfigurationApplyConfiguration) WithGeneration(value int64) *CodeSecurityConfigurationApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Generation = &value
	return b
}

// WithCreationTimestamp sets the CreationTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreationTimestamp field is set to the value of the last call.
func (b *CodeSecurityConfigurationApplyConfiguration) WithCreationTimestamp(value metav1.Time) *CodeSecurityConfigurationApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.CreationTimestamp = &value
	return b
}

// WithDeletionTimestamp sets the DeletionTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionTimestamp field is set to the value of the last call.
func (b *CodeSecurityConfigurationApplyConfiguration) WithDeletionTimestamp(value metav1.Time) *CodeSecurityConfigurationApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionTimestamp = &value
	return b
}

// WithDeletionGracePeriodSeconds sets the DeletionGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionGracePeriodSeconds field is set to the value of the last call.
func (b *CodeSecurityConfigurationApplyConfiguration) WithDeletionGracePeriodSeconds(value int64) *CodeSecurityConfigurationApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionGracePeriodSeconds = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *CodeSecurityConfigurationApplyConfiguration) WithLabels(entries map[string]string) *CodeSecurityConfigurationApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Labels == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *CodeSecurityConfigurationApplyConfiguration) WithAnnotations(entries map[string]string) *CodeSecurityConfigurationApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Annotations == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Annotations[k] = v
	}
	return b
}

// WithOwnerReferences adds the given value to the OwnerReferences field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OwnerReferences field.
func (b *CodeSecurityConfigurationApplyConfiguration) WithOwnerReferences(values ...*v1.OwnerReferenceApplyConfiguration) *CodeSecurityConfigurationApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOwnerReferences")
		}
		b.ObjectMetaApplyConfiguration.OwnerReferences = append(b.ObjectMetaApplyConfiguration.OwnerReferences, *values[i])
	}
	return b
}

// WithFinalizers adds the given value to the Finalizers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Finalizers field.
func (b *CodeSecurityConfigurationApplyConfiguration) WithFinalizers(values ...string) *CodeSecurityConfigurationApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		b.ObjectMetaApplyConfiguration.Finalizers = append(b.ObjectMetaApplyConfiguration.Finalizers, values[i])
	}
	return b
}

func (b *CodeSecurityConfigurationApplyConfiguration) ensureObjectMetaApplyConfigurationExists() {
	if b.ObjectMetaApplyConfiguration == nil {
		b.ObjectMetaApplyConfiguration = &v1.ObjectMetaApplyConfiguration{}
	}
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *CodeSecurityConfigurationApplyConfiguration) WithSpec(value *CodeSecurityConfigurationSpecApplyConfiguration) *CodeSecurityConfigurationApplyConfiguration {
	b.Spec = value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *CodeSecurityConfigurationApplyConfiguration) WithStatus(value *CodeSecurityConfigurationStatusApplyConfiguration) *CodeSecurityConfigurationApplyConfiguration {
	b.Status = value
	return b
}

// GetKind retrieves the value of the Kind field in the declarative configuration.
func (b *CodeSecurityConfigurationApplyConfiguration) GetKind() *string {
	return b.TypeMetaApplyConfiguration.Kind
}

// GetAPIVersion retrieves the value of the APIVersion field in the declarative configuration.
func (b *CodeSecurityConfigurationApplyConfiguration) GetAPIVersion() *string {
	return b.TypeMetaApplyConfiguration.APIVersion
}

// GetName retrieves the value of the Name field in the declarative configuration.
func (b *CodeSecurityConfigurationApplyConfiguration) GetName() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Name
}

// GetNamespace retrieves the value of the Namespace field in the declarative configuration.
func (b *CodeSecurityConfigurationApplyConfiguration) GetNamespace() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Namespace
}
