/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// CodeScanningOptionsApplyConfiguration represents a declarative configuration of the CodeScanningOptions type for use
// with apply.
//
// CodeScanningOptions configures code scanning feature options for a security configuration.
// See: https://docs.github.com/en/rest/code-security/configurations
type CodeScanningOptionsApplyConfiguration struct {
	// AllowAdvanced determines whether users can enable advanced code scanning features.
	// When true, repository administrators can configure advanced code scanning settings beyond the default setup.
	AllowAdvanced *bool `json:"allowAdvanced,omitempty"`
}

// CodeScanningOptionsApplyConfiguration constructs a declarative configuration of the CodeScanningOptions type for use with
// apply.
func CodeScanningOptions() *CodeScanningOptionsApplyConfiguration {
	return &CodeScanningOptionsApplyConfiguration{}
}

// WithAllowAdvanced sets the AllowAdvanced field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllowAdvanced field is set to the value of the last call.
func (b *CodeScanningOptionsApplyConfiguration) WithAllowAdvanced(value bool) *CodeScanningOptionsApplyConfiguration {
	b.AllowAdvanced = &value
	return b
}
