/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// CodeSecurityConfigurationSpecApplyConfiguration represents a declarative configuration of the CodeSecurityConfigurationSpec type for use
// with apply.
//
// EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
// NOTE: json tags are required.  Any new fields you add must have json tags for the fields to be serialized.
// CodeSecurityConfigurationSpec defines the desired state of CodeSecurityConfiguration.
// A code security configuration defines a set of security features and settings that can be applied
// to repositories in an organization. This is a configuration-only CRD with no dedicated controller;
// it is reconciled by the Organization controller.
// Please note that activating features may cause additional costs as the code security features are billed additionally.
// See: https://docs.github.com/en/rest/code-security/configurations
type CodeSecurityConfigurationSpecApplyConfiguration struct {
	// Name is the display name of the code security configuration.
	Name *string `json:"name,omitempty"`
	// Description provides additional information about the configuration's purpose and settings.
	Description *string `json:"description,omitempty"`
	// AdvancedSecurity enables or disables GitHub Advanced Security features.
	// - "enabled": Enable Advanced Security (required for code scanning, secret scanning, and dependency review)
	// - "disabled": Disable Advanced Security
	// - "code_security": Enable code security features only
	// - "secret_protection": Enable secret protection features only
	// Warning: code_security and secret_protection are deprecated values for this field.
	// Prefer the individual code_security and secret_protection fields to set the status of these features.
	// See: https://docs.github.com/en/get-started/learning-about-github/about-github-advanced-security
	AdvancedSecurity *string `json:"advancedSecurity,omitempty"`
	// DependencyGraph enables or disables the dependency graph.
	// The dependency graph identifies all dependencies in your repository.
	// - "enabled": Enable dependency graph
	// - "disabled": Disable dependency graph
	// - "not_set": Use default organization or repository setting
	// See: https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-the-dependency-graph
	DependencyGraph *string `json:"dependencyGraph,omitempty"`
	// DependencyGraphAutosubmitAction enables automatic submission of dependency information.
	// When enabled, dependency information is automatically submitted from Actions workflows.
	DependencyGraphAutosubmitAction *string `json:"dependencyGraphAutosubmitAction,omitempty"`
	// DependencyGraphAutosubmitActionOptions configures options for automatic dependency submission.
	DependencyGraphAutosubmitActionOptions *DependencyGraphAutosubmitActionOptionsApplyConfiguration `json:"dependencyGraphAutosubmitActionOptions,omitempty"`
	// DependabotAlerts enables or disables Dependabot alerts for vulnerable dependencies.
	// Requires DependencyGraph to be enabled.
	// See: https://docs.github.com/en/code-security/dependabot/dependabot-alerts/about-dependabot-alerts
	DependabotAlerts *string `json:"dependabotAlerts,omitempty"`
	// DependabotSecurityUpdates enables or disables Dependabot security updates.
	// When enabled, Dependabot automatically creates pull requests to update vulnerable dependencies.
	// Requires DependabotAlerts to be enabled.
	// See: https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/about-dependabot-security-updates
	DependabotSecurityUpdates *string `json:"dependabotSecurityUpdates,omitempty"`
	// CodeScanningDefaultSetup enables or disables default code scanning setup.
	// Default setup automatically configures code scanning with recommended settings.
	// See: https://docs.github.com/en/code-security/code-scanning/enabling-code-scanning/configuring-default-setup-for-code-scanning
	CodeScanningDefaultSetup *string `json:"codeScanningDefaultSetup,omitempty"`
	// CodeScanningDefaultSetupOptions configures runner options for default code scanning setup.
	CodeScanningDefaultSetupOptions *CodeScanningDefaultSetupOptionsApplyConfiguration `json:"codeScanningDefaultSetupOptions,omitempty"`
	// CodeScanningDelegatedAlertDismissal enables users to dismiss code scanning alerts.
	// When enabled, users with appropriate permissions can dismiss alerts that don't require action.
	CodeScanningDelegatedAlertDismissal *string `json:"code_scanning_delegated_alert_dismissal,omitempty"`
	// CodeScanningOptions configures advanced code scanning options.
	CodeScanningOptions *CodeScanningOptionsApplyConfiguration `json:"code_scanning_options,omitempty"`
	// CodeSecurity is a meta-setting that enables multiple code security features.
	CodeSecurity *string `json:"codeSecurity,omitempty"`
	// SecretScanning enables or disables secret scanning.
	// Secret scanning detects secrets (like API keys and tokens) in your code.
	// Requires AdvancedSecurity to be enabled.
	// See: https://docs.github.com/en/code-security/secret-scanning/about-secret-scanning
	SecretScanning *string `json:"secretScanning,omitempty"`
	// SecretScanningPushProtection enables or disables push protection for secret scanning.
	// When enabled, pushes containing detected secrets are blocked.
	// Requires SecretScanning to be enabled.
	// See: https://docs.github.com/en/code-security/secret-scanning/push-protection-for-repositories-and-organizations
	SecretScanningPushProtection *string `json:"secretScanningPushProtection,omitempty"`
	// SecretScanningValidityChecks enables validation of detected secrets.
	// When enabled, GitHub validates whether detected secrets are still active.
	SecretScanningValidityChecks *string `json:"secretScanningValidityChecks,omitempty"`
	// SecretScanningNonProviderPatterns enables detection of non-provider secret patterns.
	// This expands secret scanning beyond known service provider patterns.
	SecretScanningNonProviderPatterns *string `json:"secretScanningNonProviderPatterns,omitempty"`
	// SecretScanningGenericSecrets enables detection of generic secrets.
	// This uses AI to detect potential secrets that don't match specific patterns.
	SecretScanningGenericSecrets *string `json:"secretScanningGenericSecrets,omitempty"`
	// SecretScanningDelegatedAlertDismissal enables users to dismiss secret scanning alerts.
	// When enabled, users with appropriate permissions can dismiss false-positive alerts.
	SecretScanningDelegatedAlertDismissal *string `json:"secretScanningDelegatedAlertDismissal,omitempty"`
	// SecretProtection is a meta-setting that enables multiple secret protection features.
	SecretProtection *string `json:"secretProtection,omitempty"`
	// PrivateVulnerabilityReporting enables or disables private vulnerability reporting.
	// When enabled, security researchers can privately report vulnerabilities.
	// See: https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing-information-about-vulnerabilities/privately-reporting-a-security-vulnerability
	PrivateVulnerabilityReporting *string `json:"privateVulnerabilityReporting,omitempty"`
	// Enforcement determines how strictly this configuration is applied.
	// - "enforced": Configuration settings are strictly enforced and cannot be overridden
	// - "unenforced": Configuration settings are recommended but can be overridden at the repository level
	Enforcement *string `json:"enforcement,omitempty"`
	// SecretScanningDelegatedBypass enables delegated bypass for secret scanning push protection.
	// When enabled, contributors can request bypass approval from designated reviewers.
	SecretScanningDelegatedBypass *string `json:"secretScanningDelegatedBypass,omitempty"`
	// SecretScanningDelegatedBypassOptions configures reviewers who can approve bypass requests.
	SecretScanningDelegatedBypassOptions *SecretScanningDelegatedBypassOptionsApplyConfiguration `json:"secretScanningDelegatedBypassOptions,omitempty"`
	// DefaultForNewRepos determines whether this configuration is automatically applied to new repositories.
	// - "all": Apply to all new repositories
	// - "private_and_internal": Apply only to new private and internal repositories
	// - "public": Apply only to new public repositories
	DefaultForNewRepos *string `json:"defaultForNewRepos,omitempty"`
}

// CodeSecurityConfigurationSpecApplyConfiguration constructs a declarative configuration of the CodeSecurityConfigurationSpec type for use with
// apply.
func CodeSecurityConfigurationSpec() *CodeSecurityConfigurationSpecApplyConfiguration {
	return &CodeSecurityConfigurationSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *CodeSecurityConfigurationSpecApplyConfiguration) WithName(value string) *CodeSecurityConfigurationSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *CodeSecurityConfigurationSpecApplyConfiguration) WithDescription(value string) *CodeSecurityConfigurationSpecApplyConfiguration {
	b.Description = &value
	return b
}

// WithAdvancedSecurity sets the AdvancedSecurity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AdvancedSecurity field is set to the value of the last call.
func (b *CodeSecurityConfigurationSpecApplyConfiguration) WithAdvancedSecurity(value string) *CodeSecurityConfigurationSpecApplyConfiguration {
	b.AdvancedSecurity = &value
	return b
}

// WithDependencyGraph sets the DependencyGraph field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DependencyGraph field is set to the value of the last call.
func (b *CodeSecurityConfigurationSpecApplyConfiguration) WithDependencyGraph(value string) *CodeSecurityConfigurationSpecApplyConfiguration {
	b.DependencyGraph = &value
	return b
}

// WithDependencyGraphAutosubmitAction sets the DependencyGraphAutosubmitAction field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DependencyGraphAutosubmitAction field is set to the value of the last call.
func (b *CodeSecurityConfigurationSpecApplyConfiguration) WithDependencyGraphAutosubmitAction(value string) *CodeSecurityConfigurationSpecApplyConfiguration {
	b.DependencyGraphAutosubmitAction = &value
	return b
}

// WithDependencyGraphAutosubmitActionOptions sets the DependencyGraphAutosubmitActionOptions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DependencyGraphAutosubmitActionOptions field is set to the value of the last call.
func (b *CodeSecurityConfigurationSpecApplyConfiguration) WithDependencyGraphAutosubmitActionOptions(value *DependencyGraphAutosubmitActionOptionsApplyConfiguration) *CodeSecurityConfigurationSpecApplyConfiguration {
	b.DependencyGraphAutosubmitActionOptions = value
	return b
}

// WithDependabotAlerts sets the DependabotAlerts field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DependabotAlerts field is set to the value of the last call.
func (b *CodeSecurityConfigurationSpecApplyConfiguration) WithDependabotAlerts(value string) *CodeSecurityConfigurationSpecApplyConfiguration {
	b.DependabotAlerts = &value
	return b
}

// WithDependabotSecurityUpdates sets the DependabotSecurityUpdates field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DependabotSecurityUpdates field is set to the value of the last call.
func (b *CodeSecurityConfigurationSpecApplyConfiguration) WithDependabotSecurityUpdates(value string) *CodeSecurityConfigurationSpecApplyConfiguration {
	b.DependabotSecurityUpdates = &value
	return b
}

// WithCodeScanningDefaultSetup sets the CodeScanningDefaultSetup field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CodeScanningDefaultSetup field is set to the value of the last call.
func (b *CodeSecurityConfigurationSpecApplyConfiguration) WithCodeScanningDefaultSetup(value string) *CodeSecurityConfigurationSpecApplyConfiguration {
	b.CodeScanningDefaultSetup = &value
	return b
}

// WithCodeScanningDefaultSetupOptions sets the CodeScanningDefaultSetupOptions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CodeScanningDefaultSetupOptions field is set to the value of the last call.
func (b *CodeSecurityConfigurationSpecApplyConfiguration) WithCodeScanningDefaultSetupOptions(value *CodeScanningDefaultSetupOptionsApplyConfiguration) *CodeSecurityConfigurationSpecApplyConfiguration {
	b.CodeScanningDefaultSetupOptions = value
	return b
}

// WithCodeScanningDelegatedAlertDismissal sets the CodeScanningDelegatedAlertDismissal field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CodeScanningDelegatedAlertDismissal field is set to the value of the last call.
func (b *CodeSecurityConfigurationSpecApplyConfiguration) WithCodeScanningDelegatedAlertDismissal(value string) *CodeSecurityConfigurationSpecApplyConfiguration {
	b.CodeScanningDelegatedAlertDismissal = &value
	return b
}

// WithCodeScanningOptions sets the CodeScanningOptions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CodeScanningOptions field is set to the value of the last call.
func (b *CodeSecurityConfigurationSpecApplyConfiguration) WithCodeScanningOptions(value *CodeScanningOptionsApplyConfiguration) *CodeSecurityConfigurationSpecApplyConfiguration {
	b.CodeScanningOptions = value
	return b
}

// WithCodeSecurity sets the CodeSecurity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CodeSecurity field is set to the value of the last call.
func (b *CodeSecurityConfigurationSpecApplyConfiguration) WithCodeSecurity(value string) *CodeSecurityConfigurationSpecApplyConfiguration {
	b.CodeSecurity = &value
	return b
}

// WithSecretScanning sets the SecretScanning field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretScanning field is set to the value of the last call.
func (b *CodeSecurityConfigurationSpecApplyConfiguration) WithSecretScanning(value string) *CodeSecurityConfigurationSpecApplyConfiguration {
	b.SecretScanning = &value
	return b
}

// WithSecretScanningPushProtection sets the SecretScanningPushProtection field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretScanningPushProtection field is set to the value of the last call.
func (b *CodeSecurityConfigurationSpecApplyConfiguration) WithSecretScanningPushProtection(value string) *CodeSecurityConfigurationSpecApplyConfiguration {
	b.SecretScanningPushProtection = &value
	return b
}

// WithSecretScanningValidityChecks sets the SecretScanningValidityChecks field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretScanningValidityChecks field is set to the value of the last call.
func (b *CodeSecurityConfigurationSpecApplyConfiguration) WithSecretScanningValidityChecks(value string) *CodeSecurityConfigurationSpecApplyConfiguration {
	b.SecretScanningValidityChecks = &value
	return b
}

// WithSecretScanningNonProviderPatterns sets the SecretScanningNonProviderPatterns field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretScanningNonProviderPatterns field is set to the value of the last call.
func (b *CodeSecurityConfigurationSpecApplyConfiguration) WithSecretScanningNonProviderPatterns(value string) *CodeSecurityConfigurationSpecApplyConfiguration {
	b.SecretScanningNonProviderPatterns = &value
	return b
}

// WithSecretScanningGenericSecrets sets the SecretScanningGenericSecrets field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretScanningGenericSecrets field is set to the value of the last call.
func (b *CodeSecurityConfigurationSpecApplyConfiguration) WithSecretScanningGenericSecrets(value string) *CodeSecurityConfigurationSpecApplyConfiguration {
	b.SecretScanningGenericSecrets = &value
	return b
}

// WithSecretScanningDelegatedAlertDismissal sets the SecretScanningDelegatedAlertDismissal field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretScanningDelegatedAlertDismissal field is set to the value of the last call.
func (b *CodeSecurityConfigurationSpecApplyConfiguration) WithSecretScanningDelegatedAlertDismissal(value string) *CodeSecurityConfigurationSpecApplyConfiguration {
	b.SecretScanningDelegatedAlertDismissal = &value
	return b
}

// WithSecretProtection sets the SecretProtection field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretProtection field is set to the value of the last call.
func (b *CodeSecurityConfigurationSpecApplyConfiguration) WithSecretProtection(value string) *CodeSecurityConfigurationSpecApplyConfiguration {
	b.SecretProtection = &value
	return b
}

// WithPrivateVulnerabilityReporting sets the PrivateVulnerabilityReporting field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PrivateVulnerabilityReporting field is set to the value of the last call.
func (b *CodeSecurityConfigurationSpecApplyConfiguration) WithPrivateVulnerabilityReporting(value string) *CodeSecurityConfigurationSpecApplyConfiguration {
	b.PrivateVulnerabilityReporting = &value
	return b
}

// WithEnforcement sets the Enforcement field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enforcement field is set to the value of the last call.
func (b *CodeSecurityConfigurationSpecApplyConfiguration) WithEnforcement(value string) *CodeSecurityConfigurationSpecApplyConfiguration {
	b.Enforcement = &value
	return b
}

// WithSecretScanningDelegatedBypass sets the SecretScanningDelegatedBypass field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretScanningDelegatedBypass field is set to the value of the last call.
func (b *CodeSecurityConfigurationSpecApplyConfiguration) WithSecretScanningDelegatedBypass(value string) *CodeSecurityConfigurationSpecApplyConfiguration {
	b.SecretScanningDelegatedBypass = &value
	return b
}

// WithSecretScanningDelegatedBypassOptions sets the SecretScanningDelegatedBypassOptions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretScanningDelegatedBypassOptions field is set to the value of the last call.
func (b *CodeSecurityConfigurationSpecApplyConfiguration) WithSecretScanningDelegatedBypassOptions(value *SecretScanningDelegatedBypassOptionsApplyConfiguration) *CodeSecurityConfigurationSpecApplyConfiguration {
	b.SecretScanningDelegatedBypassOptions = value
	return b
}

// WithDefaultForNewRepos sets the DefaultForNewRepos field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefaultForNewRepos field is set to the value of the last call.
func (b *CodeSecurityConfigurationSpecApplyConfiguration) WithDefaultForNewRepos(value string) *CodeSecurityConfigurationSpecApplyConfiguration {
	b.DefaultForNewRepos = &value
	return b
}
