/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// CodeScanningDefaultSetupOptionsApplyConfiguration represents a declarative configuration of the CodeScanningDefaultSetupOptions type for use
// with apply.
//
// CodeScanningDefaultSetupOptions configures the default setup options for code scanning.
// See: https://docs.github.com/en/rest/code-security/configurations
type CodeScanningDefaultSetupOptionsApplyConfiguration struct {
	// RunnerType specifies which type of runners to use for code scanning.
	// - "standard": Use GitHub-hosted standard runners
	// - "labeled": Use self-hosted runners with specific labels (requires RunnerLabel)
	// - "not_set": No runner type is configured
	RunnerType *string `json:"runnerType,omitempty"`
	// RunnerLabel specifies the label of self-hosted runners to use.
	// This field is required when RunnerType is "labeled" and ignored otherwise.
	RunnerLabel *string `json:"runnerLabel,omitempty"`
}

// CodeScanningDefaultSetupOptionsApplyConfiguration constructs a declarative configuration of the CodeScanningDefaultSetupOptions type for use with
// apply.
func CodeScanningDefaultSetupOptions() *CodeScanningDefaultSetupOptionsApplyConfiguration {
	return &CodeScanningDefaultSetupOptionsApplyConfiguration{}
}

// WithRunnerType sets the RunnerType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RunnerType field is set to the value of the last call.
func (b *CodeScanningDefaultSetupOptionsApplyConfiguration) WithRunnerType(value string) *CodeScanningDefaultSetupOptionsApplyConfiguration {
	b.RunnerType = &value
	return b
}

// WithRunnerLabel sets the RunnerLabel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RunnerLabel field is set to the value of the last call.
func (b *CodeScanningDefaultSetupOptionsApplyConfiguration) WithRunnerLabel(value string) *CodeScanningDefaultSetupOptionsApplyConfiguration {
	b.RunnerLabel = &value
	return b
}
