/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// CopilotCodeReviewRuleApplyConfiguration represents a declarative configuration of the CopilotCodeReviewRule type for use
// with apply.
//
// CopilotCodeReviewRule defines the automatic pull request review by GitHub Copilot.
type CopilotCodeReviewRuleApplyConfiguration struct {
	// ReviewOnPush configures Copilot to automatically review each new push to the pull request.
	ReviewOnPush *bool `json:"reviewOnPush,omitempty"`
	// ReviewDraftPullRequests configures Copilot to automatically review draft pull requests before they are marked as ready for review.
	ReviewDraftPullRequests *bool `json:"reviewDraftPullRequests,omitempty"`
}

// CopilotCodeReviewRuleApplyConfiguration constructs a declarative configuration of the CopilotCodeReviewRule type for use with
// apply.
func CopilotCodeReviewRule() *CopilotCodeReviewRuleApplyConfiguration {
	return &CopilotCodeReviewRuleApplyConfiguration{}
}

// WithReviewOnPush sets the ReviewOnPush field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReviewOnPush field is set to the value of the last call.
func (b *CopilotCodeReviewRuleApplyConfiguration) WithReviewOnPush(value bool) *CopilotCodeReviewRuleApplyConfiguration {
	b.ReviewOnPush = &value
	return b
}

// WithReviewDraftPullRequests sets the ReviewDraftPullRequests field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReviewDraftPullRequests field is set to the value of the last call.
func (b *CopilotCodeReviewRuleApplyConfiguration) WithReviewDraftPullRequests(value bool) *CopilotCodeReviewRuleApplyConfiguration {
	b.ReviewDraftPullRequests = &value
	return b
}
