/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// CustomPropertyValueApplyConfiguration represents a declarative configuration of the CustomPropertyValue type for use
// with apply.
//
// CustomPropertyValue defines a custom property value for a repository.
// Custom properties are defined at the organization level and applied to repositories.
// If both Value and Values are empty, the value for the property is considered nil (removes the property).
// For custom properties of value type "multi_select", use Values to specify multiple selections.
// For all other value types ("string", "single_select", "true_false"), use Value.
// See: https://docs.github.com/en/rest/repos/custom-properties
type CustomPropertyValueApplyConfiguration struct {
	// Value is the property value for types "string", "single_select", and "true_false".
	// For "true_false", must be "true" or "false".
	// For "single_select", must be one of the allowed values defined in the organization's custom property.
	Value *string `json:"value,omitempty"`
	// Values is the list of selected values for "multi_select" type properties.
	// Each value must be one of the allowed values defined in the organization's custom property.
	Values []string `json:"values,omitempty"`
	// PropertyName is the name of the custom property as defined in the organization.
	PropertyName *string `json:"propertyName,omitempty"`
}

// CustomPropertyValueApplyConfiguration constructs a declarative configuration of the CustomPropertyValue type for use with
// apply.
func CustomPropertyValue() *CustomPropertyValueApplyConfiguration {
	return &CustomPropertyValueApplyConfiguration{}
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *CustomPropertyValueApplyConfiguration) WithValue(value string) *CustomPropertyValueApplyConfiguration {
	b.Value = &value
	return b
}

// WithValues adds the given value to the Values field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Values field.
func (b *CustomPropertyValueApplyConfiguration) WithValues(values ...string) *CustomPropertyValueApplyConfiguration {
	for i := range values {
		b.Values = append(b.Values, values[i])
	}
	return b
}

// WithPropertyName sets the PropertyName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PropertyName field is set to the value of the last call.
func (b *CustomPropertyValueApplyConfiguration) WithPropertyName(value string) *CustomPropertyValueApplyConfiguration {
	b.PropertyName = &value
	return b
}
