/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// DependencyGraphAutosubmitActionOptionsApplyConfiguration represents a declarative configuration of the DependencyGraphAutosubmitActionOptions type for use
// with apply.
//
// DependencyGraphAutosubmitActionOptions configures options for automatic dependency submission actions.
// See: https://docs.github.com/en/rest/code-security/configurations
type DependencyGraphAutosubmitActionOptionsApplyConfiguration struct {
	// LabeledRunners indicates whether to use labeled runners for dependency submission actions.
	// If true, actions will run on runners with specific labels instead of GitHub-hosted runners.
	LabeledRunners *bool `json:"labeledRunners,omitempty"`
}

// DependencyGraphAutosubmitActionOptionsApplyConfiguration constructs a declarative configuration of the DependencyGraphAutosubmitActionOptions type for use with
// apply.
func DependencyGraphAutosubmitActionOptions() *DependencyGraphAutosubmitActionOptionsApplyConfiguration {
	return &DependencyGraphAutosubmitActionOptionsApplyConfiguration{}
}

// WithLabeledRunners sets the LabeledRunners field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LabeledRunners field is set to the value of the last call.
func (b *DependencyGraphAutosubmitActionOptionsApplyConfiguration) WithLabeledRunners(value bool) *DependencyGraphAutosubmitActionOptionsApplyConfiguration {
	b.LabeledRunners = &value
	return b
}
