/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// DeployKeyApplyConfiguration represents a declarative configuration of the DeployKey type for use
// with apply.
//
// DeployKey defines an SSH key for read-only or read-write access to a single repository.
// Deploy keys are commonly used for CI/CD systems and automated deployments.
// See: https://docs.github.com/en/rest/deploy-keys/deploy-keys
type DeployKeyApplyConfiguration struct {
	// Key is the public SSH key in OpenSSH format.
	// Supported key types are RSA and Ed25519.
	// Example: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC..." or "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5..."
	Key *string `json:"key,omitempty"`
	// Title is a descriptive name for the deploy key shown in the repository settings.
	// Examples: "CI/CD Key", "Read-Only Deploy Key", "Production Server"
	Title *string `json:"title,omitempty"`
	// ReadOnly determines the access level for this deploy key.
	// - true: Key can only read from the repository (cannot push)
	// - false: Key can read and write to the repository (can push commits)
	ReadOnly *bool `json:"readOnly,omitempty"`
}

// DeployKeyApplyConfiguration constructs a declarative configuration of the DeployKey type for use with
// apply.
func DeployKey() *DeployKeyApplyConfiguration {
	return &DeployKeyApplyConfiguration{}
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *DeployKeyApplyConfiguration) WithKey(value string) *DeployKeyApplyConfiguration {
	b.Key = &value
	return b
}

// WithTitle sets the Title field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Title field is set to the value of the last call.
func (b *DeployKeyApplyConfiguration) WithTitle(value string) *DeployKeyApplyConfiguration {
	b.Title = &value
	return b
}

// WithReadOnly sets the ReadOnly field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadOnly field is set to the value of the last call.
func (b *DeployKeyApplyConfiguration) WithReadOnly(value bool) *DeployKeyApplyConfiguration {
	b.ReadOnly = &value
	return b
}
