/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// GitHubAppConfigApplyConfiguration represents a declarative configuration of the GitHubAppConfig type for use
// with apply.
//
// GitHubAppConfig defines the GitHub App configuration for an organization, referencing the
// Kubernetes Secret that holds the app credentials by name. The secret must reside in the
// namespace configured via the APP_CREDENTIALS_SECRET_NAMESPACE environment variable.
type GitHubAppConfigApplyConfiguration struct {
	// InstallationId is the numeric ID of the GitHub App installation for this organization.
	// You can find this ID in your GitHub App's installation settings or via the GitHub API.
	InstallationId *int64 `json:"installationId,omitempty"`
	// CredentialsSecretName is the name of the Kubernetes Secret containing the GitHub App credentials.
	// The secret must contain the keys `app-id` and `private-key` and must reside in the namespace
	// configured via the APP_CREDENTIALS_SECRET_NAMESPACE environment variable.
	CredentialsSecretName *string `json:"credentialsSecretName,omitempty"`
}

// GitHubAppConfigApplyConfiguration constructs a declarative configuration of the GitHubAppConfig type for use with
// apply.
func GitHubAppConfig() *GitHubAppConfigApplyConfiguration {
	return &GitHubAppConfigApplyConfiguration{}
}

// WithInstallationId sets the InstallationId field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InstallationId field is set to the value of the last call.
func (b *GitHubAppConfigApplyConfiguration) WithInstallationId(value int64) *GitHubAppConfigApplyConfiguration {
	b.InstallationId = &value
	return b
}

// WithCredentialsSecretName sets the CredentialsSecretName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CredentialsSecretName field is set to the value of the last call.
func (b *GitHubAppConfigApplyConfiguration) WithCredentialsSecretName(value string) *GitHubAppConfigApplyConfiguration {
	b.CredentialsSecretName = &value
	return b
}
