/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// IpAllowListSettingsApplyConfiguration represents a declarative configuration of the IpAllowListSettings type for use
// with apply.
//
// IpAllowListSettings configures the organization-level IP allow list.
//
// Only the organization-owned portion of the effective allow list is managed here. Entries
// inherited from the enterprise account and entries automatically managed by installed GitHub
// Apps (described as "Managed by the <name> GitHub App") are read-only and are never modified,
// deleted, or reported as drift by the reconciler.
//
// IP allow lists are only available on GitHub Enterprise Cloud organizations. If the enterprise
// delegates its allow list to an identity provider (Enterprise Managed Users with Entra ID and
// OIDC), GitHub deactivates the organization IP allow list GraphQL APIs; in that case the
// reconciler surfaces the condition but does not treat it as a hard failure.
// See: https://docs.github.com/en/organizations/keeping-your-organization-secure/managing-security-settings-for-your-organization/managing-allowed-ip-addresses-for-your-organization
type IpAllowListSettingsApplyConfiguration struct {
	// Enabled determines whether the IP allow list is enforced for the organization.
	// Entries are always reconciled first, so that enabling enforcement never locks out the
	// currently configured (active) addresses.
	Enabled *bool `json:"enabled,omitempty"`
	// EnabledForInstalledApps determines whether IP addresses configured for installed GitHub Apps
	// are automatically added to the allow list. This takes effect independently of Enabled.
	// The resulting App-managed entries are read-only and are not managed via the Entries field.
	EnabledForInstalledApps *bool `json:"enabledForInstalledApps,omitempty"`
	// Entries is the desired set of organization-owned IP allow list entries, keyed by their
	// AllowListValue. Entries present in GitHub but not listed here are deleted (except read-only
	// enterprise-inherited and App-managed entries, which are always preserved). Omitting this
	// field (nil) manages only the enabled settings and leaves organization-owned entries untouched;
	// provide an empty list to explicitly remove all organization-owned entries.
	Entries []IpAllowListEntryApplyConfiguration `json:"entries,omitempty"`
}

// IpAllowListSettingsApplyConfiguration constructs a declarative configuration of the IpAllowListSettings type for use with
// apply.
func IpAllowListSettings() *IpAllowListSettingsApplyConfiguration {
	return &IpAllowListSettingsApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *IpAllowListSettingsApplyConfiguration) WithEnabled(value bool) *IpAllowListSettingsApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithEnabledForInstalledApps sets the EnabledForInstalledApps field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EnabledForInstalledApps field is set to the value of the last call.
func (b *IpAllowListSettingsApplyConfiguration) WithEnabledForInstalledApps(value bool) *IpAllowListSettingsApplyConfiguration {
	b.EnabledForInstalledApps = &value
	return b
}

// WithEntries adds the given value to the Entries field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Entries field.
func (b *IpAllowListSettingsApplyConfiguration) WithEntries(values ...*IpAllowListEntryApplyConfiguration) *IpAllowListSettingsApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithEntries")
		}
		b.Entries = append(b.Entries, *values[i])
	}
	return b
}
