/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// IpAllowListEntryApplyConfiguration represents a declarative configuration of the IpAllowListEntry type for use
// with apply.
//
// IpAllowListEntry defines a single entry in an organization's IP allow list.
// Each entry allows access from a single IP address or a range of addresses in CIDR notation.
// See: https://docs.github.com/en/organizations/keeping-your-organization-secure/managing-security-settings-for-your-organization/managing-allowed-ip-addresses-for-your-organization
type IpAllowListEntryApplyConfiguration struct {
	// AllowListValue is an IP address or a range of addresses in CIDR notation (e.g. "192.0.2.1" or "192.0.2.0/24").
	// A range covering the entire address space (such as "0.0.0.0/0" or "::/0") is rejected by GitHub;
	// to allow access from anywhere, disable the allow list via Enabled=false instead.
	AllowListValue *string `json:"allowListValue,omitempty"`
	// Name is an optional human-readable description of the entry, shown in the GitHub UI.
	Name *string `json:"name,omitempty"`
	// IsActive determines whether this entry is enforced while the IP allow list is enabled.
	// Inactive entries remain configured but are ignored until activated.
	IsActive *bool `json:"isActive,omitempty"`
}

// IpAllowListEntryApplyConfiguration constructs a declarative configuration of the IpAllowListEntry type for use with
// apply.
func IpAllowListEntry() *IpAllowListEntryApplyConfiguration {
	return &IpAllowListEntryApplyConfiguration{}
}

// WithAllowListValue sets the AllowListValue field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllowListValue field is set to the value of the last call.
func (b *IpAllowListEntryApplyConfiguration) WithAllowListValue(value string) *IpAllowListEntryApplyConfiguration {
	b.AllowListValue = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *IpAllowListEntryApplyConfiguration) WithName(value string) *IpAllowListEntryApplyConfiguration {
	b.Name = &value
	return b
}

// WithIsActive sets the IsActive field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IsActive field is set to the value of the last call.
func (b *IpAllowListEntryApplyConfiguration) WithIsActive(value bool) *IpAllowListEntryApplyConfiguration {
	b.IsActive = &value
	return b
}
