/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// MergeStrategyApplyConfiguration represents a declarative configuration of the MergeStrategy type for use
// with apply.
//
// MergeStrategy defines an allowed merge strategy for pull requests.
// See: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/about-merge-methods-on-github
type MergeStrategyApplyConfiguration struct {
	// Type specifies the merge strategy type.
	// - "merge": Create a merge commit (preserves all commits from the feature branch)
	// - "rebase": Rebase and merge (rebases commits onto base branch)
	// - "squash": Squash and merge (combines all commits into a single commit)
	Type *string `json:"type,omitempty"`
}

// MergeStrategyApplyConfiguration constructs a declarative configuration of the MergeStrategy type for use with
// apply.
func MergeStrategy() *MergeStrategyApplyConfiguration {
	return &MergeStrategyApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *MergeStrategyApplyConfiguration) WithType(value string) *MergeStrategyApplyConfiguration {
	b.Type = &value
	return b
}
