/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// OrganizationSpecApplyConfiguration represents a declarative configuration of the OrganizationSpec type for use
// with apply.
//
// OrganizationSpec defines the desired state of Organization.
// An Organization represents a GitHub organization and its configuration including custom properties,
// rulesets, code security settings, and Actions permissions.
// See: https://docs.github.com/en/rest/orgs/orgs
type OrganizationSpecApplyConfiguration struct {
	// Login is the GitHub organization login (the unique, immutable identifier on GitHub).
	// This field is optional for backwards compatibility. If not specified, the Name field
	// will be used as both login and display name.
	// It is recommended to explicitly set this field to clearly separate login from display name.
	Login *string `json:"login,omitempty"`
	// Name is the organization's display name shown on the GitHub profile.
	// If Login is not specified, this field will also be used as the organization login
	// for backwards compatibility.
	// At least one of Login or Name must be specified.
	Name *string `json:"name,omitempty"`
	// GitHubAppInstallationId is the numeric ID of the GitHub App installation for this organization.
	// This field is deprecated. Use GitHubAppConfig instead, which also allows specifying which
	// credential secret to use. When only this field is set, the operator falls back to the
	// secret name configured via --app-credentials-secret-name.
	// At least one of GitHubAppInstallationId or GitHubAppConfig must be set.
	// If both are set, GitHubAppConfig takes precedence.
	GitHubAppInstallationId *int64 `json:"githubAppInstallationId,omitempty"`
	// GitHubAppConfig specifies the GitHub App installation and credentials secret to use for
	// authenticating API requests on behalf of this organization.
	// At least one of GitHubAppConfig or GitHubAppInstallationId must be set.
	// If both are set, GitHubAppConfig takes precedence.
	GitHubAppConfig *GitHubAppConfigApplyConfiguration `json:"githubAppConfig,omitempty"`
	// CustomProperties defines custom metadata properties that can be assigned to repositories in the organization.
	// These properties allow you to categorize and add structured metadata to your repositories.
	// See: https://docs.github.com/en/rest/orgs/custom-properties
	CustomProperties []OrgCustomPropertyApplyConfiguration `json:"customProperties,omitempty"`
	// ActionsSettings configures GitHub Actions permissions and behavior for the organization.
	// This includes which repositories can use Actions, which actions are allowed, and runner group configurations.
	// See: https://docs.github.com/en/rest/actions/permissions
	ActionsSettings *ActionsSettingsApplyConfiguration `json:"actionsSettings,omitempty"`
	// CodeSecurityConfigurations lists code security configurations to create and optionally attach to repositories.
	// Each configuration defines security features like dependency scanning, secret scanning, and code scanning.
	// See: https://docs.github.com/en/rest/code-security/configurations
	CodeSecurityConfigurations []AttachableCodeSecurityConfigurationRefApplyConfiguration `json:"codeSecurityConfigurations,omitempty"`
	// RulesetPresetList references RulesetPreset CRDs that define repository rulesets for this organization.
	// Rulesets enforce policies like branch protection, required reviews, and status checks.
	// See: https://docs.github.com/en/rest/orgs/rules
	RulesetPresetList []v1.LocalObjectReference `json:"rulesetPresets,omitempty"`
	// Description is a human-readable description of the organization.
	// This appears on the organization's GitHub profile page.
	Description *string `json:"description,omitempty"`
	// Location is the organization's location (e.g., "Munich, Germany").
	// This appears on the organization's GitHub profile page.
	Location *string `json:"location,omitempty"`
	// Website is the organization's website URL.
	// This appears on the organization's GitHub profile page as a clickable link.
	Website *string `json:"website,omitempty"`
	// Plan indicates the GitHub plan tier for this organization (enterprise, team, or free).
	// Determines whether Enterprise-only features (e.g., custom properties, runner groups) are reconciled or skipped.
	Plan *string `json:"plan,omitempty"`
}

// OrganizationSpecApplyConfiguration constructs a declarative configuration of the OrganizationSpec type for use with
// apply.
func OrganizationSpec() *OrganizationSpecApplyConfiguration {
	return &OrganizationSpecApplyConfiguration{}
}

// WithLogin sets the Login field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Login field is set to the value of the last call.
func (b *OrganizationSpecApplyConfiguration) WithLogin(value string) *OrganizationSpecApplyConfiguration {
	b.Login = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *OrganizationSpecApplyConfiguration) WithName(value string) *OrganizationSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithGitHubAppInstallationId sets the GitHubAppInstallationId field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GitHubAppInstallationId field is set to the value of the last call.
func (b *OrganizationSpecApplyConfiguration) WithGitHubAppInstallationId(value int64) *OrganizationSpecApplyConfiguration {
	b.GitHubAppInstallationId = &value
	return b
}

// WithGitHubAppConfig sets the GitHubAppConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GitHubAppConfig field is set to the value of the last call.
func (b *OrganizationSpecApplyConfiguration) WithGitHubAppConfig(value *GitHubAppConfigApplyConfiguration) *OrganizationSpecApplyConfiguration {
	b.GitHubAppConfig = value
	return b
}

// WithCustomProperties adds the given value to the CustomProperties field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the CustomProperties field.
func (b *OrganizationSpecApplyConfiguration) WithCustomProperties(values ...*OrgCustomPropertyApplyConfiguration) *OrganizationSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithCustomProperties")
		}
		b.CustomProperties = append(b.CustomProperties, *values[i])
	}
	return b
}

// WithActionsSettings sets the ActionsSettings field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ActionsSettings field is set to the value of the last call.
func (b *OrganizationSpecApplyConfiguration) WithActionsSettings(value *ActionsSettingsApplyConfiguration) *OrganizationSpecApplyConfiguration {
	b.ActionsSettings = value
	return b
}

// WithCodeSecurityConfigurations adds the given value to the CodeSecurityConfigurations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the CodeSecurityConfigurations field.
func (b *OrganizationSpecApplyConfiguration) WithCodeSecurityConfigurations(values ...*AttachableCodeSecurityConfigurationRefApplyConfiguration) *OrganizationSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithCodeSecurityConfigurations")
		}
		b.CodeSecurityConfigurations = append(b.CodeSecurityConfigurations, *values[i])
	}
	return b
}

// WithRulesetPresetList adds the given value to the RulesetPresetList field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the RulesetPresetList field.
func (b *OrganizationSpecApplyConfiguration) WithRulesetPresetList(values ...v1.LocalObjectReference) *OrganizationSpecApplyConfiguration {
	for i := range values {
		b.RulesetPresetList = append(b.RulesetPresetList, values[i])
	}
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *OrganizationSpecApplyConfiguration) WithDescription(value string) *OrganizationSpecApplyConfiguration {
	b.Description = &value
	return b
}

// WithLocation sets the Location field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Location field is set to the value of the last call.
func (b *OrganizationSpecApplyConfiguration) WithLocation(value string) *OrganizationSpecApplyConfiguration {
	b.Location = &value
	return b
}

// WithWebsite sets the Website field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Website field is set to the value of the last call.
func (b *OrganizationSpecApplyConfiguration) WithWebsite(value string) *OrganizationSpecApplyConfiguration {
	b.Website = &value
	return b
}

// WithPlan sets the Plan field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Plan field is set to the value of the last call.
func (b *OrganizationSpecApplyConfiguration) WithPlan(value string) *OrganizationSpecApplyConfiguration {
	b.Plan = &value
	return b
}
