/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// OrganizationSpecApplyConfiguration represents a declarative configuration of the OrganizationSpec type for use
// with apply.
//
// OrganizationSpec defines the desired state of Organization.
// An Organization represents a GitHub organization and its configuration including custom properties,
// rulesets, code security settings, and Actions permissions.
// See: https://docs.github.com/en/rest/orgs/orgs
type OrganizationSpecApplyConfiguration struct {
	// Name is the GitHub organization name (also known as the organization login).
	// This is the unique identifier for the organization on GitHub.
	Name *string `json:"name,omitempty"`
	// GitHubAppInstallationId is the numeric ID of the GitHub App installation for this organization.
	// This is used to authenticate API requests to GitHub. You can find this ID in your GitHub App's
	// installation settings or via the GitHub API.
	GitHubAppInstallationId *int64 `json:"githubAppInstallationId,omitempty"`
	// CustomProperties defines custom metadata properties that can be assigned to repositories in the organization.
	// These properties allow you to categorize and add structured metadata to your repositories.
	// See: https://docs.github.com/en/rest/orgs/custom-properties
	CustomProperties []OrgCustomPropertyApplyConfiguration `json:"customProperties,omitempty"`
	// ActionsSettings configures GitHub Actions permissions and behavior for the organization.
	// This includes which repositories can use Actions, which actions are allowed, and runner group configurations.
	// See: https://docs.github.com/en/rest/actions/permissions
	ActionsSettings *ActionsSettingsApplyConfiguration `json:"actionsSettings,omitempty"`
	// CodeSecurityConfigurations lists code security configurations to create and optionally attach to repositories.
	// Each configuration defines security features like dependency scanning, secret scanning, and code scanning.
	// See: https://docs.github.com/en/rest/code-security/configurations
	CodeSecurityConfigurations []AttachableCodeSecurityConfigurationRefApplyConfiguration `json:"codeSecurityConfigurations,omitempty"`
	// RulesetPresetList references RulesetPreset CRDs that define repository rulesets for this organization.
	// Rulesets enforce policies like branch protection, required reviews, and status checks.
	// See: https://docs.github.com/en/rest/orgs/rules
	RulesetPresetList []v1.LocalObjectReference `json:"rulesetPresets,omitempty"`
	// Description is a human-readable description of the organization.
	// This appears on the organization's GitHub profile page.
	Description *string `json:"description,omitempty"`
}

// OrganizationSpecApplyConfiguration constructs a declarative configuration of the OrganizationSpec type for use with
// apply.
func OrganizationSpec() *OrganizationSpecApplyConfiguration {
	return &OrganizationSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *OrganizationSpecApplyConfiguration) WithName(value string) *OrganizationSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithGitHubAppInstallationId sets the GitHubAppInstallationId field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GitHubAppInstallationId field is set to the value of the last call.
func (b *OrganizationSpecApplyConfiguration) WithGitHubAppInstallationId(value int64) *OrganizationSpecApplyConfiguration {
	b.GitHubAppInstallationId = &value
	return b
}

// WithCustomProperties adds the given value to the CustomProperties field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the CustomProperties field.
func (b *OrganizationSpecApplyConfiguration) WithCustomProperties(values ...*OrgCustomPropertyApplyConfiguration) *OrganizationSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithCustomProperties")
		}
		b.CustomProperties = append(b.CustomProperties, *values[i])
	}
	return b
}

// WithActionsSettings sets the ActionsSettings field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ActionsSettings field is set to the value of the last call.
func (b *OrganizationSpecApplyConfiguration) WithActionsSettings(value *ActionsSettingsApplyConfiguration) *OrganizationSpecApplyConfiguration {
	b.ActionsSettings = value
	return b
}

// WithCodeSecurityConfigurations adds the given value to the CodeSecurityConfigurations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the CodeSecurityConfigurations field.
func (b *OrganizationSpecApplyConfiguration) WithCodeSecurityConfigurations(values ...*AttachableCodeSecurityConfigurationRefApplyConfiguration) *OrganizationSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithCodeSecurityConfigurations")
		}
		b.CodeSecurityConfigurations = append(b.CodeSecurityConfigurations, *values[i])
	}
	return b
}

// WithRulesetPresetList adds the given value to the RulesetPresetList field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the RulesetPresetList field.
func (b *OrganizationSpecApplyConfiguration) WithRulesetPresetList(values ...v1.LocalObjectReference) *OrganizationSpecApplyConfiguration {
	for i := range values {
		b.RulesetPresetList = append(b.RulesetPresetList, values[i])
	}
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *OrganizationSpecApplyConfiguration) WithDescription(value string) *OrganizationSpecApplyConfiguration {
	b.Description = &value
	return b
}
