/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// OrganizationMemberPrivilegesApplyConfiguration represents a declarative configuration of the OrganizationMemberPrivileges type for use
// with apply.
//
// MemberPrivileges configures the privileges and default permissions for members of this organization.
// Configurability may be restricted by Enterprise policies.
// The individual settings do not have a default by design: not setting a value results in keeping the current
// setting in GitHub. This is necessary if the setting is managed by Enterprise policies or manual configuration
// is preferred.
type OrganizationMemberPrivilegesApplyConfiguration struct {
	// DefaultRepositoryPermission defines the default permission level members have for organization repositories.
	// This setting can not be set if it is fixed at Enterprise level.
	DefaultRepositoryPermission *string `json:"defaultRepositoryPermission,omitempty"`
	// MembersCanCreatePublicRepositories defines whether organization members can create public repositories,
	// which are visible to anyone.
	// This setting is not supported for Organizations in Enterprises with Managed Users (EMU).
	MembersCanCreatePublicRepositories *bool `json:"membersCanCreatePublicRepositories,omitempty"`
	// MembersCanCreatePrivateRepositories defines whether organization members can create private repositories,
	// which are visible to organization members with permission.
	MembersCanCreatePrivateRepositories *bool `json:"membersCanCreatePrivateRepositories,omitempty"`
	// MembersCanCreateInternalRepositories defines whether organization members can create internal repositories,
	// which are visible to all enterprise members. You can only allow members to create internal repositories if
	// your organization is associated with an enterprise account using GitHub Enterprise Cloud or
	// GitHub Enterprise Server 2.20+.
	MembersCanCreateInternalRepositories *bool `json:"membersCanCreateInternalRepositories,omitempty"`
	// MembersCanCreatePages defines whether organization members can create GitHub Pages sites.
	// Existing published sites will not be impacted.
	MembersCanCreatePages *bool `json:"membersCanCreatePages,omitempty"`
	// MembersCanCreatePublicPages defines whether organization members can create public GitHub Pages sites.
	// Existing published sites will not be impacted.
	// This setting is not supported for Organizations in Enterprises with Managed Users (EMU).
	MembersCanCreatePublicPages *bool `json:"membersCanCreatePublicPages,omitempty"`
	// MembersCanCreatePrivatePages defines whether organization members can create private GitHub Pages sites.
	// Existing published sites will not be impacted.
	MembersCanCreatePrivatePages *bool `json:"membersCanCreatePrivatePages,omitempty"`
	// MembersCanForkPrivateRepositories defines whether organization members can fork private organization repositories.
	MembersCanForkPrivateRepositories *bool `json:"membersCanForkPrivateRepositories,omitempty"`
}

// OrganizationMemberPrivilegesApplyConfiguration constructs a declarative configuration of the OrganizationMemberPrivileges type for use with
// apply.
func OrganizationMemberPrivileges() *OrganizationMemberPrivilegesApplyConfiguration {
	return &OrganizationMemberPrivilegesApplyConfiguration{}
}

// WithDefaultRepositoryPermission sets the DefaultRepositoryPermission field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefaultRepositoryPermission field is set to the value of the last call.
func (b *OrganizationMemberPrivilegesApplyConfiguration) WithDefaultRepositoryPermission(value string) *OrganizationMemberPrivilegesApplyConfiguration {
	b.DefaultRepositoryPermission = &value
	return b
}

// WithMembersCanCreatePublicRepositories sets the MembersCanCreatePublicRepositories field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MembersCanCreatePublicRepositories field is set to the value of the last call.
func (b *OrganizationMemberPrivilegesApplyConfiguration) WithMembersCanCreatePublicRepositories(value bool) *OrganizationMemberPrivilegesApplyConfiguration {
	b.MembersCanCreatePublicRepositories = &value
	return b
}

// WithMembersCanCreatePrivateRepositories sets the MembersCanCreatePrivateRepositories field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MembersCanCreatePrivateRepositories field is set to the value of the last call.
func (b *OrganizationMemberPrivilegesApplyConfiguration) WithMembersCanCreatePrivateRepositories(value bool) *OrganizationMemberPrivilegesApplyConfiguration {
	b.MembersCanCreatePrivateRepositories = &value
	return b
}

// WithMembersCanCreateInternalRepositories sets the MembersCanCreateInternalRepositories field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MembersCanCreateInternalRepositories field is set to the value of the last call.
func (b *OrganizationMemberPrivilegesApplyConfiguration) WithMembersCanCreateInternalRepositories(value bool) *OrganizationMemberPrivilegesApplyConfiguration {
	b.MembersCanCreateInternalRepositories = &value
	return b
}

// WithMembersCanCreatePages sets the MembersCanCreatePages field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MembersCanCreatePages field is set to the value of the last call.
func (b *OrganizationMemberPrivilegesApplyConfiguration) WithMembersCanCreatePages(value bool) *OrganizationMemberPrivilegesApplyConfiguration {
	b.MembersCanCreatePages = &value
	return b
}

// WithMembersCanCreatePublicPages sets the MembersCanCreatePublicPages field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MembersCanCreatePublicPages field is set to the value of the last call.
func (b *OrganizationMemberPrivilegesApplyConfiguration) WithMembersCanCreatePublicPages(value bool) *OrganizationMemberPrivilegesApplyConfiguration {
	b.MembersCanCreatePublicPages = &value
	return b
}

// WithMembersCanCreatePrivatePages sets the MembersCanCreatePrivatePages field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MembersCanCreatePrivatePages field is set to the value of the last call.
func (b *OrganizationMemberPrivilegesApplyConfiguration) WithMembersCanCreatePrivatePages(value bool) *OrganizationMemberPrivilegesApplyConfiguration {
	b.MembersCanCreatePrivatePages = &value
	return b
}

// WithMembersCanForkPrivateRepositories sets the MembersCanForkPrivateRepositories field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MembersCanForkPrivateRepositories field is set to the value of the last call.
func (b *OrganizationMemberPrivilegesApplyConfiguration) WithMembersCanForkPrivateRepositories(value bool) *OrganizationMemberPrivilegesApplyConfiguration {
	b.MembersCanForkPrivateRepositories = &value
	return b
}
