/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// OrgCustomPropertyDefaultValueApplyConfiguration represents a declarative configuration of the OrgCustomPropertyDefaultValue type for use
// with apply.
//
// OrgCustomPropertyDefaultValue defines the default value for an organization custom property.
// Either Value (for single values) or Values (for multi-select) must be set, but not both.
type OrgCustomPropertyDefaultValueApplyConfiguration struct {
	// Value is the default value for properties with ValueType "string", "single_select", or "true_false".
	// For "true_false", it must be either "true" or "false".
	// For "single_select", it must be one of the AllowedValues defined in the property.
	Value *string `json:"value,omitempty"`
	// Values is the default value for properties with ValueType "multi_select".
	// Each value must be one of the AllowedValues defined in the property.
	Values []string `json:"values,omitempty"`
}

// OrgCustomPropertyDefaultValueApplyConfiguration constructs a declarative configuration of the OrgCustomPropertyDefaultValue type for use with
// apply.
func OrgCustomPropertyDefaultValue() *OrgCustomPropertyDefaultValueApplyConfiguration {
	return &OrgCustomPropertyDefaultValueApplyConfiguration{}
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *OrgCustomPropertyDefaultValueApplyConfiguration) WithValue(value string) *OrgCustomPropertyDefaultValueApplyConfiguration {
	b.Value = &value
	return b
}

// WithValues adds the given value to the Values field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Values field.
func (b *OrgCustomPropertyDefaultValueApplyConfiguration) WithValues(values ...string) *OrgCustomPropertyDefaultValueApplyConfiguration {
	for i := range values {
		b.Values = append(b.Values, values[i])
	}
	return b
}
