/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// OrgCustomPropertyApplyConfiguration represents a declarative configuration of the OrgCustomProperty type for use
// with apply.
//
// OrgCustomProperty defines a custom property for an organization.
// Custom properties allow you to add metadata to repositories in your organization.
// This is a kubebuilder annotated copy of github.CustomProperty without the source_type (as it is fixed to "organization").
// For the logic to work the json field names must match the ones in github.CustomProperty.
// See: https://docs.github.com/en/rest/orgs/custom-properties
type OrgCustomPropertyApplyConfiguration struct {
	// PropertyName is the unique name of the custom property.
	// Must start with a letter, number, _, $, or # and can only contain letters, numbers, _, $, #, and -.
	PropertyName *string `json:"propertyName,omitempty"`
	// ValueType specifies the type of value this property accepts.
	// - "string": A free-form text value
	// - "single_select": A single value from a predefined list (requires AllowedValues)
	// - "multi_select": Multiple values from a predefined list (requires AllowedValues)
	// - "true_false": A boolean value represented as "true" or "false"
	ValueType *string `json:"valueType,omitempty"`
	// Required indicates whether this property must be set on all repositories.
	// If true, a DefaultValue must be provided.
	Required *bool `json:"required,omitempty"`
	// DefaultValue is the default value for the property.
	// This property must be set if Required is true. It must be empty if Required is false.
	// The allowed format depends on the ValueType.
	// For ValueType "string" or "single_select", it must be a string. For "single_select", it must be one of the AllowedValues.
	// For ValueType "multi_select", it must be a JSON array of strings only containing elements of AllowedValues.
	// For ValueType "true_false", it must be a string that is either "true" or "false".
	DefaultValue *OrgCustomPropertyDefaultValueApplyConfiguration `json:"defaultValue,omitempty"`
	// Description provides additional information about the purpose and usage of this custom property.
	Description *string `json:"description,omitempty"`
	// AllowedValues is a list of allowed values for the property.
	// This property is required for ValueType "single_select" and "multi_select".
	// For the other ValueTypes, it must be empty.
	AllowedValues []string `json:"allowedValues,omitempty"`
	// ValuesEditableBy determines who can edit the property values on repositories.
	// - "org_actors": Only organization members can edit values
	// - "org_and_repo_actors": Both organization and repository members can edit values
	ValuesEditableBy *string `json:"valuesEditableBy,omitempty"`
}

// OrgCustomPropertyApplyConfiguration constructs a declarative configuration of the OrgCustomProperty type for use with
// apply.
func OrgCustomProperty() *OrgCustomPropertyApplyConfiguration {
	return &OrgCustomPropertyApplyConfiguration{}
}

// WithPropertyName sets the PropertyName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PropertyName field is set to the value of the last call.
func (b *OrgCustomPropertyApplyConfiguration) WithPropertyName(value string) *OrgCustomPropertyApplyConfiguration {
	b.PropertyName = &value
	return b
}

// WithValueType sets the ValueType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ValueType field is set to the value of the last call.
func (b *OrgCustomPropertyApplyConfiguration) WithValueType(value string) *OrgCustomPropertyApplyConfiguration {
	b.ValueType = &value
	return b
}

// WithRequired sets the Required field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Required field is set to the value of the last call.
func (b *OrgCustomPropertyApplyConfiguration) WithRequired(value bool) *OrgCustomPropertyApplyConfiguration {
	b.Required = &value
	return b
}

// WithDefaultValue sets the DefaultValue field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefaultValue field is set to the value of the last call.
func (b *OrgCustomPropertyApplyConfiguration) WithDefaultValue(value *OrgCustomPropertyDefaultValueApplyConfiguration) *OrgCustomPropertyApplyConfiguration {
	b.DefaultValue = value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *OrgCustomPropertyApplyConfiguration) WithDescription(value string) *OrgCustomPropertyApplyConfiguration {
	b.Description = &value
	return b
}

// WithAllowedValues adds the given value to the AllowedValues field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllowedValues field.
func (b *OrgCustomPropertyApplyConfiguration) WithAllowedValues(values ...string) *OrgCustomPropertyApplyConfiguration {
	for i := range values {
		b.AllowedValues = append(b.AllowedValues, values[i])
	}
	return b
}

// WithValuesEditableBy sets the ValuesEditableBy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ValuesEditableBy field is set to the value of the last call.
func (b *OrgCustomPropertyApplyConfiguration) WithValuesEditableBy(value string) *OrgCustomPropertyApplyConfiguration {
	b.ValuesEditableBy = &value
	return b
}
