/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// PatternRuleApplyConfiguration represents a declarative configuration of the PatternRule type for use
// with apply.
//
// PatternRule defines a pattern-based rule for enforcing naming conventions or content requirements.
// Patterns are evaluated using the specified operator and can be negated if needed.
// See: https://docs.github.com/en/rest/repos/rules#metadata-restrictions
type PatternRuleApplyConfiguration struct {
	// Pattern is the pattern to match against.
	// For regex operator, this is a regular expression.
	// For other operators, this is a literal string or substring.
	Pattern *string `json:"pattern,omitempty"`
	// Operator defines how the pattern is evaluated.
	// - "starts_with": String must start with the pattern
	// - "ends_with": String must end with the pattern
	// - "contains": String must contain the pattern
	// - "regex": String must match the pattern as a regular expression
	Operator *string `json:"operator,omitempty"`
	// Negate inverts the pattern matching logic.
	// When true, the rule passes if the pattern does NOT match.
	// Example: Use with "contains" to prevent certain words in commit messages.
	Negate *bool `json:"negate,omitempty"`
}

// PatternRuleApplyConfiguration constructs a declarative configuration of the PatternRule type for use with
// apply.
func PatternRule() *PatternRuleApplyConfiguration {
	return &PatternRuleApplyConfiguration{}
}

// WithPattern sets the Pattern field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Pattern field is set to the value of the last call.
func (b *PatternRuleApplyConfiguration) WithPattern(value string) *PatternRuleApplyConfiguration {
	b.Pattern = &value
	return b
}

// WithOperator sets the Operator field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Operator field is set to the value of the last call.
func (b *PatternRuleApplyConfiguration) WithOperator(value string) *PatternRuleApplyConfiguration {
	b.Operator = &value
	return b
}

// WithNegate sets the Negate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Negate field is set to the value of the last call.
func (b *PatternRuleApplyConfiguration) WithNegate(value bool) *PatternRuleApplyConfiguration {
	b.Negate = &value
	return b
}
