/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// PullRequestReviewerEntityApplyConfiguration represents a declarative configuration of the PullRequestReviewerEntity type for use
// with apply.
//
// PullRequestReviewerEntity defines who is required to review as part of a required reviewers pull request rule.
type PullRequestReviewerEntityApplyConfiguration struct {
	// ID of the required reviewer. This field is exclusive with Slug.
	ID *int64 `json:"id,omitempty"`
	// Slug identifying the required reviewer. This field is exclusive with ID.
	// Slug will be resolved to the id during reconciliation.
	Slug *string `json:"slug,omitempty"`
	// Type of the required reviewer. Currently only Teams are supported.
	Type *string `json:"type,omitempty"`
}

// PullRequestReviewerEntityApplyConfiguration constructs a declarative configuration of the PullRequestReviewerEntity type for use with
// apply.
func PullRequestReviewerEntity() *PullRequestReviewerEntityApplyConfiguration {
	return &PullRequestReviewerEntityApplyConfiguration{}
}

// WithID sets the ID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ID field is set to the value of the last call.
func (b *PullRequestReviewerEntityApplyConfiguration) WithID(value int64) *PullRequestReviewerEntityApplyConfiguration {
	b.ID = &value
	return b
}

// WithSlug sets the Slug field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Slug field is set to the value of the last call.
func (b *PullRequestReviewerEntityApplyConfiguration) WithSlug(value string) *PullRequestReviewerEntityApplyConfiguration {
	b.Slug = &value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *PullRequestReviewerEntityApplyConfiguration) WithType(value string) *PullRequestReviewerEntityApplyConfiguration {
	b.Type = &value
	return b
}
