/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// PullRequestRuleApplyConfiguration represents a declarative configuration of the PullRequestRule type for use
// with apply.
//
// PullRequestRule defines pull request requirements that must be met before merging.
// See: https://docs.github.com/en/rest/repos/rules#pull-request
type PullRequestRuleApplyConfiguration struct {
	// AllowedMergeMethods specifies which merge methods are allowed for pull requests.
	// - "squash": Squash all commits into a single commit
	// - "merge": Create a merge commit (preserves all commits)
	// - "rebase": Rebase commits onto the base branch
	AllowedMergeMethods []string `json:"allowedMergeMethods,omitempty"`
	// DismissStaleReviewsOnPush automatically dismisses approved reviews when new commits are pushed.
	// This ensures reviewers see the latest changes before approval.
	DismissStaleReviewsOnPush *bool `json:"dismissStaleReviewsOnPush,omitempty"`
	// RequireCodeOwnerReviews requires approval from code owners before merging.
	// Code owners are defined in a CODEOWNERS file in the repository.
	// See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
	RequireCodeOwnerReviews *bool `json:"requireCodeOwnerReviews,omitempty"`
	// RequireLastPushApproval requires that the most recent push be approved.
	// This prevents merging if new commits are pushed after the last approval.
	RequireLastPushApproval *bool `json:"requireLastPushApproval,omitempty"`
	// RequiredApprovingReviewCount specifies the minimum number of approving reviews required.
	// Must be between 1 and 10.
	RequiredApprovingReviewCount *int `json:"requiredApprovingReviewCount,omitempty"`
	// RequiredReviewThreadResolution requires all review comment threads to be resolved before merging.
	// This ensures all feedback is addressed.
	RequiredReviewThreadResolution *bool `json:"requiredReviewThreadResolution,omitempty"`
}

// PullRequestRuleApplyConfiguration constructs a declarative configuration of the PullRequestRule type for use with
// apply.
func PullRequestRule() *PullRequestRuleApplyConfiguration {
	return &PullRequestRuleApplyConfiguration{}
}

// WithAllowedMergeMethods adds the given value to the AllowedMergeMethods field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllowedMergeMethods field.
func (b *PullRequestRuleApplyConfiguration) WithAllowedMergeMethods(values ...string) *PullRequestRuleApplyConfiguration {
	for i := range values {
		b.AllowedMergeMethods = append(b.AllowedMergeMethods, values[i])
	}
	return b
}

// WithDismissStaleReviewsOnPush sets the DismissStaleReviewsOnPush field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DismissStaleReviewsOnPush field is set to the value of the last call.
func (b *PullRequestRuleApplyConfiguration) WithDismissStaleReviewsOnPush(value bool) *PullRequestRuleApplyConfiguration {
	b.DismissStaleReviewsOnPush = &value
	return b
}

// WithRequireCodeOwnerReviews sets the RequireCodeOwnerReviews field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequireCodeOwnerReviews field is set to the value of the last call.
func (b *PullRequestRuleApplyConfiguration) WithRequireCodeOwnerReviews(value bool) *PullRequestRuleApplyConfiguration {
	b.RequireCodeOwnerReviews = &value
	return b
}

// WithRequireLastPushApproval sets the RequireLastPushApproval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequireLastPushApproval field is set to the value of the last call.
func (b *PullRequestRuleApplyConfiguration) WithRequireLastPushApproval(value bool) *PullRequestRuleApplyConfiguration {
	b.RequireLastPushApproval = &value
	return b
}

// WithRequiredApprovingReviewCount sets the RequiredApprovingReviewCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequiredApprovingReviewCount field is set to the value of the last call.
func (b *PullRequestRuleApplyConfiguration) WithRequiredApprovingReviewCount(value int) *PullRequestRuleApplyConfiguration {
	b.RequiredApprovingReviewCount = &value
	return b
}

// WithRequiredReviewThreadResolution sets the RequiredReviewThreadResolution field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequiredReviewThreadResolution field is set to the value of the last call.
func (b *PullRequestRuleApplyConfiguration) WithRequiredReviewThreadResolution(value bool) *PullRequestRuleApplyConfiguration {
	b.RequiredReviewThreadResolution = &value
	return b
}
