/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// RefNameConditionApplyConfiguration represents a declarative configuration of the RefNameCondition type for use
// with apply.
//
// RefNameCondition defines which refs a ruleset applies to.
// At least one pattern must be specified.
type RefNameConditionApplyConfiguration struct {
	// Include defines ref patterns that the ruleset applies to.
	// Patterns can use wildcards (*) and must start with refs/heads/ (branches) or refs/tags/ (tags).
	// Use "~DEFAULT_BRANCH" to target the default branch.
	// Use "~ALL" to target all branches.
	// Examples: "refs/heads/main", "refs/heads/feature/*", "refs/tags/v*", "~DEFAULT_BRANCH", "~ALL"
	Include []string `json:"include,omitempty"`
	// Exclude defines ref patterns to exempt from the ruleset.
	// Refs matching exclude patterns will not be subject to the ruleset rules.
	// Useful for exempting release branches or other special refs.
	Exclude []string `json:"exclude,omitempty"`
}

// RefNameConditionApplyConfiguration constructs a declarative configuration of the RefNameCondition type for use with
// apply.
func RefNameCondition() *RefNameConditionApplyConfiguration {
	return &RefNameConditionApplyConfiguration{}
}

// WithInclude adds the given value to the Include field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Include field.
func (b *RefNameConditionApplyConfiguration) WithInclude(values ...string) *RefNameConditionApplyConfiguration {
	for i := range values {
		b.Include = append(b.Include, values[i])
	}
	return b
}

// WithExclude adds the given value to the Exclude field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Exclude field.
func (b *RefNameConditionApplyConfiguration) WithExclude(values ...string) *RefNameConditionApplyConfiguration {
	for i := range values {
		b.Exclude = append(b.Exclude, values[i])
	}
	return b
}
