/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// RepositoryStatusApplyConfiguration represents a declarative configuration of the RepositoryStatus type for use
// with apply.
//
// RepositoryStatus defines the observed state of Repository.
type RepositoryStatusApplyConfiguration struct {
	// Webhooks is a list of webhooks configured for this repository
	// the key is the hash of the configuration
	Webhooks map[string]WebhookStatusApplyConfiguration `json:"webhooks,omitempty"`
	// conditions represent the current state of the Repository resource.
	// Each condition has a unique type and reflects the status of a specific aspect of the resource.
	//
	// Standard condition types include:
	// - "Available": the resource is fully functional
	// - "Progressing": the resource is being created or updated
	// - "Degraded": the resource failed to reach or maintain its desired state
	//
	// The status of each condition is one of True, False, or Unknown.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// ID is the repository ID as created by GitHub.
	ID *int64 `json:"id,omitempty"`
	// ObservedSubResourceGenerations is a map of sub-resource names to their observed generations.
	// Keys are in the format "<kind>/<namespace/<name>".
	// SubResources are kubernetes resources that are referenced by this Repository and are not managed
	// by their own controllers like WebhookPresets, RuleSetPresets and the attached CodeSecurityConfiguration
	ObservedSubResourceGenerations map[string]int64 `json:"observedSubResourceGenerations,omitempty"`
}

// RepositoryStatusApplyConfiguration constructs a declarative configuration of the RepositoryStatus type for use with
// apply.
func RepositoryStatus() *RepositoryStatusApplyConfiguration {
	return &RepositoryStatusApplyConfiguration{}
}

// WithWebhooks puts the entries into the Webhooks field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Webhooks field,
// overwriting an existing map entries in Webhooks field with the same key.
func (b *RepositoryStatusApplyConfiguration) WithWebhooks(entries map[string]WebhookStatusApplyConfiguration) *RepositoryStatusApplyConfiguration {
	if b.Webhooks == nil && len(entries) > 0 {
		b.Webhooks = make(map[string]WebhookStatusApplyConfiguration, len(entries))
	}
	for k, v := range entries {
		b.Webhooks[k] = v
	}
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *RepositoryStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *RepositoryStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithID sets the ID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ID field is set to the value of the last call.
func (b *RepositoryStatusApplyConfiguration) WithID(value int64) *RepositoryStatusApplyConfiguration {
	b.ID = &value
	return b
}

// WithObservedSubResourceGenerations puts the entries into the ObservedSubResourceGenerations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the ObservedSubResourceGenerations field,
// overwriting an existing map entries in ObservedSubResourceGenerations field with the same key.
func (b *RepositoryStatusApplyConfiguration) WithObservedSubResourceGenerations(entries map[string]int64) *RepositoryStatusApplyConfiguration {
	if b.ObservedSubResourceGenerations == nil && len(entries) > 0 {
		b.ObservedSubResourceGenerations = make(map[string]int64, len(entries))
	}
	for k, v := range entries {
		b.ObservedSubResourceGenerations[k] = v
	}
	return b
}
