/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// RepositoryNameConditionApplyConfiguration represents a declarative configuration of the RepositoryNameCondition type for use
// with apply.
//
// RepositoryNameCondition defines repository name patterns for organization-level ruleset targeting.
// Only effective for organization-level rulesets; ignored when applied at repository level.
// Use "~ALL" to target all repositories.
// See: https://docs.github.com/en/rest/orgs/rules#create-an-organization-repository-ruleset
type RepositoryNameConditionApplyConfiguration struct {
	// Include defines repository name patterns that the ruleset applies to.
	// Use "~ALL" to target all repositories. Supports wildcards (*).
	// Examples: "~ALL", "my-repo-*", "backend-*"
	Include []string `json:"include,omitempty"`
	// Exclude defines repository name patterns to exempt from the ruleset.
	Exclude []string `json:"exclude,omitempty"`
	// Protected determines whether renaming a targeted repository is prevented.
	Protected *bool `json:"protected,omitempty"`
}

// RepositoryNameConditionApplyConfiguration constructs a declarative configuration of the RepositoryNameCondition type for use with
// apply.
func RepositoryNameCondition() *RepositoryNameConditionApplyConfiguration {
	return &RepositoryNameConditionApplyConfiguration{}
}

// WithInclude adds the given value to the Include field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Include field.
func (b *RepositoryNameConditionApplyConfiguration) WithInclude(values ...string) *RepositoryNameConditionApplyConfiguration {
	for i := range values {
		b.Include = append(b.Include, values[i])
	}
	return b
}

// WithExclude adds the given value to the Exclude field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Exclude field.
func (b *RepositoryNameConditionApplyConfiguration) WithExclude(values ...string) *RepositoryNameConditionApplyConfiguration {
	for i := range values {
		b.Exclude = append(b.Exclude, values[i])
	}
	return b
}

// WithProtected sets the Protected field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Protected field is set to the value of the last call.
func (b *RepositoryNameConditionApplyConfiguration) WithProtected(value bool) *RepositoryNameConditionApplyConfiguration {
	b.Protected = &value
	return b
}
