/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// RepositoryTeamPermissionApplyConfiguration represents a declarative configuration of the RepositoryTeamPermission type for use
// with apply.
//
// RepositoryTeamPermission defines repository-level access for a GitHub team.
type RepositoryTeamPermissionApplyConfiguration struct {
	// TeamRef references the Team CRD that should be granted access to this repository.
	TeamRef *TeamRefApplyConfiguration `json:"teamRef,omitempty"`
	// Permission is the access level granted to the team for this repository.
	// - "pull": Read-only access
	// - "triage": Manage issues and pull requests without write access
	// - "push": Read and write access
	// - "maintain": Manage repository settings except sensitive/destructive actions
	// - "admin": Full repository administrative access
	Permission *string `json:"permission,omitempty"`
}

// RepositoryTeamPermissionApplyConfiguration constructs a declarative configuration of the RepositoryTeamPermission type for use with
// apply.
func RepositoryTeamPermission() *RepositoryTeamPermissionApplyConfiguration {
	return &RepositoryTeamPermissionApplyConfiguration{}
}

// WithTeamRef sets the TeamRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TeamRef field is set to the value of the last call.
func (b *RepositoryTeamPermissionApplyConfiguration) WithTeamRef(value *TeamRefApplyConfiguration) *RepositoryTeamPermissionApplyConfiguration {
	b.TeamRef = value
	return b
}

// WithPermission sets the Permission field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Permission field is set to the value of the last call.
func (b *RepositoryTeamPermissionApplyConfiguration) WithPermission(value string) *RepositoryTeamPermissionApplyConfiguration {
	b.Permission = &value
	return b
}
