/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// RepositoryPropertyConditionApplyConfiguration represents a declarative configuration of the RepositoryPropertyCondition type for use
// with apply.
//
// RepositoryPropertyCondition defines repository property-based conditions for organization-level ruleset targeting.
// Only effective for organization-level rulesets; ignored when applied at repository level.
// Repositories matching the included property conditions (and not matching excluded ones) are targeted.
// See: https://docs.github.com/en/rest/orgs/rules#create-an-organization-repository-ruleset
type RepositoryPropertyConditionApplyConfiguration struct {
	// Include defines repository property conditions that must match for the ruleset to apply.
	// A repository must match all included property conditions. The names of the properties in the slice are
	// validated to be unique.
	Include []RepositoryPropertyTargetApplyConfiguration `json:"include,omitempty"`
	// Exclude defines repository property conditions that exempt repositories from the ruleset.
	// A repository matching any of the conditions is excluded from the rule.
	// The names of the properties in the slice are validated to be unique.
	Exclude []RepositoryPropertyTargetApplyConfiguration `json:"exclude,omitempty"`
}

// RepositoryPropertyConditionApplyConfiguration constructs a declarative configuration of the RepositoryPropertyCondition type for use with
// apply.
func RepositoryPropertyCondition() *RepositoryPropertyConditionApplyConfiguration {
	return &RepositoryPropertyConditionApplyConfiguration{}
}

// WithInclude adds the given value to the Include field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Include field.
func (b *RepositoryPropertyConditionApplyConfiguration) WithInclude(values ...*RepositoryPropertyTargetApplyConfiguration) *RepositoryPropertyConditionApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithInclude")
		}
		b.Include = append(b.Include, *values[i])
	}
	return b
}

// WithExclude adds the given value to the Exclude field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Exclude field.
func (b *RepositoryPropertyConditionApplyConfiguration) WithExclude(values ...*RepositoryPropertyTargetApplyConfiguration) *RepositoryPropertyConditionApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithExclude")
		}
		b.Exclude = append(b.Exclude, *values[i])
	}
	return b
}
