/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// RepositoryCollaboratorPermissionApplyConfiguration represents a declarative configuration of the RepositoryCollaboratorPermission type for use
// with apply.
//
// RepositoryCollaboratorPermission defines repository-level access for a GitHub user.
type RepositoryCollaboratorPermissionApplyConfiguration struct {
	// Username is the GitHub username of the member.
	// Supports standard GitHub usernames and Enterprise Managed Users-style
	// usernames with an underscore suffix (for example: "name-surname_org").
	Username *string `json:"username,omitempty"`
	// Permission is the access level granted to the member for this repository.
	// - "pull": Read-only access
	// - "triage": Manage issues and pull requests without write access
	// - "push": Read and write access
	// - "maintain": Manage repository settings except sensitive/destructive actions
	// - "admin": Full repository administrative access
	Permission *string `json:"permission,omitempty"`
}

// RepositoryCollaboratorPermissionApplyConfiguration constructs a declarative configuration of the RepositoryCollaboratorPermission type for use with
// apply.
func RepositoryCollaboratorPermission() *RepositoryCollaboratorPermissionApplyConfiguration {
	return &RepositoryCollaboratorPermissionApplyConfiguration{}
}

// WithUsername sets the Username field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Username field is set to the value of the last call.
func (b *RepositoryCollaboratorPermissionApplyConfiguration) WithUsername(value string) *RepositoryCollaboratorPermissionApplyConfiguration {
	b.Username = &value
	return b
}

// WithPermission sets the Permission field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Permission field is set to the value of the last call.
func (b *RepositoryCollaboratorPermissionApplyConfiguration) WithPermission(value string) *RepositoryCollaboratorPermissionApplyConfiguration {
	b.Permission = &value
	return b
}
