/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// RepositorySpecApplyConfiguration represents a declarative configuration of the RepositorySpec type for use
// with apply.
//
// RepositorySpec defines the desired state of Repository.
// A Repository represents a GitHub repository and its configuration including settings, webhooks,
// rulesets, custom properties, and more.
// See: https://docs.github.com/en/rest/repos/repos
type RepositorySpecApplyConfiguration struct {
	// TODO: validate validations. Compare with bit-brother.
	// Name is the GitHub repository name.
	// Repository names can contain alphanumeric characters, hyphens, underscores, and periods.
	Name *string `json:"name,omitempty"`
	// CustomProperties is a list of custom property values to apply to this repository.
	// These properties must be defined in the parent organization's custom properties.
	// If a property is not present in this list, it will be unset (removed) from the repository.
	// See: https://docs.github.com/en/rest/repos/custom-properties
	CustomProperties []CustomPropertyValueApplyConfiguration `json:"customProperties,omitempty"`
	// DefaultBranch is the name of the default branch for the repository.
	// This is the base branch for pull requests and where the repository opens by default.
	DefaultBranch *string `json:"defaultBranch,omitempty"`
	// Visibility controls who can see the repository.
	// - "public": Anyone can see the repository
	// - "private": Only people with explicit access can see the repository
	// - "internal": Only members of the organization can see the repository (Enterprise only)
	// See: https://docs.github.com/en/rest/repos/repos#create-an-organization-repository
	Visibility *string `json:"visibility,omitempty"`
	// HasIssues enables or disables the GitHub Issues feature for the repository.
	// When enabled, users can create and track issues.
	HasIssues *bool `json:"hasIssues,omitempty"`
	// HasProjects enables or disables the GitHub Projects (classic) feature for the repository.
	// Note: This refers to classic projects, not the newer Projects feature.
	HasProjects *bool `json:"hasProjects,omitempty"`
	// HasWiki enables or disables the GitHub Wiki feature for the repository.
	// When enabled, users can create wiki pages for documentation.
	HasWiki *bool `json:"hasWiki,omitempty"`
	// HasDownloads enables or disables the Downloads feature for the repository.
	// This feature is deprecated and has been replaced by Releases.
	HasDownloads *bool `json:"hasDownloads,omitempty"`
	// IsTemplate marks the repository as a template repository.
	// Template repositories can be used as a starting point for new repositories.
	// See: https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository
	IsTemplate *bool `json:"isTemplate,omitempty"`
	// MergeCommitTitle determines the default title for merge commits.
	// - "PR_TITLE": Use the pull request title
	// - "MERGE_MESSAGE": Use the default merge message format
	// See: https://docs.github.com/en/rest/repos/repos#update-a-repository
	MergeCommitTitle *string `json:"mergeCommitTitle,omitempty"`
	// MergeCommitMessage determines the default message for merge commits.
	// - "PR_BODY": Use the pull request body
	// - "PR_TITLE": Use the pull request title
	// - "BLANK": Use a blank message
	// See: https://docs.github.com/en/rest/repos/repos#update-a-repository
	MergeCommitMessage *string `json:"mergeCommitMessage,omitempty"`
	// AllowedMergeStrategies lists the merge strategies allowed for pull requests.
	// See: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges
	AllowedMergeStrategies []MergeStrategyApplyConfiguration `json:"allowedMergeStrategies,omitempty"`
	// DeleteBranchOnMerge automatically deletes head branches after pull requests are merged.
	// This helps keep the repository clean by removing merged feature branches.
	// See: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches
	DeleteBranchOnMerge *bool `json:"deleteBranchOnMerge,omitempty"`
	// About contains descriptive information about the repository.
	About *AboutApplyConfiguration `json:"about,omitempty"`
	// Archived marks the repository as archived (read-only).
	// Archived repositories cannot receive new issues, pull requests, or commits.
	// See: https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories
	Archived *bool `json:"archived,omitempty"`
	// ActionsEnabled determines whether this repository can use GitHub Actions.
	// This must be enabled at the organization level for this setting to take effect.
	// See: https://docs.github.com/en/rest/actions/permissions
	ActionsEnabled *bool `json:"actionsEnabled,omitempty"`
	// AccessLevelForExternalWorkflows controls access to workflows outside the repository.
	// - "none": Only workflows in this repository can access actions and reusable workflows
	// - "user": Workflows in user-owned private repositories can access them
	// - "organization": Workflows across the organization can access them
	// - "enterprise": Workflows across the enterprise can access them
	// See: https://docs.github.com/en/rest/actions/permissions
	AccessLevelForExternalWorkflows *string `json:"accessLevelForExternalWorkflows,omitempty"`
	// AvailableActionsRunnerGroups lists runner group names that this repository can use.
	// This is only relevant when the organization's runner groups have "selected" visibility.
	// See: https://docs.github.com/en/rest/actions/self-hosted-runner-groups
	AvailableActionsRunnerGroups []string `json:"availableActionsRunnerGroups,omitempty"`
	// OrganizationRef references the Organization CRD this repository belongs to.
	OrganizationRef *OrganizationRefApplyConfiguration `json:"organizationRef,omitempty"`
	// Teams defines team permissions for this repository.
	// Each entry references an existing Team CRD via TeamRef and assigns it a specific permission level.
	// Teams not present in this list will have their explicit repository access removed.
	// See: https://docs.github.com/en/rest/teams/teams#add-or-update-team-repository-permissions
	Teams []RepositoryTeamPermissionApplyConfiguration `json:"teams,omitempty"`
	// Collaborators defines direct repository member (collaborator) permissions.
	// Each entry assigns a GitHub user a specific permission level.
	// Collaborators not present in this list will have their explicit repository access removed.
	// See: https://docs.github.com/en/rest/collaborators/collaborators#add-a-repository-collaborator
	Collaborators []RepositoryCollaboratorPermissionApplyConfiguration `json:"collaborators,omitempty"`
	// RulesetPresetList references RulesetPreset CRDs to apply to this repository.
	// These define branch protection rules, required status checks, and other policies.
	// See: https://docs.github.com/en/rest/repos/rules
	RulesetPresetList []v1.LocalObjectReference `json:"rulesetPresets,omitempty"`
	// WebhookPresetList references WebhookPreset CRDs to create webhooks for this repository.
	// Webhooks send HTTP POST payloads to external services when specific events occur.
	// See: https://docs.github.com/en/rest/webhooks/repos
	WebhookPresetList []v1.LocalObjectReference `json:"webhookPresets,omitempty"`
	// WebhookIgnorePresetsList references WebhookIgnorePreset CRDs that define webhooks to ignore.
	// Webhooks matching these patterns will not be created even if they are in WebhookPresetList.
	WebhookIgnorePresetsList []v1.LocalObjectReference `json:"webhookIgnorePresets,omitempty"`
	// AutolinksPresetList references AutolinksPreset CRDs to create autolinks for this repository.
	// Autolinks automatically convert references (like "JIRA-123") into clickable links.
	// See: https://docs.github.com/en/rest/repos/autolinks
	AutolinksPresetList []v1.LocalObjectReference `json:"autolinksPresets,omitempty"`
	// DeployKeyList defines deploy keys to create for this repository.
	// Deploy keys are SSH keys that grant access to a single repository.
	// See: https://docs.github.com/en/rest/deploy-keys/deploy-keys
	DeployKeyList []DeployKeyApplyConfiguration `json:"deployKeys,omitempty"`
	// AttachedCodeSecurityConfiguration references a CodeSecurityConfiguration to attach to this repository.
	// This is only used when the organization's configuration has "selected" attachment scope.
	// See: https://docs.github.com/en/rest/code-security/configurations
	AttachedCodeSecurityConfiguration *CodeSecurityConfigurationRefApplyConfiguration `json:"attachedCodeSecurityConfiguration,omitempty"`
}

// RepositorySpecApplyConfiguration constructs a declarative configuration of the RepositorySpec type for use with
// apply.
func RepositorySpec() *RepositorySpecApplyConfiguration {
	return &RepositorySpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *RepositorySpecApplyConfiguration) WithName(value string) *RepositorySpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithCustomProperties adds the given value to the CustomProperties field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the CustomProperties field.
func (b *RepositorySpecApplyConfiguration) WithCustomProperties(values ...*CustomPropertyValueApplyConfiguration) *RepositorySpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithCustomProperties")
		}
		b.CustomProperties = append(b.CustomProperties, *values[i])
	}
	return b
}

// WithDefaultBranch sets the DefaultBranch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefaultBranch field is set to the value of the last call.
func (b *RepositorySpecApplyConfiguration) WithDefaultBranch(value string) *RepositorySpecApplyConfiguration {
	b.DefaultBranch = &value
	return b
}

// WithVisibility sets the Visibility field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Visibility field is set to the value of the last call.
func (b *RepositorySpecApplyConfiguration) WithVisibility(value string) *RepositorySpecApplyConfiguration {
	b.Visibility = &value
	return b
}

// WithHasIssues sets the HasIssues field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HasIssues field is set to the value of the last call.
func (b *RepositorySpecApplyConfiguration) WithHasIssues(value bool) *RepositorySpecApplyConfiguration {
	b.HasIssues = &value
	return b
}

// WithHasProjects sets the HasProjects field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HasProjects field is set to the value of the last call.
func (b *RepositorySpecApplyConfiguration) WithHasProjects(value bool) *RepositorySpecApplyConfiguration {
	b.HasProjects = &value
	return b
}

// WithHasWiki sets the HasWiki field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HasWiki field is set to the value of the last call.
func (b *RepositorySpecApplyConfiguration) WithHasWiki(value bool) *RepositorySpecApplyConfiguration {
	b.HasWiki = &value
	return b
}

// WithHasDownloads sets the HasDownloads field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HasDownloads field is set to the value of the last call.
func (b *RepositorySpecApplyConfiguration) WithHasDownloads(value bool) *RepositorySpecApplyConfiguration {
	b.HasDownloads = &value
	return b
}

// WithIsTemplate sets the IsTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IsTemplate field is set to the value of the last call.
func (b *RepositorySpecApplyConfiguration) WithIsTemplate(value bool) *RepositorySpecApplyConfiguration {
	b.IsTemplate = &value
	return b
}

// WithMergeCommitTitle sets the MergeCommitTitle field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MergeCommitTitle field is set to the value of the last call.
func (b *RepositorySpecApplyConfiguration) WithMergeCommitTitle(value string) *RepositorySpecApplyConfiguration {
	b.MergeCommitTitle = &value
	return b
}

// WithMergeCommitMessage sets the MergeCommitMessage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MergeCommitMessage field is set to the value of the last call.
func (b *RepositorySpecApplyConfiguration) WithMergeCommitMessage(value string) *RepositorySpecApplyConfiguration {
	b.MergeCommitMessage = &value
	return b
}

// WithAllowedMergeStrategies adds the given value to the AllowedMergeStrategies field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllowedMergeStrategies field.
func (b *RepositorySpecApplyConfiguration) WithAllowedMergeStrategies(values ...*MergeStrategyApplyConfiguration) *RepositorySpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAllowedMergeStrategies")
		}
		b.AllowedMergeStrategies = append(b.AllowedMergeStrategies, *values[i])
	}
	return b
}

// WithDeleteBranchOnMerge sets the DeleteBranchOnMerge field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeleteBranchOnMerge field is set to the value of the last call.
func (b *RepositorySpecApplyConfiguration) WithDeleteBranchOnMerge(value bool) *RepositorySpecApplyConfiguration {
	b.DeleteBranchOnMerge = &value
	return b
}

// WithAbout sets the About field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the About field is set to the value of the last call.
func (b *RepositorySpecApplyConfiguration) WithAbout(value *AboutApplyConfiguration) *RepositorySpecApplyConfiguration {
	b.About = value
	return b
}

// WithArchived sets the Archived field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Archived field is set to the value of the last call.
func (b *RepositorySpecApplyConfiguration) WithArchived(value bool) *RepositorySpecApplyConfiguration {
	b.Archived = &value
	return b
}

// WithActionsEnabled sets the ActionsEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ActionsEnabled field is set to the value of the last call.
func (b *RepositorySpecApplyConfiguration) WithActionsEnabled(value bool) *RepositorySpecApplyConfiguration {
	b.ActionsEnabled = &value
	return b
}

// WithAccessLevelForExternalWorkflows sets the AccessLevelForExternalWorkflows field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AccessLevelForExternalWorkflows field is set to the value of the last call.
func (b *RepositorySpecApplyConfiguration) WithAccessLevelForExternalWorkflows(value string) *RepositorySpecApplyConfiguration {
	b.AccessLevelForExternalWorkflows = &value
	return b
}

// WithAvailableActionsRunnerGroups adds the given value to the AvailableActionsRunnerGroups field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AvailableActionsRunnerGroups field.
func (b *RepositorySpecApplyConfiguration) WithAvailableActionsRunnerGroups(values ...string) *RepositorySpecApplyConfiguration {
	for i := range values {
		b.AvailableActionsRunnerGroups = append(b.AvailableActionsRunnerGroups, values[i])
	}
	return b
}

// WithOrganizationRef sets the OrganizationRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OrganizationRef field is set to the value of the last call.
func (b *RepositorySpecApplyConfiguration) WithOrganizationRef(value *OrganizationRefApplyConfiguration) *RepositorySpecApplyConfiguration {
	b.OrganizationRef = value
	return b
}

// WithTeams adds the given value to the Teams field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Teams field.
func (b *RepositorySpecApplyConfiguration) WithTeams(values ...*RepositoryTeamPermissionApplyConfiguration) *RepositorySpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTeams")
		}
		b.Teams = append(b.Teams, *values[i])
	}
	return b
}

// WithCollaborators adds the given value to the Collaborators field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Collaborators field.
func (b *RepositorySpecApplyConfiguration) WithCollaborators(values ...*RepositoryCollaboratorPermissionApplyConfiguration) *RepositorySpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithCollaborators")
		}
		b.Collaborators = append(b.Collaborators, *values[i])
	}
	return b
}

// WithRulesetPresetList adds the given value to the RulesetPresetList field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the RulesetPresetList field.
func (b *RepositorySpecApplyConfiguration) WithRulesetPresetList(values ...v1.LocalObjectReference) *RepositorySpecApplyConfiguration {
	for i := range values {
		b.RulesetPresetList = append(b.RulesetPresetList, values[i])
	}
	return b
}

// WithWebhookPresetList adds the given value to the WebhookPresetList field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the WebhookPresetList field.
func (b *RepositorySpecApplyConfiguration) WithWebhookPresetList(values ...v1.LocalObjectReference) *RepositorySpecApplyConfiguration {
	for i := range values {
		b.WebhookPresetList = append(b.WebhookPresetList, values[i])
	}
	return b
}

// WithWebhookIgnorePresetsList adds the given value to the WebhookIgnorePresetsList field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the WebhookIgnorePresetsList field.
func (b *RepositorySpecApplyConfiguration) WithWebhookIgnorePresetsList(values ...v1.LocalObjectReference) *RepositorySpecApplyConfiguration {
	for i := range values {
		b.WebhookIgnorePresetsList = append(b.WebhookIgnorePresetsList, values[i])
	}
	return b
}

// WithAutolinksPresetList adds the given value to the AutolinksPresetList field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AutolinksPresetList field.
func (b *RepositorySpecApplyConfiguration) WithAutolinksPresetList(values ...v1.LocalObjectReference) *RepositorySpecApplyConfiguration {
	for i := range values {
		b.AutolinksPresetList = append(b.AutolinksPresetList, values[i])
	}
	return b
}

// WithDeployKeyList adds the given value to the DeployKeyList field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the DeployKeyList field.
func (b *RepositorySpecApplyConfiguration) WithDeployKeyList(values ...*DeployKeyApplyConfiguration) *RepositorySpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithDeployKeyList")
		}
		b.DeployKeyList = append(b.DeployKeyList, *values[i])
	}
	return b
}

// WithAttachedCodeSecurityConfiguration sets the AttachedCodeSecurityConfiguration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AttachedCodeSecurityConfiguration field is set to the value of the last call.
func (b *RepositorySpecApplyConfiguration) WithAttachedCodeSecurityConfiguration(value *CodeSecurityConfigurationRefApplyConfiguration) *RepositorySpecApplyConfiguration {
	b.AttachedCodeSecurityConfiguration = value
	return b
}
