/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// RequiredPullRequestReviewerApplyConfiguration represents a declarative configuration of the RequiredPullRequestReviewer type for use
// with apply.
//
// RequiredPullRequestReviewer is the configuration for a required review on all pull request changing files that match
// the configured file patterns.
type RequiredPullRequestReviewerApplyConfiguration struct {
	// MinimumApprovals is the minimum number of approvals required before a matching pull request
	// can be merged. If set to zero, the team will be added to the pull request but approval is optional.
	// Requires a non-negative value. Defaults to 0.
	MinimumApprovals *int `json:"minimumApprovals,omitempty"`
	// FilePatterns are fnmatch syntax patterns that pull request changes are matched against.
	// If a pull request changes any matching file it must be approved by the configured reviewers.
	// Defaults to "*" representing all files.
	FilePatterns []string `json:"filePatterns,omitempty"`
	// Reviewer defines who is required to review.
	Reviewer *PullRequestReviewerEntityApplyConfiguration `json:"reviewer,omitempty"`
}

// RequiredPullRequestReviewerApplyConfiguration constructs a declarative configuration of the RequiredPullRequestReviewer type for use with
// apply.
func RequiredPullRequestReviewer() *RequiredPullRequestReviewerApplyConfiguration {
	return &RequiredPullRequestReviewerApplyConfiguration{}
}

// WithMinimumApprovals sets the MinimumApprovals field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinimumApprovals field is set to the value of the last call.
func (b *RequiredPullRequestReviewerApplyConfiguration) WithMinimumApprovals(value int) *RequiredPullRequestReviewerApplyConfiguration {
	b.MinimumApprovals = &value
	return b
}

// WithFilePatterns adds the given value to the FilePatterns field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the FilePatterns field.
func (b *RequiredPullRequestReviewerApplyConfiguration) WithFilePatterns(values ...string) *RequiredPullRequestReviewerApplyConfiguration {
	for i := range values {
		b.FilePatterns = append(b.FilePatterns, values[i])
	}
	return b
}

// WithReviewer sets the Reviewer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reviewer field is set to the value of the last call.
func (b *RequiredPullRequestReviewerApplyConfiguration) WithReviewer(value *PullRequestReviewerEntityApplyConfiguration) *RequiredPullRequestReviewerApplyConfiguration {
	b.Reviewer = value
	return b
}
