/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// RequiredStatusChecksApplyConfiguration represents a declarative configuration of the RequiredStatusChecks type for use
// with apply.
//
// RequiredStatusChecks defines status check requirements that must pass before merging.
// Status checks are CI/CD jobs, security scans, or other automated checks.
// See: https://docs.github.com/en/rest/repos/rules#required-status-checks
type RequiredStatusChecksApplyConfiguration struct {
	// Checks lists the required status checks that must pass.
	Checks []StatusCheckApplyConfiguration `json:"checks,omitempty"`
	// StrictPolicy requires branches to be up to date with the base branch before merging.
	// When enabled, branches must include the latest changes from the base branch.
	// This prevents merge conflicts but may require additional merges/rebases.
	StrictPolicy *bool `json:"strictPolicy,omitempty"`
}

// RequiredStatusChecksApplyConfiguration constructs a declarative configuration of the RequiredStatusChecks type for use with
// apply.
func RequiredStatusChecks() *RequiredStatusChecksApplyConfiguration {
	return &RequiredStatusChecksApplyConfiguration{}
}

// WithChecks adds the given value to the Checks field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Checks field.
func (b *RequiredStatusChecksApplyConfiguration) WithChecks(values ...*StatusCheckApplyConfiguration) *RequiredStatusChecksApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithChecks")
		}
		b.Checks = append(b.Checks, *values[i])
	}
	return b
}

// WithStrictPolicy sets the StrictPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StrictPolicy field is set to the value of the last call.
func (b *RequiredStatusChecksApplyConfiguration) WithStrictPolicy(value bool) *RequiredStatusChecksApplyConfiguration {
	b.StrictPolicy = &value
	return b
}
