/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/Interhyp/git-hubby/api/v1alpha1"
)

// RulesetPresetSpecApplyConfiguration represents a declarative configuration of the RulesetPresetSpec type for use
// with apply.
//
// EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
// NOTE: json tags are required.  Any new fields you add must have json tags for the fields to be serialized.
// RulesetPresetSpec defines the desired state of RulesetPreset.
// A ruleset preset defines reusable repository rules that can be applied to multiple repositories
// or organizations. Rulesets enforce policies like branch protection, required reviews, and more.
// See: https://docs.github.com/en/rest/repos/rules
type RulesetPresetSpecApplyConfiguration struct {
	// Name is the display name of the ruleset shown in the GitHub UI.
	Name *string `json:"name,omitempty"`
	// Target defines which ref types this ruleset applies to.
	// The Target 'repository' is only supported by Organization-level RulesetPresets. Repository-level
	// RulesetPresets with Target 'repository' are filtered out (i.e. are not checked nor applied).
	Target *string `json:"target,omitempty"`
	// Conditions defines which refs are included or excluded in the list of targets for this Ruleset.
	// They also define which Repositories are targeted by Organization-level Rulesets.
	Conditions *RulesetConditionsApplyConfiguration `json:"conditions,omitempty"`
	// Enforcement determines whether the ruleset is enforced.
	// - "disabled": Ruleset is not enforced
	// - "active": Ruleset is actively enforced; violations block operations
	// - "evaluate": Ruleset is evaluated but violations only generate warnings
	Enforcement *apiv1alpha1.RulesetEnforcement `json:"enforcement,omitempty"`
	// BypassActors defines actors (users, teams, apps) who can bypass this ruleset.
	// Bypass actors can perform operations that would otherwise be blocked by the ruleset.
	// See: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/about-rulesets#about-bypass-mode-for-rulesets
	BypassActors []RulesetBypassActorApplyConfiguration `json:"bypassActors,omitempty"`
	// Rules defines the specific rules to enforce in this ruleset.
	Rules *RulesetRulesApplyConfiguration `json:"rules,omitempty"`
}

// RulesetPresetSpecApplyConfiguration constructs a declarative configuration of the RulesetPresetSpec type for use with
// apply.
func RulesetPresetSpec() *RulesetPresetSpecApplyConfiguration {
	return &RulesetPresetSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *RulesetPresetSpecApplyConfiguration) WithName(value string) *RulesetPresetSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithTarget sets the Target field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Target field is set to the value of the last call.
func (b *RulesetPresetSpecApplyConfiguration) WithTarget(value string) *RulesetPresetSpecApplyConfiguration {
	b.Target = &value
	return b
}

// WithConditions sets the Conditions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Conditions field is set to the value of the last call.
func (b *RulesetPresetSpecApplyConfiguration) WithConditions(value *RulesetConditionsApplyConfiguration) *RulesetPresetSpecApplyConfiguration {
	b.Conditions = value
	return b
}

// WithEnforcement sets the Enforcement field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enforcement field is set to the value of the last call.
func (b *RulesetPresetSpecApplyConfiguration) WithEnforcement(value apiv1alpha1.RulesetEnforcement) *RulesetPresetSpecApplyConfiguration {
	b.Enforcement = &value
	return b
}

// WithBypassActors adds the given value to the BypassActors field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the BypassActors field.
func (b *RulesetPresetSpecApplyConfiguration) WithBypassActors(values ...*RulesetBypassActorApplyConfiguration) *RulesetPresetSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithBypassActors")
		}
		b.BypassActors = append(b.BypassActors, *values[i])
	}
	return b
}

// WithRules sets the Rules field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Rules field is set to the value of the last call.
func (b *RulesetPresetSpecApplyConfiguration) WithRules(value *RulesetRulesApplyConfiguration) *RulesetPresetSpecApplyConfiguration {
	b.Rules = value
	return b
}
