/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// RulesetRulesApplyConfiguration represents a declarative configuration of the RulesetRules type for use
// with apply.
//
// RulesetRules defines the specific rules to enforce in a ruleset.
// Each rule is optional and can be combined to create comprehensive protection policies.
// See: https://docs.github.com/en/rest/repos/rules#available-rules
type RulesetRulesApplyConfiguration struct {
	// Creation prevents the creation of matching refs.
	// When enabled, users cannot create branches or tags matching the ruleset target.
	Creation *bool `json:"creation,omitempty"`
	// Update prevents updates to matching refs.
	// When enabled, users cannot push commits to matching branches.
	Update *bool `json:"update,omitempty"`
	// Deletion prevents deletion of matching refs.
	// When enabled, users cannot delete matching branches or tags.
	Deletion *bool `json:"deletion,omitempty"`
	// RequiredLinearHistory requires branches to have a linear commit history.
	// When enabled, merge commits are not allowed; only rebasing and fast-forward merges are permitted.
	RequiredLinearHistory *bool `json:"requiredLinearHistory,omitempty"`
	// RequiredSignatures requires commits to be signed with a verified signature.
	// When enabled, only commits signed with GPG, SSH, or S/MIME are allowed.
	// See: https://docs.github.com/en/authentication/managing-commit-signature-verification
	RequiredSignatures *bool `json:"requiredSignatures,omitempty"`
	// PullRequest defines pull request requirements for merging.
	// See: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches#require-pull-request-reviews-before-merging
	PullRequest *PullRequestRuleApplyConfiguration `json:"pullRequest,omitempty"`
	// RequiredStatusChecks defines status checks that must pass before merging.
	// See: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches#require-status-checks-before-merging
	RequiredStatusChecks *RequiredStatusChecksApplyConfiguration `json:"requiredStatusChecks,omitempty"`
	// NonFastForward prevents non-fast-forward updates.
	// When enabled, only fast-forward pushes are allowed, preventing force pushes.
	NonFastForward *bool `json:"nonFastForward,omitempty"`
	// CommitMessagePattern enforces a pattern for commit messages.
	// Use this to enforce commit message conventions like Conventional Commits.
	CommitMessagePattern *PatternRuleApplyConfiguration `json:"commitMessagePattern,omitempty"`
	// CommitAuthorEmailPattern enforces a pattern for commit author email addresses.
	// Use this to ensure commits come from verified email domains.
	CommitAuthorEmailPattern *PatternRuleApplyConfiguration `json:"commitAuthorEmailPattern,omitempty"`
	// CommitterEmailPattern enforces a pattern for committer email addresses.
	CommitterEmailPattern *PatternRuleApplyConfiguration `json:"committerEmailPattern,omitempty"`
	// BranchNamePattern enforces a pattern for branch names.
	// Use this to enforce branch naming conventions like "feature/*" or "hotfix/*".
	BranchNamePattern *PatternRuleApplyConfiguration `json:"branchNamePattern,omitempty"`
	// TagNamePattern enforces a pattern for tag names.
	// Use this to enforce semantic versioning or other tag naming conventions.
	TagNamePattern *PatternRuleApplyConfiguration `json:"tagNamePattern,omitempty"`
	// CopilotReview automatically requests a GitHub Copilot pull request review
	// if the author has access to Copilot code review and their premium requests quota has not reached the limit.
	CopilotReview *CopilotCodeReviewRuleApplyConfiguration `json:"copilotReview,omitempty"`
	// Workflows defines required workflow rules that must pass before merging.
	// This rule type is only effective for organization-level rulesets and is ignored
	// when the preset is applied at the repository level.
	// See: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/available-rules-for-rulesets#require-workflows-to-pass-before-merging
	Workflows *WorkflowsRuleApplyConfiguration `json:"workflows,omitempty"`
}

// RulesetRulesApplyConfiguration constructs a declarative configuration of the RulesetRules type for use with
// apply.
func RulesetRules() *RulesetRulesApplyConfiguration {
	return &RulesetRulesApplyConfiguration{}
}

// WithCreation sets the Creation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Creation field is set to the value of the last call.
func (b *RulesetRulesApplyConfiguration) WithCreation(value bool) *RulesetRulesApplyConfiguration {
	b.Creation = &value
	return b
}

// WithUpdate sets the Update field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Update field is set to the value of the last call.
func (b *RulesetRulesApplyConfiguration) WithUpdate(value bool) *RulesetRulesApplyConfiguration {
	b.Update = &value
	return b
}

// WithDeletion sets the Deletion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Deletion field is set to the value of the last call.
func (b *RulesetRulesApplyConfiguration) WithDeletion(value bool) *RulesetRulesApplyConfiguration {
	b.Deletion = &value
	return b
}

// WithRequiredLinearHistory sets the RequiredLinearHistory field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequiredLinearHistory field is set to the value of the last call.
func (b *RulesetRulesApplyConfiguration) WithRequiredLinearHistory(value bool) *RulesetRulesApplyConfiguration {
	b.RequiredLinearHistory = &value
	return b
}

// WithRequiredSignatures sets the RequiredSignatures field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequiredSignatures field is set to the value of the last call.
func (b *RulesetRulesApplyConfiguration) WithRequiredSignatures(value bool) *RulesetRulesApplyConfiguration {
	b.RequiredSignatures = &value
	return b
}

// WithPullRequest sets the PullRequest field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PullRequest field is set to the value of the last call.
func (b *RulesetRulesApplyConfiguration) WithPullRequest(value *PullRequestRuleApplyConfiguration) *RulesetRulesApplyConfiguration {
	b.PullRequest = value
	return b
}

// WithRequiredStatusChecks sets the RequiredStatusChecks field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequiredStatusChecks field is set to the value of the last call.
func (b *RulesetRulesApplyConfiguration) WithRequiredStatusChecks(value *RequiredStatusChecksApplyConfiguration) *RulesetRulesApplyConfiguration {
	b.RequiredStatusChecks = value
	return b
}

// WithNonFastForward sets the NonFastForward field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NonFastForward field is set to the value of the last call.
func (b *RulesetRulesApplyConfiguration) WithNonFastForward(value bool) *RulesetRulesApplyConfiguration {
	b.NonFastForward = &value
	return b
}

// WithCommitMessagePattern sets the CommitMessagePattern field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CommitMessagePattern field is set to the value of the last call.
func (b *RulesetRulesApplyConfiguration) WithCommitMessagePattern(value *PatternRuleApplyConfiguration) *RulesetRulesApplyConfiguration {
	b.CommitMessagePattern = value
	return b
}

// WithCommitAuthorEmailPattern sets the CommitAuthorEmailPattern field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CommitAuthorEmailPattern field is set to the value of the last call.
func (b *RulesetRulesApplyConfiguration) WithCommitAuthorEmailPattern(value *PatternRuleApplyConfiguration) *RulesetRulesApplyConfiguration {
	b.CommitAuthorEmailPattern = value
	return b
}

// WithCommitterEmailPattern sets the CommitterEmailPattern field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CommitterEmailPattern field is set to the value of the last call.
func (b *RulesetRulesApplyConfiguration) WithCommitterEmailPattern(value *PatternRuleApplyConfiguration) *RulesetRulesApplyConfiguration {
	b.CommitterEmailPattern = value
	return b
}

// WithBranchNamePattern sets the BranchNamePattern field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BranchNamePattern field is set to the value of the last call.
func (b *RulesetRulesApplyConfiguration) WithBranchNamePattern(value *PatternRuleApplyConfiguration) *RulesetRulesApplyConfiguration {
	b.BranchNamePattern = value
	return b
}

// WithTagNamePattern sets the TagNamePattern field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TagNamePattern field is set to the value of the last call.
func (b *RulesetRulesApplyConfiguration) WithTagNamePattern(value *PatternRuleApplyConfiguration) *RulesetRulesApplyConfiguration {
	b.TagNamePattern = value
	return b
}

// WithCopilotReview sets the CopilotReview field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CopilotReview field is set to the value of the last call.
func (b *RulesetRulesApplyConfiguration) WithCopilotReview(value *CopilotCodeReviewRuleApplyConfiguration) *RulesetRulesApplyConfiguration {
	b.CopilotReview = value
	return b
}

// WithWorkflows sets the Workflows field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Workflows field is set to the value of the last call.
func (b *RulesetRulesApplyConfiguration) WithWorkflows(value *WorkflowsRuleApplyConfiguration) *RulesetRulesApplyConfiguration {
	b.Workflows = value
	return b
}
