/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// RulesetBypassActorApplyConfiguration represents a declarative configuration of the RulesetBypassActor type for use
// with apply.
//
// RulesetBypassActor defines an actor (user, team, or integration) who can bypass ruleset enforcement.
// Either ActorID (for direct specification) or ActorSlug (for name-based resolution) must be provided for
// ActorTypes "Integration" and "Team". ActorID must be provided for ActorType "RepositoryRole".
// Both must be empty for ActorType "DeployKey".
// See: https://docs.github.com/en/rest/repos/rules#create-an-organization-repository-ruleset
type RulesetBypassActorApplyConfiguration struct {
	// ActorID is the numeric ID of the bypass actor.
	// This field is mutually exclusive with ActorSlug.
	ActorID *int64 `json:"actorId,omitempty"`
	// ActorSlug is the slug or name of the actor, which will be resolved to an ID.
	// This field is mutually exclusive with ActorID.
	// Only supported for ActorType "Integration" (GitHub Apps) and "Team" (organization teams).
	// For Integration, use the app slug (e.g., "my-github-app").
	// For Team, use the team slug (e.g., "platform-engineers").
	ActorSlug *string `json:"actorSlug,omitempty"`
	// ActorType specifies the type of actor that can bypass the ruleset.
	// - "Integration": A GitHub App
	// - "OrganizationAdmin": Organization administrators
	// - "RepositoryRole": Users with a specific repository role
	// - "Team": An organization team
	// - "DeployKey": A deploy key
	// - "EnterpriseOwner": Enterprise owners (GitHub Enterprise only)
	ActorType *string `json:"actorType,omitempty"`
	// BypassMode determines when and how the actor can bypass the ruleset.
	// - "always": Actor can always bypass the ruleset
	// - "pull_request": Actor can bypass only when submitting via pull request
	BypassMode *string `json:"bypassMode,omitempty"`
}

// RulesetBypassActorApplyConfiguration constructs a declarative configuration of the RulesetBypassActor type for use with
// apply.
func RulesetBypassActor() *RulesetBypassActorApplyConfiguration {
	return &RulesetBypassActorApplyConfiguration{}
}

// WithActorID sets the ActorID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ActorID field is set to the value of the last call.
func (b *RulesetBypassActorApplyConfiguration) WithActorID(value int64) *RulesetBypassActorApplyConfiguration {
	b.ActorID = &value
	return b
}

// WithActorSlug sets the ActorSlug field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ActorSlug field is set to the value of the last call.
func (b *RulesetBypassActorApplyConfiguration) WithActorSlug(value string) *RulesetBypassActorApplyConfiguration {
	b.ActorSlug = &value
	return b
}

// WithActorType sets the ActorType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ActorType field is set to the value of the last call.
func (b *RulesetBypassActorApplyConfiguration) WithActorType(value string) *RulesetBypassActorApplyConfiguration {
	b.ActorType = &value
	return b
}

// WithBypassMode sets the BypassMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BypassMode field is set to the value of the last call.
func (b *RulesetBypassActorApplyConfiguration) WithBypassMode(value string) *RulesetBypassActorApplyConfiguration {
	b.BypassMode = &value
	return b
}
