/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// RulesetConditionsApplyConfiguration represents a declarative configuration of the RulesetConditions type for use
// with apply.
//
// RulesetConditions define which refs are targeted by the Ruleset. For Organization-level rules they additionally define
// which Repositories are targeted by the Ruleset via the fields RepositoryName and RepositoryProperty. If neither
// RepositoryName nor RepositoryProperty are set for an Organization-level ruleset, the ruleset will target all repositories.
type RulesetConditionsApplyConfiguration struct {
	// RefName defines which git refs (branches or tags) a ruleset applies to.
	RefName *RefNameConditionApplyConfiguration `json:"refName,omitempty"`
	// RepositoryName targets repositories for Organization-level rulesets by their name.
	// The field is ignored for Repository-level rulesets.
	RepositoryName *RepositoryNameConditionApplyConfiguration `json:"repositoryName,omitempty"`
	// RepositoryProperty targets repositories for Organization-level rulesets by matching against custom properties.
	// The field is ignored for Repository-level rulesets.
	RepositoryProperty *RepositoryPropertyConditionApplyConfiguration `json:"repositoryProperty,omitempty"`
}

// RulesetConditionsApplyConfiguration constructs a declarative configuration of the RulesetConditions type for use with
// apply.
func RulesetConditions() *RulesetConditionsApplyConfiguration {
	return &RulesetConditionsApplyConfiguration{}
}

// WithRefName sets the RefName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RefName field is set to the value of the last call.
func (b *RulesetConditionsApplyConfiguration) WithRefName(value *RefNameConditionApplyConfiguration) *RulesetConditionsApplyConfiguration {
	b.RefName = value
	return b
}

// WithRepositoryName sets the RepositoryName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RepositoryName field is set to the value of the last call.
func (b *RulesetConditionsApplyConfiguration) WithRepositoryName(value *RepositoryNameConditionApplyConfiguration) *RulesetConditionsApplyConfiguration {
	b.RepositoryName = value
	return b
}

// WithRepositoryProperty sets the RepositoryProperty field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RepositoryProperty field is set to the value of the last call.
func (b *RulesetConditionsApplyConfiguration) WithRepositoryProperty(value *RepositoryPropertyConditionApplyConfiguration) *RulesetConditionsApplyConfiguration {
	b.RepositoryProperty = value
	return b
}
