/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// RuleWorkflowApplyConfiguration represents a declarative configuration of the RuleWorkflow type for use
// with apply.
//
// RuleWorkflow defines a single required workflow for the workflows rule.
// The workflow is referenced by its path in a repository. The repository is identified by name
// (resolved to a numeric ID at reconciliation time via the GitHub API).
type RuleWorkflowApplyConfiguration struct {
	// Path is the path to the workflow file relative to the repository root.
	// Example: ".github/workflows/ci.yaml"
	Path *string `json:"path,omitempty"`
	// RepositoryName is the name of the repository containing the workflow.
	// Must be a repository within the same organization. The name will be resolved
	// to a numeric repository ID at reconciliation time via the GitHub API.
	RepositoryName *string `json:"repositoryName,omitempty"`
	// Ref is the git ref (branch, tag, or SHA) to use for the workflow file.
	// Example: "refs/heads/main"
	Ref *string `json:"ref,omitempty"`
}

// RuleWorkflowApplyConfiguration constructs a declarative configuration of the RuleWorkflow type for use with
// apply.
func RuleWorkflow() *RuleWorkflowApplyConfiguration {
	return &RuleWorkflowApplyConfiguration{}
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *RuleWorkflowApplyConfiguration) WithPath(value string) *RuleWorkflowApplyConfiguration {
	b.Path = &value
	return b
}

// WithRepositoryName sets the RepositoryName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RepositoryName field is set to the value of the last call.
func (b *RuleWorkflowApplyConfiguration) WithRepositoryName(value string) *RuleWorkflowApplyConfiguration {
	b.RepositoryName = &value
	return b
}

// WithRef sets the Ref field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ref field is set to the value of the last call.
func (b *RuleWorkflowApplyConfiguration) WithRef(value string) *RuleWorkflowApplyConfiguration {
	b.Ref = &value
	return b
}
