/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// RunnerGroupApplyConfiguration represents a declarative configuration of the RunnerGroup type for use
// with apply.
//
// RunnerGroup configures a self-hosted runner group for GitHub Actions in an organization.
// Runner groups allow you to control which repositories can use specific sets of self-hosted runners.
// See: https://docs.github.com/en/rest/actions/self-hosted-runner-groups
type RunnerGroupApplyConfiguration struct {
	// Name is the unique name of the runner group within the organization.
	Name *string `json:"name,omitempty"`
	// Visibility determines which repositories can access runners in this group.
	// - "all": All repositories in the organization can use these runners
	// - "private": Only private repositories can use these runners
	// - "selected": Only specific repositories can use these runners (selected via AvailableActionsRunnerGroups in RepositorySpec)
	Visibility *string `json:"visibility,omitempty"`
	// RestrictedToWorkflows determines whether this runner group can only run specific workflows.
	// If true, only workflows listed in SelectedWorkflows can use runners in this group.
	// This provides additional security by limiting which workflows can execute on sensitive runners.
	RestrictedToWorkflows *bool `json:"restrictedToWorkflows,omitempty"`
	// SelectedWorkflows lists the workflows that can use runners in this group.
	// This field is only used when RestrictedToWorkflows is true.
	// Each entry must be a full workflow path with a reference (branch, tag, or SHA).
	// Example: "octo-org/octo-repo/.github/workflows/deploy.yaml@refs/heads/main"
	SelectedWorkflows []string `json:"selectedWorkflows,omitempty"`
}

// RunnerGroupApplyConfiguration constructs a declarative configuration of the RunnerGroup type for use with
// apply.
func RunnerGroup() *RunnerGroupApplyConfiguration {
	return &RunnerGroupApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *RunnerGroupApplyConfiguration) WithName(value string) *RunnerGroupApplyConfiguration {
	b.Name = &value
	return b
}

// WithVisibility sets the Visibility field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Visibility field is set to the value of the last call.
func (b *RunnerGroupApplyConfiguration) WithVisibility(value string) *RunnerGroupApplyConfiguration {
	b.Visibility = &value
	return b
}

// WithRestrictedToWorkflows sets the RestrictedToWorkflows field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RestrictedToWorkflows field is set to the value of the last call.
func (b *RunnerGroupApplyConfiguration) WithRestrictedToWorkflows(value bool) *RunnerGroupApplyConfiguration {
	b.RestrictedToWorkflows = &value
	return b
}

// WithSelectedWorkflows adds the given value to the SelectedWorkflows field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the SelectedWorkflows field.
func (b *RunnerGroupApplyConfiguration) WithSelectedWorkflows(values ...string) *RunnerGroupApplyConfiguration {
	for i := range values {
		b.SelectedWorkflows = append(b.SelectedWorkflows, values[i])
	}
	return b
}
