/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/Interhyp/git-hubby/api/v1alpha1"
)

// SecretScanningDelegatedBypassOptionsApplyConfiguration represents a declarative configuration of the SecretScanningDelegatedBypassOptions type for use
// with apply.
//
// SecretScanningDelegatedBypassOptions configures reviewers who can approve secret scanning bypass requests.
// When delegated bypass is enabled, contributors can request to bypass secret scanning push protection,
// and the specified reviewers can approve or deny these requests.
// See: https://docs.github.com/en/rest/code-security/configurations
type SecretScanningDelegatedBypassOptionsApplyConfiguration struct {
	// Reviewers is a list of teams or organization roles that can review bypass requests.
	Reviewers []*apiv1alpha1.BypassReviewer `json:"reviewers,omitempty"`
}

// SecretScanningDelegatedBypassOptionsApplyConfiguration constructs a declarative configuration of the SecretScanningDelegatedBypassOptions type for use with
// apply.
func SecretScanningDelegatedBypassOptions() *SecretScanningDelegatedBypassOptionsApplyConfiguration {
	return &SecretScanningDelegatedBypassOptionsApplyConfiguration{}
}

// WithReviewers adds the given value to the Reviewers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Reviewers field.
func (b *SecretScanningDelegatedBypassOptionsApplyConfiguration) WithReviewers(values ...**apiv1alpha1.BypassReviewer) *SecretScanningDelegatedBypassOptionsApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithReviewers")
		}
		b.Reviewers = append(b.Reviewers, *values[i])
	}
	return b
}
