/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// SelectedAllowedActionsApplyConfiguration represents a declarative configuration of the SelectedAllowedActions type for use
// with apply.
//
// SelectedAllowedActions defines which specific actions are allowed when AllowedActions is set to "selected".
// At least one setting must be configured to allow some actions.
// See: https://docs.github.com/en/rest/actions/permissions
type SelectedAllowedActionsApplyConfiguration struct {
	// GitHubOwnedAllowed determines whether actions created by GitHub are allowed to run.
	// This includes actions in the "actions" and "github" organizations.
	GitHubOwnedAllowed *bool `json:"githubOwnedAllowed,omitempty"`
	// VerifiedAllowed determines whether actions from verified creators are allowed to run.
	// Verified creators are trusted partners and organizations with verified domains.
	VerifiedAllowed *bool `json:"verifiedAllowed,omitempty"`
	// PatternsAllowed is a list of glob patterns specifying allowed actions.
	// Each pattern can match action repositories using wildcards, e.g., "my-org/*" or "*/action-name@*".
	PatternsAllowed []string `json:"patternsAllowed,omitempty"`
}

// SelectedAllowedActionsApplyConfiguration constructs a declarative configuration of the SelectedAllowedActions type for use with
// apply.
func SelectedAllowedActions() *SelectedAllowedActionsApplyConfiguration {
	return &SelectedAllowedActionsApplyConfiguration{}
}

// WithGitHubOwnedAllowed sets the GitHubOwnedAllowed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GitHubOwnedAllowed field is set to the value of the last call.
func (b *SelectedAllowedActionsApplyConfiguration) WithGitHubOwnedAllowed(value bool) *SelectedAllowedActionsApplyConfiguration {
	b.GitHubOwnedAllowed = &value
	return b
}

// WithVerifiedAllowed sets the VerifiedAllowed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VerifiedAllowed field is set to the value of the last call.
func (b *SelectedAllowedActionsApplyConfiguration) WithVerifiedAllowed(value bool) *SelectedAllowedActionsApplyConfiguration {
	b.VerifiedAllowed = &value
	return b
}

// WithPatternsAllowed adds the given value to the PatternsAllowed field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PatternsAllowed field.
func (b *SelectedAllowedActionsApplyConfiguration) WithPatternsAllowed(values ...string) *SelectedAllowedActionsApplyConfiguration {
	for i := range values {
		b.PatternsAllowed = append(b.PatternsAllowed, values[i])
	}
	return b
}
