/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// StatusCheckApplyConfiguration represents a declarative configuration of the StatusCheck type for use
// with apply.
//
// StatusCheck defines a required status check that must pass before merging.
// A status check can be provided by a GitHub App or CI/CD integration.
// See: https://docs.github.com/en/rest/repos/rules#required-status-checks
type StatusCheckApplyConfiguration struct {
	// Context is the name of the status check as reported by the CI/CD system or app.
	// Examples: "ci/circleci: build", "Security Scan", "Unit Tests"
	Context *string `json:"context,omitempty"`
	// IntegrationID is the numeric ID of the GitHub App integration providing the status check.
	// This field is mutually exclusive with AppSlug.
	IntegrationID *int64 `json:"integrationId,omitempty"`
	// AppSlug is the slug of the GitHub App integration providing the status check.
	// This field is mutually exclusive with IntegrationID.
	// The slug will be resolved to the corresponding integration ID.
	// Only supported for GitHub App integrations.
	// Example: "my-ci-app"
	AppSlug *string `json:"appSlug,omitempty"`
}

// StatusCheckApplyConfiguration constructs a declarative configuration of the StatusCheck type for use with
// apply.
func StatusCheck() *StatusCheckApplyConfiguration {
	return &StatusCheckApplyConfiguration{}
}

// WithContext sets the Context field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Context field is set to the value of the last call.
func (b *StatusCheckApplyConfiguration) WithContext(value string) *StatusCheckApplyConfiguration {
	b.Context = &value
	return b
}

// WithIntegrationID sets the IntegrationID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IntegrationID field is set to the value of the last call.
func (b *StatusCheckApplyConfiguration) WithIntegrationID(value int64) *StatusCheckApplyConfiguration {
	b.IntegrationID = &value
	return b
}

// WithAppSlug sets the AppSlug field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AppSlug field is set to the value of the last call.
func (b *StatusCheckApplyConfiguration) WithAppSlug(value string) *StatusCheckApplyConfiguration {
	b.AppSlug = &value
	return b
}
