/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// TeamStatusApplyConfiguration represents a declarative configuration of the TeamStatus type for use
// with apply.
//
// TeamStatus defines the observed state of Team.
type TeamStatusApplyConfiguration struct {
	// conditions represent the current state of the Team resource.
	// Each condition has a unique type and reflects the status of a specific aspect of the resource.
	//
	// Standard condition types include:
	// - "Available": the resource is fully functional
	// - "Progressing": the resource is being created or updated
	// - "Degraded": the resource failed to reach or maintain its desired state
	//
	// The status of each condition is one of True, False, or Unknown.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// PreviousOrganizationRefs tracks the organization references from the last successful reconciliation.
	// This allows the reconciler to detect when organizations are removed from the spec
	// and clean up teams from those organizations while preserving them in remaining organizations.
	PreviousOrganizationRefs []OrganizationRefApplyConfiguration `json:"previousOrganizationRefs,omitempty"`
	// Slug is the URL-friendly version of the team name as assigned by GitHub.
	// This slug is used in URLs and API calls. GitHub generates it automatically from the Name field.
	// Example: A team named "Platform Engineers" might have the slug "platform-engineers".
	Slug *string `json:"slug,omitempty"`
}

// TeamStatusApplyConfiguration constructs a declarative configuration of the TeamStatus type for use with
// apply.
func TeamStatus() *TeamStatusApplyConfiguration {
	return &TeamStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *TeamStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *TeamStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithPreviousOrganizationRefs adds the given value to the PreviousOrganizationRefs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PreviousOrganizationRefs field.
func (b *TeamStatusApplyConfiguration) WithPreviousOrganizationRefs(values ...*OrganizationRefApplyConfiguration) *TeamStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPreviousOrganizationRefs")
		}
		b.PreviousOrganizationRefs = append(b.PreviousOrganizationRefs, *values[i])
	}
	return b
}

// WithSlug sets the Slug field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Slug field is set to the value of the last call.
func (b *TeamStatusApplyConfiguration) WithSlug(value string) *TeamStatusApplyConfiguration {
	b.Slug = &value
	return b
}
