/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// TeamSpecApplyConfiguration represents a declarative configuration of the TeamSpec type for use
// with apply.
//
// EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
// NOTE: json tags are required.  Any new fields you add must have json tags for the fields to be serialized.
// TeamSpec defines the desired state of Team within one or more Organizations.
// Teams group organization members and can be assigned permissions to repositories.
// A Team can exist in multiple organizations simultaneously.
// See: https://docs.github.com/en/rest/teams/teams
type TeamSpecApplyConfiguration struct {
	// Name is the display name of the team in GitHub.
	// GitHub automatically generates a "slug" from this name for use in URLs and APIs.
	Name *string `json:"name,omitempty"`
	// Members is a list of GitHub usernames to add to the team.
	// This field is mutually exclusive with IDPGroup.
	// When set, team membership is managed manually through this list.
	// Members not in this list will be removed from the team.
	Members []string `json:"members,omitempty"`
	// IDPGroup is the name of the Identity Provider group to synchronize with this team.
	// This field is mutually exclusive with Members.
	// When set, team membership is automatically synchronized from the IDP group.
	// See: https://docs.github.com/en/organizations/organizing-members-into-teams/synchronizing-a-team-with-an-identity-provider-group
	IDPGroup *string `json:"idpGroup,omitempty"`
	// Description provides additional information about the team's purpose.
	// This appears on the team's page in GitHub.
	Description *string `json:"description,omitempty"`
	// Privacy controls the visibility of the team within the organization.
	// - "closed": The team is visible to all members of the organization, but only team members can see team discussions and manage team membership.
	// - "secret": The team is only visible to organization owners and team members.
	// See: https://docs.github.com/en/rest/teams/teams#create-a-team
	Privacy *string `json:"privacy,omitempty"`
	// Permission specifies the default permission granted to team members for organization repositories.
	// - "pull": Team members can pull (read) from organization repositories.
	// - "push": Team members can pull and push (read and write) to organization repositories.
	// Note: This is a legacy field. Use organization roles for more fine-grained permissions.
	// See: https://docs.github.com/en/rest/teams/teams#create-a-team
	Permission *string `json:"permission,omitempty"`
	// NotificationSetting controls whether team members receive notifications for the team.
	// - "notifications_disabled": No one receives notifications.
	// - "notifications_enabled": Everyone receives notifications when the team is @mentioned.
	// See: https://docs.github.com/en/rest/teams/teams#create-a-team
	NotificationSetting *string `json:"notificationSetting,omitempty"`
	// OrganizationRoles is a list of organization role names to assign to this team.
	// Organization roles define the permissions the team has within the organization.
	// If not specified, defaults to empty list.
	// Set to an empty list to remove all role assignments.
	// See: https://docs.github.com/en/rest/orgs/organization-roles
	OrganizationRoles []string `json:"organizationRoles,omitempty"`
	// OrganizationRefs is a list of Organization CRDs that this team belongs to.
	// The team will be created or updated in all referenced organizations.
	// Removing an organization from this list will delete the team from that organization
	// while preserving it in other organizations.
	OrganizationRefs []OrganizationRefApplyConfiguration `json:"organizationRefs,omitempty"`
}

// TeamSpecApplyConfiguration constructs a declarative configuration of the TeamSpec type for use with
// apply.
func TeamSpec() *TeamSpecApplyConfiguration {
	return &TeamSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *TeamSpecApplyConfiguration) WithName(value string) *TeamSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithMembers adds the given value to the Members field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Members field.
func (b *TeamSpecApplyConfiguration) WithMembers(values ...string) *TeamSpecApplyConfiguration {
	for i := range values {
		b.Members = append(b.Members, values[i])
	}
	return b
}

// WithIDPGroup sets the IDPGroup field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IDPGroup field is set to the value of the last call.
func (b *TeamSpecApplyConfiguration) WithIDPGroup(value string) *TeamSpecApplyConfiguration {
	b.IDPGroup = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *TeamSpecApplyConfiguration) WithDescription(value string) *TeamSpecApplyConfiguration {
	b.Description = &value
	return b
}

// WithPrivacy sets the Privacy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Privacy field is set to the value of the last call.
func (b *TeamSpecApplyConfiguration) WithPrivacy(value string) *TeamSpecApplyConfiguration {
	b.Privacy = &value
	return b
}

// WithPermission sets the Permission field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Permission field is set to the value of the last call.
func (b *TeamSpecApplyConfiguration) WithPermission(value string) *TeamSpecApplyConfiguration {
	b.Permission = &value
	return b
}

// WithNotificationSetting sets the NotificationSetting field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NotificationSetting field is set to the value of the last call.
func (b *TeamSpecApplyConfiguration) WithNotificationSetting(value string) *TeamSpecApplyConfiguration {
	b.NotificationSetting = &value
	return b
}

// WithOrganizationRoles adds the given value to the OrganizationRoles field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OrganizationRoles field.
func (b *TeamSpecApplyConfiguration) WithOrganizationRoles(values ...string) *TeamSpecApplyConfiguration {
	for i := range values {
		b.OrganizationRoles = append(b.OrganizationRoles, values[i])
	}
	return b
}

// WithOrganizationRefs adds the given value to the OrganizationRefs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OrganizationRefs field.
func (b *TeamSpecApplyConfiguration) WithOrganizationRefs(values ...*OrganizationRefApplyConfiguration) *TeamSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOrganizationRefs")
		}
		b.OrganizationRefs = append(b.OrganizationRefs, *values[i])
	}
	return b
}
