/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// WebhookPresetSpecApplyConfiguration represents a declarative configuration of the WebhookPresetSpec type for use
// with apply.
//
// EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
// NOTE: json tags are required.  Any new fields you add must have json tags for the fields to be serialized.
// WebhookPresetSpec defines the desired state of WebhookPreset.
// Webhooks allow external services to be notified when certain events occur in a repository.
// See: https://docs.github.com/en/rest/webhooks/repos
type WebhookPresetSpecApplyConfiguration struct {
	// PayloadURL is the URL that will receive the webhook POST requests.
	// Must be a publicly accessible HTTP or HTTPS endpoint.
	// GitHub will send HTTP POST requests to this URL when subscribed events occur.
	PayloadURL *string `json:"payloadUrl,omitempty"`
	// Secret is a reference to a Kubernetes Secret containing the webhook secret.
	// The webhook secret is used by GitHub to sign webhook payloads.
	// Your service can verify this signature to ensure the request came from GitHub.
	// This field takes precedence over SecretValue if both are provided.
	// See: https://docs.github.com/en/webhooks/using-webhooks/validating-webhook-deliveries
	Secret *WebhookPresetSecretSpecApplyConfiguration `json:"secret,omitempty"`
	// SecretValue is the plaintext value of the webhook secret.
	// Use this for simple cases, but Secret (referencing a Kubernetes Secret) is more secure.
	// If both Secret and SecretValue are provided, Secret takes precedence.
	SecretValue *string `json:"secretValue,omitempty"`
	// ContentType specifies the format of the webhook payload.
	// - "json": Send payload as application/json (recommended)
	// - "form": Send payload as application/x-www-form-urlencoded
	// See: https://docs.github.com/en/webhooks/webhook-events-and-payloads
	ContentType *string `json:"contentType,omitempty"`
	// Active determines whether the webhook is active and will send events.
	// Set to false to temporarily disable the webhook without deleting it.
	Active *bool `json:"active,omitempty"`
	// Events is a list of GitHub event types that trigger this webhook.
	// If empty, the webhook subscribes to all events ("*").
	// Common events include "push", "pull_request", "issues", "release".
	// See: https://docs.github.com/en/webhooks/webhook-events-and-payloads
	Events []string `json:"events,omitempty"`
	// SSLVerify enables SSL certificate verification for the webhook endpoint.
	// When true, GitHub verifies the SSL certificate of the PayloadURL.
	// Disable only for testing with self-signed certificates; always enable in production.
	SSLVerify *bool `json:"sslVerify,omitempty"`
}

// WebhookPresetSpecApplyConfiguration constructs a declarative configuration of the WebhookPresetSpec type for use with
// apply.
func WebhookPresetSpec() *WebhookPresetSpecApplyConfiguration {
	return &WebhookPresetSpecApplyConfiguration{}
}

// WithPayloadURL sets the PayloadURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PayloadURL field is set to the value of the last call.
func (b *WebhookPresetSpecApplyConfiguration) WithPayloadURL(value string) *WebhookPresetSpecApplyConfiguration {
	b.PayloadURL = &value
	return b
}

// WithSecret sets the Secret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Secret field is set to the value of the last call.
func (b *WebhookPresetSpecApplyConfiguration) WithSecret(value *WebhookPresetSecretSpecApplyConfiguration) *WebhookPresetSpecApplyConfiguration {
	b.Secret = value
	return b
}

// WithSecretValue sets the SecretValue field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretValue field is set to the value of the last call.
func (b *WebhookPresetSpecApplyConfiguration) WithSecretValue(value string) *WebhookPresetSpecApplyConfiguration {
	b.SecretValue = &value
	return b
}

// WithContentType sets the ContentType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ContentType field is set to the value of the last call.
func (b *WebhookPresetSpecApplyConfiguration) WithContentType(value string) *WebhookPresetSpecApplyConfiguration {
	b.ContentType = &value
	return b
}

// WithActive sets the Active field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Active field is set to the value of the last call.
func (b *WebhookPresetSpecApplyConfiguration) WithActive(value bool) *WebhookPresetSpecApplyConfiguration {
	b.Active = &value
	return b
}

// WithEvents adds the given value to the Events field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Events field.
func (b *WebhookPresetSpecApplyConfiguration) WithEvents(values ...string) *WebhookPresetSpecApplyConfiguration {
	for i := range values {
		b.Events = append(b.Events, values[i])
	}
	return b
}

// WithSSLVerify sets the SSLVerify field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SSLVerify field is set to the value of the last call.
func (b *WebhookPresetSpecApplyConfiguration) WithSSLVerify(value bool) *WebhookPresetSpecApplyConfiguration {
	b.SSLVerify = &value
	return b
}
