/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

// WorkflowsRuleApplyConfiguration represents a declarative configuration of the WorkflowsRule type for use
// with apply.
//
// WorkflowsRule defines required workflow rules that must pass before merging.
// Workflows are GitHub Actions workflows that are required to run and pass.
// This rule type is only effective for organization-level rulesets and is ignored
// when the preset is applied at the repository level.
// See: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-rulesets/available-rules-for-rulesets#require-workflows-to-pass-before-merging
type WorkflowsRuleApplyConfiguration struct {
	// DoNotEnforceOnCreate disables enforcement of this rule for newly created refs.
	// When true, the workflow requirement is not enforced on the first push creating the ref.
	DoNotEnforceOnCreate *bool `json:"doNotEnforceOnCreate,omitempty"`
	// Workflows lists the required workflows that must pass.
	Workflows []RuleWorkflowApplyConfiguration `json:"workflows,omitempty"`
}

// WorkflowsRuleApplyConfiguration constructs a declarative configuration of the WorkflowsRule type for use with
// apply.
func WorkflowsRule() *WorkflowsRuleApplyConfiguration {
	return &WorkflowsRuleApplyConfiguration{}
}

// WithDoNotEnforceOnCreate sets the DoNotEnforceOnCreate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DoNotEnforceOnCreate field is set to the value of the last call.
func (b *WorkflowsRuleApplyConfiguration) WithDoNotEnforceOnCreate(value bool) *WorkflowsRuleApplyConfiguration {
	b.DoNotEnforceOnCreate = &value
	return b
}

// WithWorkflows adds the given value to the Workflows field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Workflows field.
func (b *WorkflowsRuleApplyConfiguration) WithWorkflows(values ...*RuleWorkflowApplyConfiguration) *WorkflowsRuleApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithWorkflows")
		}
		b.Workflows = append(b.Workflows, *values[i])
	}
	return b
}
