// post-helmify patches the Helm chart generated by helmify to apply
// customizations that helmify cannot produce natively.
//
// It performs the following transformations:
//   - Replaces helmify-generated templates with pre-built versions from hack/post-helmify/templates/
//   - Patches deployment.yaml with custom Helm helpers for env vars and labels
//   - Patches values.yaml to introduce watchedNamespaces list and remove kustomize artifacts
//   - Adds namespace templating to RBAC and webhook resources
//
// Usage:
//
//	go run ./hack/post-helmify [chart-path]
//
// If chart-path is not specified, defaults to "./chart".
package main

import (
	"fmt"
	"os"
)

func main() {
	chartPath := "./chart"
	if len(os.Args) > 1 {
		chartPath = os.Args[1]
	}

	cfg := Config{
		ChartPath:      chartPath,
		TemplateSrcDir: "hack/post-helmify/templates",
	}

	if err := run(cfg); err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "ERROR: %v\n", err)
		os.Exit(1)
	}
}

func run(cfg Config) error {
	steps := []struct {
		name string
		fn   func(Config) error
	}{
		{"copy envs configmap template", copyEnvsConfigmapTemplate},
		{"patch deployment podLabels", patchDeploymentPodLabels},
		{"patch deployment strategy", patchDeploymentStrategy},
		{"patch deployment preStop hook", patchDeploymentPreStop},
		{"patch deployment topologySpreadConstraints", patchDeploymentTopologySpread},
		{"patch serviceaccount secrets", patchServiceAccountSecrets},
		{"replace configMapRef name", replaceConfigMapRefName},
		{"replace WATCH_NAMESPACE value", replaceWatchNamespaceValue},
		{"copy manager-rbac template", copyManagerRBACTemplate},
		{"patch app-credentials RBAC namespace", patchAppCredentialsRBAC},
		{"template webhook namespaceSelector", templateWebhookNamespaceSelector},
		{"template APP_CREDENTIALS_SECRET_NAMESPACE", templateAppCredentialsEnv},
		{"patch values.yaml namespaces", patchValuesNamespaces},
		{"patch serviceaccount labels", patchServiceAccountLabels},
		{"patch values.yaml defaults", patchValuesDefaults},
		{"copy PDB template", copyPDBTemplate},
		{"add podDisruptionBudget to values.yaml", addPDBValues},
		{"add topologySpreadConstraints to values.yaml", addTopologySpreadValues},
		{"copy serving-cert template", copyServingCertTemplate},
		{"add servingCert to values.yaml", addServingCertValues},
	}

	for _, step := range steps {
		if err := step.fn(cfg); err != nil {
			return fmt.Errorf("%s: %w", step.name, err)
		}
		fmt.Printf("✓ %s\n", step.name)
	}

	fmt.Println("post-helmify completed")
	return nil
}

// Config holds paths used by the post-helmify transformations.
type Config struct {
	ChartPath      string
	TemplateSrcDir string
}

func (c Config) deployment() string     { return c.ChartPath + "/templates/deployment.yaml" }
func (c Config) serviceAccount() string { return c.ChartPath + "/templates/serviceaccount.yaml" }
func (c Config) managerRBAC() string    { return c.ChartPath + "/templates/manager-rbac.yaml" }
func (c Config) appCredsRBAC() string   { return c.ChartPath + "/templates/app-credentials-rbac.yaml" }
func (c Config) webhook() string {
	return c.ChartPath + "/templates/validating-webhook-configuration.yaml"
}
func (c Config) values() string         { return c.ChartPath + "/values.yaml" }
func (c Config) pdb() string            { return c.ChartPath + "/templates/poddisruptionbudget.yaml" }
func (c Config) pdbSrc() string         { return c.TemplateSrcDir + "/poddisruptionbudget.yaml" }
func (c Config) servingCertSrc() string { return c.TemplateSrcDir + "/serving-cert.yaml" }
func (c Config) managerRBACSrc() string { return c.TemplateSrcDir + "/manager-rbac.yaml" }
func (c Config) envsConfigmapSrc() string {
	return c.TemplateSrcDir + "/envs.configmap.yaml"
}
func (c Config) envsConfigmap() string {
	return c.ChartPath + "/templates/envs.configmap.yaml"
}
