//nolint:goconst // "selected" is a possible value in three different contexts (runner group visibility, allowed actions, enabled repositories), reusing one constant is misleading
package orgrec

import (
	"context"
	"maps"
	"slices"

	"github.com/Interhyp/git-hubby/api/v1alpha1"
	"github.com/Interhyp/git-hubby/internal/mapper"
	"github.com/Interhyp/git-hubby/internal/reconciler"
	"github.com/Interhyp/git-hubby/internal/utils"
	"github.com/google/go-github/v86/github"
	logPkg "sigs.k8s.io/controller-runtime/pkg/log"
)

const enabledReposNone = "none"

func (o *GitHubOrgReconciler) reconcileActionsSettings(ctx context.Context) error {
	log := logPkg.FromContext(ctx)
	log.V(1).Info("Reconciling organization GitHub actions configurations on GitHub")

	if reconciler.IsActionsDisabledForOrgSpec(o.Kubernetes.Resource) {
		err := o.disableActionsForGHOrg(ctx)
		if err != nil {
			return err
		}
		log.V(1).Info("Actions are disabled for org, skipping further reconciliation")
		return nil
	}

	reconciliations := []func(context.Context) error{
		o.reconcilePermissions,
		o.reconcileRetention,
		o.reconcileAllowedActions,
		o.reconcileDefaultWorkflowPermissions,
		o.reconcileSelfHostedRunnerSettings,
		o.reconcileRunnerGroups,
	}

	for _, reconciliation := range reconciliations {
		err := reconciliation(ctx)
		if err != nil {
			return err
		}
	}

	log.V(1).Info("Successfully reconciled organization GitHub actions configurations on GitHub")
	return nil
}

func (o *GitHubOrgReconciler) disableActionsForGHOrg(ctx context.Context) error {
	current, err := o.GitHub.Client.GetActionsPermissionsForOrg(ctx, o.GitHub.Resource)
	if err != nil {
		return err
	}
	if current.GetEnabledRepositories() != enabledReposNone {
		_, err = o.GitHub.Client.SetActionsPermissionsForOrg(ctx, o.GitHub.Resource, github.ActionsPermissions{EnabledRepositories: new(enabledReposNone)})
		return err
	}
	return nil
}

func (o *GitHubOrgReconciler) reconcileRunnerGroups(ctx context.Context) error {
	current, err := o.GitHub.Client.GetRunnerGroupsForOrg(ctx, o.GitHub.Resource)
	if err != nil {
		return err
	}
	repos, err := o.getReferencingK8sRepos(ctx)
	if err != nil {
		return err
	}
	// We are matching by name, thus changing the name in either github or k8s forces a delete + removal of all runners + recreate of the group.
	// This is the only solution, since renaming can happen in GitHub without the knowledge of the operator and we want to be able to reconcile to the desired state in that case.
	// As the ID of the group is not known beforehand and is generated by GitHub, we cannot rely on it for matching.
	expected := o.Kubernetes.Resource.Spec.ActionsSettings.RunnerGroups
	expectedByName := make(map[string]v1alpha1.RunnerGroup)
	for _, group := range expected {
		expectedByName[group.Name] = group
	}
	expectedSeen := make(map[string]any)

	for _, group := range current {
		matchingName, matchFound := expectedByName[group.GetName()]
		if matchFound {
			// update runner group properties if they differ
			if !mapper.EqualRunnerGroup(matchingName, group) {
				if _, err = o.GitHub.Client.UpdateRunnerGroupForOrg(ctx, o.GitHub.Resource, group.GetID(), mapper.MapRunnerGroupToUpdateRequest(matchingName)); err != nil {
					return err
				}
			}
			expectedSeen[matchingName.Name] = nil
			if matchingName.Visibility != nil && *matchingName.Visibility != "selected" {
				// if visibility is not "selected", the repository selection is not relevant,
				// thus we can skip the update call for the repository selection and also skip the check if it's in sync
				continue
			}
			err := o.updateSelectedRepositoriesForRunnerGroup(ctx, matchingName, repos, group)
			if err != nil {
				return err
			}
		} else {
			//  delete
			if err = o.GitHub.Client.DeleteRunnerGroupForOrg(ctx, o.GitHub.Resource, group.GetID()); err != nil {
				return err
			}
		}
	}
	for _, group := range expected {
		if _, hasBeenSeen := expectedSeen[group.Name]; !hasBeenSeen {
			if _, err = o.GitHub.Client.CreateRunnerGroupForOrg(ctx, o.GitHub.Resource, mapper.MapRunnerGroupToCreateRequest(group, repos.Items)); err != nil {
				return err
			}
		}
	}

	return nil
}

func (o *GitHubOrgReconciler) updateSelectedRepositoriesForRunnerGroup(ctx context.Context, matchingName v1alpha1.RunnerGroup, repos v1alpha1.RepositoryList, group *github.RunnerGroup) error {
	expectedSelectedRepositoryIDs := mapper.GetSelectedRepositoryIDsForRunnerGroup(matchingName, repos.Items)
	currentSelectedRepositories, err := o.GitHub.Client.GetSelectedRepositoriesForRunnerGroup(ctx, o.GitHub.Resource, group.GetID())
	if err != nil {
		return err
	}
	if !mapper.EqualRepositoryIDs(expectedSelectedRepositoryIDs, currentSelectedRepositories) {
		if err = o.GitHub.Client.SetSelectedRepositoriesForRunnerGroup(ctx, o.GitHub.Resource, group.GetID(), expectedSelectedRepositoryIDs); err != nil {
			return err
		}
	}
	return nil
}

func containsSameIDs(current []*github.Repository, ds map[int64]any) bool {
	if len(current) != len(ds) {
		return false
	}
	for _, repo := range current {
		// we assume that GitHub does not return duplicate IDs
		_, found := ds[repo.GetID()]
		if !found {
			return false
		}
	}
	return true
}

func (o *GitHubOrgReconciler) reconcilePermissions(ctx context.Context) error {
	current, err := o.GitHub.Client.GetActionsPermissionsForOrg(ctx, o.GitHub.Resource)
	if err != nil {
		return err
	}

	expected := github.ActionsPermissions{
		EnabledRepositories: o.Kubernetes.Resource.Spec.ActionsSettings.EnabledRepositories, // is not nil because we would have returned earlier as part of disabled check
		AllowedActions:      utils.WithDefaultAsPtr(o.Kubernetes.Resource.Spec.ActionsSettings.AllowedActions, "selected"),
		SHAPinningRequired:  utils.WithDefaultAsPtr(o.Kubernetes.Resource.Spec.ActionsSettings.ShaPinningRequired, false),
	}

	if !mapper.EqualActionsPermissions(&expected, current) {
		_, err = o.GitHub.Client.SetActionsPermissionsForOrg(ctx, o.GitHub.Resource, expected)
		return err
	}
	if expected.GetEnabledRepositories() == "selected" {
		return o.reconcileActionsEnabledRepositories(ctx)
	}
	return nil
}

func (o *GitHubOrgReconciler) reconcileActionsEnabledRepositories(ctx context.Context) error {
	repos, err := o.getReferencingK8sRepos(ctx)
	if err != nil {
		return err
	}
	current, err := o.GitHub.Client.GetActionsEnabledRepositoriesForOrg(ctx, o.GitHub.Resource)
	if err != nil {
		return err
	}
	expectedIDs := make(map[int64]any)
	for _, k8sRepo := range repos.Items {
		if utils.WithDefault(k8sRepo.Spec.ActionsEnabled, true) && k8sRepo.Status.ID != nil {
			expectedIDs[*k8sRepo.Status.ID] = nil
		}
	}
	if !containsSameIDs(current, expectedIDs) {
		if err = o.GitHub.Client.SetActionsEnabledRepositoriesForOrg(ctx, o.GitHub.Resource, slices.Collect(maps.Keys(expectedIDs))); err != nil {
			return err
		}
	}
	return nil
}

func (o *GitHubOrgReconciler) reconcileRetention(ctx context.Context) error {
	current, err := o.GitHub.Client.GetActionsRetentionForOrg(ctx, o.GitHub.Resource)
	if err != nil {
		return err
	}

	expected := *utils.WithDefaultAsPtr(o.Kubernetes.Resource.Spec.ActionsSettings.ArtifactAndLogRetentionDays, 400)

	if expected != current.GetDays() {
		err = o.GitHub.Client.SetActionsRetentionForOrg(ctx, o.GitHub.Resource, expected)
		return err
	}
	return nil
}

func (o *GitHubOrgReconciler) reconcileAllowedActions(ctx context.Context) error {
	if reconciler.IsActionsDisabledForOrgSpec(o.Kubernetes.Resource) {
		// If Actions are disabled for all repositories, skip reconciling allowed actions
		return nil
	}

	allowedActions := o.Kubernetes.Resource.Spec.ActionsSettings.AllowedActions
	if allowedActions == nil || *allowedActions == "all" {
		return nil
	}

	current, err := o.GitHub.Client.GetActionsAllowedForOrg(ctx, o.GitHub.Resource)
	if err != nil {
		return err
	}

	expected := github.ActionsAllowed{
		GithubOwnedAllowed: new(false),
		VerifiedAllowed:    new(false),
		PatternsAllowed:    make([]string, 0),
	}
	if o.Kubernetes.Resource.Spec.ActionsSettings.SelectedAllowedActions != nil {
		expected = github.ActionsAllowed{
			GithubOwnedAllowed: utils.WithDefaultAsPtr(o.Kubernetes.Resource.Spec.ActionsSettings.SelectedAllowedActions.GitHubOwnedAllowed, expected.GetGithubOwnedAllowed()),
			VerifiedAllowed:    utils.WithDefaultAsPtr(o.Kubernetes.Resource.Spec.ActionsSettings.SelectedAllowedActions.VerifiedAllowed, expected.GetVerifiedAllowed()),
			PatternsAllowed:    utils.WithEmptyDefault(o.Kubernetes.Resource.Spec.ActionsSettings.SelectedAllowedActions.PatternsAllowed),
		}
	}

	if !mapper.EqualActionsAllowed(&expected, current) {
		_, err = o.GitHub.Client.SetActionsAllowedForOrg(ctx, o.GitHub.Resource, expected)
		return err
	}

	return nil
}

func (o *GitHubOrgReconciler) reconcileDefaultWorkflowPermissions(ctx context.Context) error {
	current, err := o.GitHub.Client.GetActionsDefaultWorkflowPermissionsForOrg(ctx, o.GitHub.Resource)
	if err != nil {
		return err
	}
	expected := github.DefaultWorkflowPermissionOrganization{
		DefaultWorkflowPermissions:   utils.WithDefaultAsPtr(o.Kubernetes.Resource.Spec.ActionsSettings.DefaultWorkflowPermissions, "read"),
		CanApprovePullRequestReviews: utils.WithDefaultAsPtr(o.Kubernetes.Resource.Spec.ActionsSettings.CanApprovePullRequestReviews, false),
	}
	if !mapper.EqualDefaultWorkflowPermissions(&expected, current) {
		_, err = o.GitHub.Client.SetActionsDefaultWorkflowPermissionsForOrg(ctx, o.GitHub.Resource, expected)
		if err != nil {
			return err
		}
	}
	return nil
}

func (o *GitHubOrgReconciler) reconcileSelfHostedRunnerSettings(ctx context.Context) error {
	current, err := o.GitHub.Client.GetSelfHostedRunnersSettingsForOrg(ctx, o.GitHub.Resource)
	if err != nil {
		return err
	}

	if current.GetEnabledRepositories() != enabledReposNone {
		err = o.GitHub.Client.SetSelfHostedRunnersSettingsForOrg(ctx, o.GitHub.Resource, github.SelfHostedRunnersSettingsOrganizationOpt{
			EnabledRepositories: new(enabledReposNone),
		})
		if err != nil {
			return err
		}
	}
	return nil
}
