apiVersion: github.interhyp.de/v1alpha1
kind: Repository
metadata:
  labels:
    app.kubernetes.io/name: git-hubby
    app.kubernetes.io/managed-by: kustomize
  name: repository-sample
spec:
  organizationRef:
    name: sample-org
  webhookPresets:
    - name: webhookpreset-sample
