//go:build !ignore_autogenerated

<<<<<<< HEAD
=======
/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

>>>>>>> tmp-original-30-06-26-04-09
// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *About) DeepCopyInto(out *About) {
	*out = *in
	if in.Topics != nil {
		in, out := &in.Topics, &out.Topics
		*out = make([]Topic, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new About.
func (in *About) DeepCopy() *About {
	if in == nil {
		return nil
	}
	out := new(About)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionsSettings) DeepCopyInto(out *ActionsSettings) {
	*out = *in
	if in.EnabledRepositories != nil {
		in, out := &in.EnabledRepositories, &out.EnabledRepositories
		*out = new(string)
		**out = **in
	}
	if in.AllowedActions != nil {
		in, out := &in.AllowedActions, &out.AllowedActions
		*out = new(string)
		**out = **in
	}
	if in.SelectedAllowedActions != nil {
		in, out := &in.SelectedAllowedActions, &out.SelectedAllowedActions
		*out = new(SelectedAllowedActions)
		(*in).DeepCopyInto(*out)
	}
	if in.ShaPinningRequired != nil {
		in, out := &in.ShaPinningRequired, &out.ShaPinningRequired
		*out = new(bool)
		**out = **in
	}
	if in.DefaultWorkflowPermissions != nil {
		in, out := &in.DefaultWorkflowPermissions, &out.DefaultWorkflowPermissions
		*out = new(string)
		**out = **in
	}
	if in.CanApprovePullRequestReviews != nil {
		in, out := &in.CanApprovePullRequestReviews, &out.CanApprovePullRequestReviews
		*out = new(bool)
		**out = **in
	}
	if in.ArtifactAndLogRetentionDays != nil {
		in, out := &in.ArtifactAndLogRetentionDays, &out.ArtifactAndLogRetentionDays
		*out = new(int)
		**out = **in
	}
	if in.RunnerGroups != nil {
		in, out := &in.RunnerGroups, &out.RunnerGroups
		*out = make([]RunnerGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionsSettings.
func (in *ActionsSettings) DeepCopy() *ActionsSettings {
	if in == nil {
		return nil
	}
	out := new(ActionsSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttachableCodeSecurityConfigurationRef) DeepCopyInto(out *AttachableCodeSecurityConfigurationRef) {
	*out = *in
	if in.AttachmentScope != nil {
		in, out := &in.AttachmentScope, &out.AttachmentScope
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttachableCodeSecurityConfigurationRef.
func (in *AttachableCodeSecurityConfigurationRef) DeepCopy() *AttachableCodeSecurityConfigurationRef {
	if in == nil {
		return nil
	}
	out := new(AttachableCodeSecurityConfigurationRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Autolink) DeepCopyInto(out *Autolink) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Autolink.
func (in *Autolink) DeepCopy() *Autolink {
	if in == nil {
		return nil
	}
	out := new(Autolink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutolinksPreset) DeepCopyInto(out *AutolinksPreset) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutolinksPreset.
func (in *AutolinksPreset) DeepCopy() *AutolinksPreset {
	if in == nil {
		return nil
	}
	out := new(AutolinksPreset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutolinksPreset) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutolinksPresetList) DeepCopyInto(out *AutolinksPresetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AutolinksPreset, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutolinksPresetList.
func (in *AutolinksPresetList) DeepCopy() *AutolinksPresetList {
	if in == nil {
		return nil
	}
	out := new(AutolinksPresetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutolinksPresetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutolinksPresetSpec) DeepCopyInto(out *AutolinksPresetSpec) {
	*out = *in
	if in.AutolinkList != nil {
		in, out := &in.AutolinkList, &out.AutolinkList
		*out = make([]Autolink, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutolinksPresetSpec.
func (in *AutolinksPresetSpec) DeepCopy() *AutolinksPresetSpec {
	if in == nil {
		return nil
	}
	out := new(AutolinksPresetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutolinksPresetStatus) DeepCopyInto(out *AutolinksPresetStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutolinksPresetStatus.
func (in *AutolinksPresetStatus) DeepCopy() *AutolinksPresetStatus {
	if in == nil {
		return nil
	}
	out := new(AutolinksPresetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BypassReviewer) DeepCopyInto(out *BypassReviewer) {
	*out = *in
	if in.ReviewerId != nil {
		in, out := &in.ReviewerId, &out.ReviewerId
		*out = new(int64)
		**out = **in
	}
	if in.ReviewerName != nil {
		in, out := &in.ReviewerName, &out.ReviewerName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BypassReviewer.
func (in *BypassReviewer) DeepCopy() *BypassReviewer {
	if in == nil {
		return nil
	}
	out := new(BypassReviewer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeScanningDefaultSetupOptions) DeepCopyInto(out *CodeScanningDefaultSetupOptions) {
	*out = *in
	if in.RunnerLabel != nil {
		in, out := &in.RunnerLabel, &out.RunnerLabel
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeScanningDefaultSetupOptions.
func (in *CodeScanningDefaultSetupOptions) DeepCopy() *CodeScanningDefaultSetupOptions {
	if in == nil {
		return nil
	}
	out := new(CodeScanningDefaultSetupOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeScanningOptions) DeepCopyInto(out *CodeScanningOptions) {
	*out = *in
	if in.AllowAdvanced != nil {
		in, out := &in.AllowAdvanced, &out.AllowAdvanced
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeScanningOptions.
func (in *CodeScanningOptions) DeepCopy() *CodeScanningOptions {
	if in == nil {
		return nil
	}
	out := new(CodeScanningOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeSecurityConfiguration) DeepCopyInto(out *CodeSecurityConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeSecurityConfiguration.
func (in *CodeSecurityConfiguration) DeepCopy() *CodeSecurityConfiguration {
	if in == nil {
		return nil
	}
	out := new(CodeSecurityConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CodeSecurityConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeSecurityConfigurationList) DeepCopyInto(out *CodeSecurityConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CodeSecurityConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeSecurityConfigurationList.
func (in *CodeSecurityConfigurationList) DeepCopy() *CodeSecurityConfigurationList {
	if in == nil {
		return nil
	}
	out := new(CodeSecurityConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CodeSecurityConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeSecurityConfigurationRef) DeepCopyInto(out *CodeSecurityConfigurationRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeSecurityConfigurationRef.
func (in *CodeSecurityConfigurationRef) DeepCopy() *CodeSecurityConfigurationRef {
	if in == nil {
		return nil
	}
	out := new(CodeSecurityConfigurationRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeSecurityConfigurationSpec) DeepCopyInto(out *CodeSecurityConfigurationSpec) {
	*out = *in
	if in.AdvancedSecurity != nil {
		in, out := &in.AdvancedSecurity, &out.AdvancedSecurity
		*out = new(string)
		**out = **in
	}
	if in.DependencyGraph != nil {
		in, out := &in.DependencyGraph, &out.DependencyGraph
		*out = new(string)
		**out = **in
	}
	if in.DependencyGraphAutosubmitAction != nil {
		in, out := &in.DependencyGraphAutosubmitAction, &out.DependencyGraphAutosubmitAction
		*out = new(string)
		**out = **in
	}
	if in.DependencyGraphAutosubmitActionOptions != nil {
		in, out := &in.DependencyGraphAutosubmitActionOptions, &out.DependencyGraphAutosubmitActionOptions
		*out = new(DependencyGraphAutosubmitActionOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.DependabotAlerts != nil {
		in, out := &in.DependabotAlerts, &out.DependabotAlerts
		*out = new(string)
		**out = **in
	}
	if in.DependabotSecurityUpdates != nil {
		in, out := &in.DependabotSecurityUpdates, &out.DependabotSecurityUpdates
		*out = new(string)
		**out = **in
	}
	if in.CodeScanningDefaultSetup != nil {
		in, out := &in.CodeScanningDefaultSetup, &out.CodeScanningDefaultSetup
		*out = new(string)
		**out = **in
	}
	if in.CodeScanningDefaultSetupOptions != nil {
		in, out := &in.CodeScanningDefaultSetupOptions, &out.CodeScanningDefaultSetupOptions
		*out = new(CodeScanningDefaultSetupOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.CodeScanningDelegatedAlertDismissal != nil {
		in, out := &in.CodeScanningDelegatedAlertDismissal, &out.CodeScanningDelegatedAlertDismissal
		*out = new(string)
		**out = **in
	}
	if in.CodeScanningOptions != nil {
		in, out := &in.CodeScanningOptions, &out.CodeScanningOptions
		*out = new(CodeScanningOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.CodeSecurity != nil {
		in, out := &in.CodeSecurity, &out.CodeSecurity
		*out = new(string)
		**out = **in
	}
	if in.SecretScanning != nil {
		in, out := &in.SecretScanning, &out.SecretScanning
		*out = new(string)
		**out = **in
	}
	if in.SecretScanningPushProtection != nil {
		in, out := &in.SecretScanningPushProtection, &out.SecretScanningPushProtection
		*out = new(string)
		**out = **in
	}
	if in.SecretScanningValidityChecks != nil {
		in, out := &in.SecretScanningValidityChecks, &out.SecretScanningValidityChecks
		*out = new(string)
		**out = **in
	}
	if in.SecretScanningNonProviderPatterns != nil {
		in, out := &in.SecretScanningNonProviderPatterns, &out.SecretScanningNonProviderPatterns
		*out = new(string)
		**out = **in
	}
	if in.SecretScanningGenericSecrets != nil {
		in, out := &in.SecretScanningGenericSecrets, &out.SecretScanningGenericSecrets
		*out = new(string)
		**out = **in
	}
	if in.SecretScanningDelegatedAlertDismissal != nil {
		in, out := &in.SecretScanningDelegatedAlertDismissal, &out.SecretScanningDelegatedAlertDismissal
		*out = new(string)
		**out = **in
	}
	if in.SecretProtection != nil {
		in, out := &in.SecretProtection, &out.SecretProtection
		*out = new(string)
		**out = **in
	}
	if in.PrivateVulnerabilityReporting != nil {
		in, out := &in.PrivateVulnerabilityReporting, &out.PrivateVulnerabilityReporting
		*out = new(string)
		**out = **in
	}
	if in.Enforcement != nil {
		in, out := &in.Enforcement, &out.Enforcement
		*out = new(string)
		**out = **in
	}
	if in.SecretScanningDelegatedBypass != nil {
		in, out := &in.SecretScanningDelegatedBypass, &out.SecretScanningDelegatedBypass
		*out = new(string)
		**out = **in
	}
	if in.SecretScanningDelegatedBypassOptions != nil {
		in, out := &in.SecretScanningDelegatedBypassOptions, &out.SecretScanningDelegatedBypassOptions
		*out = new(SecretScanningDelegatedBypassOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.DefaultForNewRepos != nil {
		in, out := &in.DefaultForNewRepos, &out.DefaultForNewRepos
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeSecurityConfigurationSpec.
func (in *CodeSecurityConfigurationSpec) DeepCopy() *CodeSecurityConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(CodeSecurityConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeSecurityConfigurationStatus) DeepCopyInto(out *CodeSecurityConfigurationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeSecurityConfigurationStatus.
func (in *CodeSecurityConfigurationStatus) DeepCopy() *CodeSecurityConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(CodeSecurityConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CopilotCodeReviewRule) DeepCopyInto(out *CopilotCodeReviewRule) {
	*out = *in
	if in.ReviewOnPush != nil {
		in, out := &in.ReviewOnPush, &out.ReviewOnPush
		*out = new(bool)
		**out = **in
	}
	if in.ReviewDraftPullRequests != nil {
		in, out := &in.ReviewDraftPullRequests, &out.ReviewDraftPullRequests
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CopilotCodeReviewRule.
func (in *CopilotCodeReviewRule) DeepCopy() *CopilotCodeReviewRule {
	if in == nil {
		return nil
	}
	out := new(CopilotCodeReviewRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomPropertyValue) DeepCopyInto(out *CustomPropertyValue) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomPropertyValue.
func (in *CustomPropertyValue) DeepCopy() *CustomPropertyValue {
	if in == nil {
		return nil
	}
	out := new(CustomPropertyValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependencyGraphAutosubmitActionOptions) DeepCopyInto(out *DependencyGraphAutosubmitActionOptions) {
	*out = *in
	if in.LabeledRunners != nil {
		in, out := &in.LabeledRunners, &out.LabeledRunners
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencyGraphAutosubmitActionOptions.
func (in *DependencyGraphAutosubmitActionOptions) DeepCopy() *DependencyGraphAutosubmitActionOptions {
	if in == nil {
		return nil
	}
	out := new(DependencyGraphAutosubmitActionOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeployKey) DeepCopyInto(out *DeployKey) {
	*out = *in
	if in.ReadOnly != nil {
		in, out := &in.ReadOnly, &out.ReadOnly
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeployKey.
func (in *DeployKey) DeepCopy() *DeployKey {
	if in == nil {
		return nil
	}
	out := new(DeployKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubAppConfig) DeepCopyInto(out *GitHubAppConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubAppConfig.
func (in *GitHubAppConfig) DeepCopy() *GitHubAppConfig {
	if in == nil {
		return nil
	}
	out := new(GitHubAppConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubAppCredentials) DeepCopyInto(out *GitHubAppCredentials) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubAppCredentials.
func (in *GitHubAppCredentials) DeepCopy() *GitHubAppCredentials {
	if in == nil {
		return nil
	}
	out := new(GitHubAppCredentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MergeStrategy) DeepCopyInto(out *MergeStrategy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MergeStrategy.
func (in *MergeStrategy) DeepCopy() *MergeStrategy {
	if in == nil {
		return nil
	}
	out := new(MergeStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrgCustomProperty) DeepCopyInto(out *OrgCustomProperty) {
	*out = *in
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = new(bool)
		**out = **in
	}
	if in.DefaultValue != nil {
		in, out := &in.DefaultValue, &out.DefaultValue
		*out = new(OrgCustomPropertyDefaultValue)
		(*in).DeepCopyInto(*out)
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.AllowedValues != nil {
		in, out := &in.AllowedValues, &out.AllowedValues
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrgCustomProperty.
func (in *OrgCustomProperty) DeepCopy() *OrgCustomProperty {
	if in == nil {
		return nil
	}
	out := new(OrgCustomProperty)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrgCustomPropertyDefaultValue) DeepCopyInto(out *OrgCustomPropertyDefaultValue) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrgCustomPropertyDefaultValue.
func (in *OrgCustomPropertyDefaultValue) DeepCopy() *OrgCustomPropertyDefaultValue {
	if in == nil {
		return nil
	}
	out := new(OrgCustomPropertyDefaultValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Organization) DeepCopyInto(out *Organization) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Organization.
func (in *Organization) DeepCopy() *Organization {
	if in == nil {
		return nil
	}
	out := new(Organization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Organization) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationList) DeepCopyInto(out *OrganizationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Organization, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationList.
func (in *OrganizationList) DeepCopy() *OrganizationList {
	if in == nil {
		return nil
	}
	out := new(OrganizationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OrganizationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationRef) DeepCopyInto(out *OrganizationRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationRef.
func (in *OrganizationRef) DeepCopy() *OrganizationRef {
	if in == nil {
		return nil
	}
	out := new(OrganizationRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationSpec) DeepCopyInto(out *OrganizationSpec) {
	*out = *in
	if in.GitHubAppInstallationId != nil {
		in, out := &in.GitHubAppInstallationId, &out.GitHubAppInstallationId
		*out = new(int64)
		**out = **in
	}
	if in.GitHubAppConfig != nil {
		in, out := &in.GitHubAppConfig, &out.GitHubAppConfig
		*out = new(GitHubAppConfig)
		**out = **in
	}
	if in.CustomProperties != nil {
		in, out := &in.CustomProperties, &out.CustomProperties
		*out = make([]OrgCustomProperty, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.ActionsSettings.DeepCopyInto(&out.ActionsSettings)
	if in.CodeSecurityConfigurations != nil {
		in, out := &in.CodeSecurityConfigurations, &out.CodeSecurityConfigurations
		*out = make([]AttachableCodeSecurityConfigurationRef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RulesetPresetList != nil {
		in, out := &in.RulesetPresetList, &out.RulesetPresetList
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationSpec.
func (in *OrganizationSpec) DeepCopy() *OrganizationSpec {
	if in == nil {
		return nil
	}
	out := new(OrganizationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrganizationStatus) DeepCopyInto(out *OrganizationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ObservedSubResourceGenerations != nil {
		in, out := &in.ObservedSubResourceGenerations, &out.ObservedSubResourceGenerations
		*out = make(map[string]int64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrganizationStatus.
func (in *OrganizationStatus) DeepCopy() *OrganizationStatus {
	if in == nil {
		return nil
	}
	out := new(OrganizationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatternRule) DeepCopyInto(out *PatternRule) {
	*out = *in
	if in.Negate != nil {
		in, out := &in.Negate, &out.Negate
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatternRule.
func (in *PatternRule) DeepCopy() *PatternRule {
	if in == nil {
		return nil
	}
	out := new(PatternRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PullRequestRule) DeepCopyInto(out *PullRequestRule) {
	*out = *in
	if in.AllowedMergeMethods != nil {
		in, out := &in.AllowedMergeMethods, &out.AllowedMergeMethods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DismissStaleReviewsOnPush != nil {
		in, out := &in.DismissStaleReviewsOnPush, &out.DismissStaleReviewsOnPush
		*out = new(bool)
		**out = **in
	}
	if in.RequireCodeOwnerReviews != nil {
		in, out := &in.RequireCodeOwnerReviews, &out.RequireCodeOwnerReviews
		*out = new(bool)
		**out = **in
	}
	if in.RequireLastPushApproval != nil {
		in, out := &in.RequireLastPushApproval, &out.RequireLastPushApproval
		*out = new(bool)
		**out = **in
	}
	if in.RequiredReviewThreadResolution != nil {
		in, out := &in.RequiredReviewThreadResolution, &out.RequiredReviewThreadResolution
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PullRequestRule.
func (in *PullRequestRule) DeepCopy() *PullRequestRule {
	if in == nil {
		return nil
	}
	out := new(PullRequestRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RefNameCondition) DeepCopyInto(out *RefNameCondition) {
	*out = *in
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RefNameCondition.
func (in *RefNameCondition) DeepCopy() *RefNameCondition {
	if in == nil {
		return nil
	}
	out := new(RefNameCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Repository) DeepCopyInto(out *Repository) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Repository.
func (in *Repository) DeepCopy() *Repository {
	if in == nil {
		return nil
	}
	out := new(Repository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Repository) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryList) DeepCopyInto(out *RepositoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Repository, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryList.
func (in *RepositoryList) DeepCopy() *RepositoryList {
	if in == nil {
		return nil
	}
	out := new(RepositoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RepositoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryNameCondition) DeepCopyInto(out *RepositoryNameCondition) {
	*out = *in
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Protected != nil {
		in, out := &in.Protected, &out.Protected
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryNameCondition.
func (in *RepositoryNameCondition) DeepCopy() *RepositoryNameCondition {
	if in == nil {
		return nil
	}
	out := new(RepositoryNameCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryPropertyCondition) DeepCopyInto(out *RepositoryPropertyCondition) {
	*out = *in
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = make([]RepositoryPropertyTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = make([]RepositoryPropertyTarget, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryPropertyCondition.
func (in *RepositoryPropertyCondition) DeepCopy() *RepositoryPropertyCondition {
	if in == nil {
		return nil
	}
	out := new(RepositoryPropertyCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryPropertyTarget) DeepCopyInto(out *RepositoryPropertyTarget) {
	*out = *in
	if in.PropertyValues != nil {
		in, out := &in.PropertyValues, &out.PropertyValues
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryPropertyTarget.
func (in *RepositoryPropertyTarget) DeepCopy() *RepositoryPropertyTarget {
	if in == nil {
		return nil
	}
	out := new(RepositoryPropertyTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositorySpec) DeepCopyInto(out *RepositorySpec) {
	*out = *in
	if in.CustomProperties != nil {
		in, out := &in.CustomProperties, &out.CustomProperties
		*out = make([]CustomPropertyValue, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HasIssues != nil {
		in, out := &in.HasIssues, &out.HasIssues
		*out = new(bool)
		**out = **in
	}
	if in.HasProjects != nil {
		in, out := &in.HasProjects, &out.HasProjects
		*out = new(bool)
		**out = **in
	}
	if in.HasWiki != nil {
		in, out := &in.HasWiki, &out.HasWiki
		*out = new(bool)
		**out = **in
	}
	if in.HasDownloads != nil {
		in, out := &in.HasDownloads, &out.HasDownloads
		*out = new(bool)
		**out = **in
	}
	if in.IsTemplate != nil {
		in, out := &in.IsTemplate, &out.IsTemplate
		*out = new(bool)
		**out = **in
	}
	if in.AllowedMergeStrategies != nil {
		in, out := &in.AllowedMergeStrategies, &out.AllowedMergeStrategies
		*out = make([]MergeStrategy, len(*in))
		copy(*out, *in)
	}
	if in.DeleteBranchOnMerge != nil {
		in, out := &in.DeleteBranchOnMerge, &out.DeleteBranchOnMerge
		*out = new(bool)
		**out = **in
	}
	in.About.DeepCopyInto(&out.About)
	if in.Archived != nil {
		in, out := &in.Archived, &out.Archived
		*out = new(bool)
		**out = **in
	}
	if in.ActionsEnabled != nil {
		in, out := &in.ActionsEnabled, &out.ActionsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.AccessLevelForExternalWorkflows != nil {
		in, out := &in.AccessLevelForExternalWorkflows, &out.AccessLevelForExternalWorkflows
		*out = new(string)
		**out = **in
	}
	if in.AvailableActionsRunnerGroups != nil {
		in, out := &in.AvailableActionsRunnerGroups, &out.AvailableActionsRunnerGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.OrganizationRef = in.OrganizationRef
	if in.RulesetPresetList != nil {
		in, out := &in.RulesetPresetList, &out.RulesetPresetList
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.WebhookPresetList != nil {
		in, out := &in.WebhookPresetList, &out.WebhookPresetList
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.WebhookIgnorePresetsList != nil {
		in, out := &in.WebhookIgnorePresetsList, &out.WebhookIgnorePresetsList
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.AutolinksPresetList != nil {
		in, out := &in.AutolinksPresetList, &out.AutolinksPresetList
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.DeployKeyList != nil {
		in, out := &in.DeployKeyList, &out.DeployKeyList
		*out = make([]DeployKey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AttachedCodeSecurityConfiguration != nil {
		in, out := &in.AttachedCodeSecurityConfiguration, &out.AttachedCodeSecurityConfiguration
		*out = new(CodeSecurityConfigurationRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositorySpec.
func (in *RepositorySpec) DeepCopy() *RepositorySpec {
	if in == nil {
		return nil
	}
	out := new(RepositorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepositoryStatus) DeepCopyInto(out *RepositoryStatus) {
	*out = *in
	if in.Webhooks != nil {
		in, out := &in.Webhooks, &out.Webhooks
		*out = make(map[string]WebhookStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(int64)
		**out = **in
	}
	if in.ObservedSubResourceGenerations != nil {
		in, out := &in.ObservedSubResourceGenerations, &out.ObservedSubResourceGenerations
		*out = make(map[string]int64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepositoryStatus.
func (in *RepositoryStatus) DeepCopy() *RepositoryStatus {
	if in == nil {
		return nil
	}
	out := new(RepositoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequiredStatusChecks) DeepCopyInto(out *RequiredStatusChecks) {
	*out = *in
	if in.Checks != nil {
		in, out := &in.Checks, &out.Checks
		*out = make([]StatusCheck, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StrictPolicy != nil {
		in, out := &in.StrictPolicy, &out.StrictPolicy
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequiredStatusChecks.
func (in *RequiredStatusChecks) DeepCopy() *RequiredStatusChecks {
	if in == nil {
		return nil
	}
	out := new(RequiredStatusChecks)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleWorkflow) DeepCopyInto(out *RuleWorkflow) {
	*out = *in
	if in.Ref != nil {
		in, out := &in.Ref, &out.Ref
		*out = new(string)
		**out = **in
	}
	if in.ResolvedRepositoryID != nil {
		in, out := &in.ResolvedRepositoryID, &out.ResolvedRepositoryID
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleWorkflow.
func (in *RuleWorkflow) DeepCopy() *RuleWorkflow {
	if in == nil {
		return nil
	}
	out := new(RuleWorkflow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesetBypassActor) DeepCopyInto(out *RulesetBypassActor) {
	*out = *in
	if in.ActorID != nil {
		in, out := &in.ActorID, &out.ActorID
		*out = new(int64)
		**out = **in
	}
	if in.ActorSlug != nil {
		in, out := &in.ActorSlug, &out.ActorSlug
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesetBypassActor.
func (in *RulesetBypassActor) DeepCopy() *RulesetBypassActor {
	if in == nil {
		return nil
	}
	out := new(RulesetBypassActor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesetConditions) DeepCopyInto(out *RulesetConditions) {
	*out = *in
	if in.RefName != nil {
		in, out := &in.RefName, &out.RefName
		*out = new(RefNameCondition)
		(*in).DeepCopyInto(*out)
	}
	if in.RepositoryName != nil {
		in, out := &in.RepositoryName, &out.RepositoryName
		*out = new(RepositoryNameCondition)
		(*in).DeepCopyInto(*out)
	}
	if in.RepositoryProperty != nil {
		in, out := &in.RepositoryProperty, &out.RepositoryProperty
		*out = new(RepositoryPropertyCondition)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesetConditions.
func (in *RulesetConditions) DeepCopy() *RulesetConditions {
	if in == nil {
		return nil
	}
	out := new(RulesetConditions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesetPreset) DeepCopyInto(out *RulesetPreset) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesetPreset.
func (in *RulesetPreset) DeepCopy() *RulesetPreset {
	if in == nil {
		return nil
	}
	out := new(RulesetPreset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RulesetPreset) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesetPresetList) DeepCopyInto(out *RulesetPresetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RulesetPreset, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesetPresetList.
func (in *RulesetPresetList) DeepCopy() *RulesetPresetList {
	if in == nil {
		return nil
	}
	out := new(RulesetPresetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RulesetPresetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesetPresetSpec) DeepCopyInto(out *RulesetPresetSpec) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = new(RulesetConditions)
		(*in).DeepCopyInto(*out)
	}
	if in.BypassActors != nil {
		in, out := &in.BypassActors, &out.BypassActors
		*out = make([]RulesetBypassActor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Rules.DeepCopyInto(&out.Rules)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesetPresetSpec.
func (in *RulesetPresetSpec) DeepCopy() *RulesetPresetSpec {
	if in == nil {
		return nil
	}
	out := new(RulesetPresetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesetPresetStatus) DeepCopyInto(out *RulesetPresetStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesetPresetStatus.
func (in *RulesetPresetStatus) DeepCopy() *RulesetPresetStatus {
	if in == nil {
		return nil
	}
	out := new(RulesetPresetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RulesetRules) DeepCopyInto(out *RulesetRules) {
	*out = *in
	if in.Creation != nil {
		in, out := &in.Creation, &out.Creation
		*out = new(bool)
		**out = **in
	}
	if in.Update != nil {
		in, out := &in.Update, &out.Update
		*out = new(bool)
		**out = **in
	}
	if in.Deletion != nil {
		in, out := &in.Deletion, &out.Deletion
		*out = new(bool)
		**out = **in
	}
	if in.RequiredLinearHistory != nil {
		in, out := &in.RequiredLinearHistory, &out.RequiredLinearHistory
		*out = new(bool)
		**out = **in
	}
	if in.RequiredSignatures != nil {
		in, out := &in.RequiredSignatures, &out.RequiredSignatures
		*out = new(bool)
		**out = **in
	}
	if in.PullRequest != nil {
		in, out := &in.PullRequest, &out.PullRequest
		*out = new(PullRequestRule)
		(*in).DeepCopyInto(*out)
	}
	if in.RequiredStatusChecks != nil {
		in, out := &in.RequiredStatusChecks, &out.RequiredStatusChecks
		*out = new(RequiredStatusChecks)
		(*in).DeepCopyInto(*out)
	}
	if in.NonFastForward != nil {
		in, out := &in.NonFastForward, &out.NonFastForward
		*out = new(bool)
		**out = **in
	}
	if in.CommitMessagePattern != nil {
		in, out := &in.CommitMessagePattern, &out.CommitMessagePattern
		*out = new(PatternRule)
		(*in).DeepCopyInto(*out)
	}
	if in.CommitAuthorEmailPattern != nil {
		in, out := &in.CommitAuthorEmailPattern, &out.CommitAuthorEmailPattern
		*out = new(PatternRule)
		(*in).DeepCopyInto(*out)
	}
	if in.CommitterEmailPattern != nil {
		in, out := &in.CommitterEmailPattern, &out.CommitterEmailPattern
		*out = new(PatternRule)
		(*in).DeepCopyInto(*out)
	}
	if in.BranchNamePattern != nil {
		in, out := &in.BranchNamePattern, &out.BranchNamePattern
		*out = new(PatternRule)
		(*in).DeepCopyInto(*out)
	}
	if in.TagNamePattern != nil {
		in, out := &in.TagNamePattern, &out.TagNamePattern
		*out = new(PatternRule)
		(*in).DeepCopyInto(*out)
	}
	if in.CopilotReview != nil {
		in, out := &in.CopilotReview, &out.CopilotReview
		*out = new(CopilotCodeReviewRule)
		(*in).DeepCopyInto(*out)
	}
	if in.Workflows != nil {
		in, out := &in.Workflows, &out.Workflows
		*out = new(WorkflowsRule)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RulesetRules.
func (in *RulesetRules) DeepCopy() *RulesetRules {
	if in == nil {
		return nil
	}
	out := new(RulesetRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerGroup) DeepCopyInto(out *RunnerGroup) {
	*out = *in
	if in.Visibility != nil {
		in, out := &in.Visibility, &out.Visibility
		*out = new(string)
		**out = **in
	}
	if in.RestrictedToWorkflows != nil {
		in, out := &in.RestrictedToWorkflows, &out.RestrictedToWorkflows
		*out = new(bool)
		**out = **in
	}
	if in.SelectedWorkflows != nil {
		in, out := &in.SelectedWorkflows, &out.SelectedWorkflows
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerGroup.
func (in *RunnerGroup) DeepCopy() *RunnerGroup {
	if in == nil {
		return nil
	}
	out := new(RunnerGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretScanningDelegatedBypassOptions) DeepCopyInto(out *SecretScanningDelegatedBypassOptions) {
	*out = *in
	if in.Reviewers != nil {
		in, out := &in.Reviewers, &out.Reviewers
		*out = make([]*BypassReviewer, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(BypassReviewer)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretScanningDelegatedBypassOptions.
func (in *SecretScanningDelegatedBypassOptions) DeepCopy() *SecretScanningDelegatedBypassOptions {
	if in == nil {
		return nil
	}
	out := new(SecretScanningDelegatedBypassOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelectedAllowedActions) DeepCopyInto(out *SelectedAllowedActions) {
	*out = *in
	if in.GitHubOwnedAllowed != nil {
		in, out := &in.GitHubOwnedAllowed, &out.GitHubOwnedAllowed
		*out = new(bool)
		**out = **in
	}
	if in.VerifiedAllowed != nil {
		in, out := &in.VerifiedAllowed, &out.VerifiedAllowed
		*out = new(bool)
		**out = **in
	}
	if in.PatternsAllowed != nil {
		in, out := &in.PatternsAllowed, &out.PatternsAllowed
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelectedAllowedActions.
func (in *SelectedAllowedActions) DeepCopy() *SelectedAllowedActions {
	if in == nil {
		return nil
	}
	out := new(SelectedAllowedActions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusCheck) DeepCopyInto(out *StatusCheck) {
	*out = *in
	if in.IntegrationID != nil {
		in, out := &in.IntegrationID, &out.IntegrationID
		*out = new(int64)
		**out = **in
	}
	if in.AppSlug != nil {
		in, out := &in.AppSlug, &out.AppSlug
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusCheck.
func (in *StatusCheck) DeepCopy() *StatusCheck {
	if in == nil {
		return nil
	}
	out := new(StatusCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Team) DeepCopyInto(out *Team) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Team.
func (in *Team) DeepCopy() *Team {
	if in == nil {
		return nil
	}
	out := new(Team)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Team) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamList) DeepCopyInto(out *TeamList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Team, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamList.
func (in *TeamList) DeepCopy() *TeamList {
	if in == nil {
		return nil
	}
	out := new(TeamList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TeamList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamSpec) DeepCopyInto(out *TeamSpec) {
	*out = *in
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IDPGroup != nil {
		in, out := &in.IDPGroup, &out.IDPGroup
		*out = new(string)
		**out = **in
	}
	if in.OrganizationRoles != nil {
		in, out := &in.OrganizationRoles, &out.OrganizationRoles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OrganizationRefs != nil {
		in, out := &in.OrganizationRefs, &out.OrganizationRefs
		*out = make([]OrganizationRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamSpec.
func (in *TeamSpec) DeepCopy() *TeamSpec {
	if in == nil {
		return nil
	}
	out := new(TeamSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamStatus) DeepCopyInto(out *TeamStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PreviousOrganizationRefs != nil {
		in, out := &in.PreviousOrganizationRefs, &out.PreviousOrganizationRefs
		*out = make([]OrganizationRef, len(*in))
		copy(*out, *in)
	}
	if in.Slug != nil {
		in, out := &in.Slug, &out.Slug
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamStatus.
func (in *TeamStatus) DeepCopy() *TeamStatus {
	if in == nil {
		return nil
	}
	out := new(TeamStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Topic) DeepCopyInto(out *Topic) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Topic.
func (in *Topic) DeepCopy() *Topic {
	if in == nil {
		return nil
	}
	out := new(Topic)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookIgnorePreset) DeepCopyInto(out *WebhookIgnorePreset) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookIgnorePreset.
func (in *WebhookIgnorePreset) DeepCopy() *WebhookIgnorePreset {
	if in == nil {
		return nil
	}
	out := new(WebhookIgnorePreset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WebhookIgnorePreset) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookIgnorePresetList) DeepCopyInto(out *WebhookIgnorePresetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WebhookIgnorePreset, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookIgnorePresetList.
func (in *WebhookIgnorePresetList) DeepCopy() *WebhookIgnorePresetList {
	if in == nil {
		return nil
	}
	out := new(WebhookIgnorePresetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WebhookIgnorePresetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookIgnorePresetSpec) DeepCopyInto(out *WebhookIgnorePresetSpec) {
	*out = *in
	if in.IgnoreURLRegex != nil {
		in, out := &in.IgnoreURLRegex, &out.IgnoreURLRegex
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookIgnorePresetSpec.
func (in *WebhookIgnorePresetSpec) DeepCopy() *WebhookIgnorePresetSpec {
	if in == nil {
		return nil
	}
	out := new(WebhookIgnorePresetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookIgnorePresetStatus) DeepCopyInto(out *WebhookIgnorePresetStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookIgnorePresetStatus.
func (in *WebhookIgnorePresetStatus) DeepCopy() *WebhookIgnorePresetStatus {
	if in == nil {
		return nil
	}
	out := new(WebhookIgnorePresetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookPreset) DeepCopyInto(out *WebhookPreset) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookPreset.
func (in *WebhookPreset) DeepCopy() *WebhookPreset {
	if in == nil {
		return nil
	}
	out := new(WebhookPreset)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WebhookPreset) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookPresetList) DeepCopyInto(out *WebhookPresetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WebhookPreset, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookPresetList.
func (in *WebhookPresetList) DeepCopy() *WebhookPresetList {
	if in == nil {
		return nil
	}
	out := new(WebhookPresetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WebhookPresetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookPresetSecretSpec) DeepCopyInto(out *WebhookPresetSecretSpec) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookPresetSecretSpec.
func (in *WebhookPresetSecretSpec) DeepCopy() *WebhookPresetSecretSpec {
	if in == nil {
		return nil
	}
	out := new(WebhookPresetSecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookPresetSpec) DeepCopyInto(out *WebhookPresetSpec) {
	*out = *in
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(WebhookPresetSecretSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SecretValue != nil {
		in, out := &in.SecretValue, &out.SecretValue
		*out = new(string)
		**out = **in
	}
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
	if in.Events != nil {
		in, out := &in.Events, &out.Events
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SSLVerify != nil {
		in, out := &in.SSLVerify, &out.SSLVerify
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookPresetSpec.
func (in *WebhookPresetSpec) DeepCopy() *WebhookPresetSpec {
	if in == nil {
		return nil
	}
	out := new(WebhookPresetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookPresetStatus) DeepCopyInto(out *WebhookPresetStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookPresetStatus.
func (in *WebhookPresetStatus) DeepCopy() *WebhookPresetStatus {
	if in == nil {
		return nil
	}
	out := new(WebhookPresetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookStatus) DeepCopyInto(out *WebhookStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookStatus.
func (in *WebhookStatus) DeepCopy() *WebhookStatus {
	if in == nil {
		return nil
	}
	out := new(WebhookStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkflowsRule) DeepCopyInto(out *WorkflowsRule) {
	*out = *in
	if in.DoNotEnforceOnCreate != nil {
		in, out := &in.DoNotEnforceOnCreate, &out.DoNotEnforceOnCreate
		*out = new(bool)
		**out = **in
	}
	if in.Workflows != nil {
		in, out := &in.Workflows, &out.Workflows
		*out = make([]RuleWorkflow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkflowsRule.
func (in *WorkflowsRule) DeepCopy() *WorkflowsRule {
	if in == nil {
		return nil
	}
	out := new(WorkflowsRule)
	in.DeepCopyInto(out)
	return out
}
